Repository red-hat-storage/ocs-operator, pull requests merged in 2019-11, with the labels that each got.

#259 Bug 1755623: Fix OwnerReferences for Init Objects
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  go.sum
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#263 Bug 1750761: ocs-operator deploys csi-provisioners only on storage labelled nodes
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#261 Bug 1760477: Backport noobba version update to 2.0.5
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/S

#264 Fix indentation in csv-merger
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/XS

#265 Bug 1767408: storagecluster: Set correct Store for CephObjectStoreUser
  pkg/controller/storagecluster/initialization_reconciler.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#266 storagecluster: give the cephfs metadata pool the right failureDomain
  pkg/controller/storagecluster/initialization_reconciler.go
Labels: approved, lgtm, size/XS

#267 Bug 1763070: give cephfs metadata pool the right failure domain
  pkg/controller/storagecluster/initialization_reconciler.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#226 Implement uninstall cluster operation in functest
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  functests/config.go
  functests/setup_teardown.go
  go.mod
  go.sum
  hack/common.sh
  hack/functest.sh
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/deploy-manager/config.go
  pkg/deploy-manager/subscription.go
Labels: approved, lgtm, size/L

#270 Add csv resource to ceph must-gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, ok-to-test, size/XS

#269 Set OSD memory limits and add config map
  pkg/controller/defaults/resources.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, ok-to-test, size/M

#272 Bug 1765550: Set OSD memory limits and add config map
  pkg/controller/defaults/resources.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/M

#273 Fix Ceph config override data formatting
  go.mod
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/S

#274 Bug 1765550: Fix Ceph config override data formatting
  pkg/controller/storagecluster/reconcile.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#275 Bug 1767993: zone detection: check for nil topology labels
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#271 Remove local-storage from deploy-with-olm.yaml
  deploy/deploy-with-olm.yaml
  pkg/deploy-manager/subscription.go
Labels: approved, lgtm, size/M

#268 enhance(must-gather): Adds integration test for must-gather
  functests/must-gather_test.go
  go.sum
  hack/common.sh
  hack/functest.sh
  must-gather/functests/functests.sh
  must-gather/functests/integration/command_output_test.sh
Labels: approved, lgtm, size/M

#276 Bump noobaa-operator version
  Makefile
  deploy/olm-catalog/ocs-operator/0.0.1/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, ok-to-test, size/M

#279 pass NodeAffinity when creating noobaa instance
  go.mod
  go.sum
  pkg/controller/defaults/placements.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L

#278 tests: Capture ocs-must-gather on e2e failures
  hack/dump-debug-info.sh
Labels: approved, lgtm, size/S

#283 storagecluster: Append "-rook-ceph" to name of created CephCluster
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, size/S

#285 Revert noobaa-operator to 2.0.5 to unblock CI
  Makefile
  deploy/olm-catalog/ocs-operator/0.0.1/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  pkg/controller/defaults/placements.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#286 Bug 1755623: storagecluster: Append "-rook-ceph" to name of created CephCluster
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#287 enhance(must-gather): Use helper pod for collecting ceph output
  must-gather/Dockerfile
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/templates/ceph.conf.template
  must-gather/templates/keyring.template
  must-gather/templates/pod.template
Labels: approved, lgtm, size/L

#289 Bump noobaa-operator to 2.0.7 & re-apply affinity
  deploy/olm-catalog/ocs-operator/0.0.1/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  pkg/controller/defaults/placements.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L

#281 Bug 1770199: must-gather fails to collect OCS logs when a node is down
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#290 storagecluster: Use correct CephCluster name when ...
  pkg/controller/storagecluster/generate.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, size/M

#280 enhance(must-gather): Adds logic to skip NotReady Nodes
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/XS

#210 Introducing 0.0.2 version of ocs csv
  deploy/olm-catalog/ocs-operator/0.0.2/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/noobaa-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/noobaa-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/ocs-operator.v0.0.2.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/ocsinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/rook-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/rook-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/rook-monitor-role.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/rook-monitor-role_binding.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/storagecluster.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/storageclusterinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/ocs-operator.package.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, size/XXL

#288 enhance(must-gather): Adds support to collect output of non running pods
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/M

#295 Bug 1771402: backport must-gather fixes
  hack/dump-debug-info.sh
  must-gather/Dockerfile
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/templates/ceph.conf.template
  must-gather/templates/keyring.template
  must-gather/templates/pod.template
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#291 Bug 1771844: storagecluster: Use correct CephCluster name when ...
  pkg/controller/storagecluster/generate.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#292 Bug 1769634: NooBaa is not enforced to run on OCS storage nodes
  deploy/olm-catalog/ocs-operator/0.0.1/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  pkg/controller/defaults/placements.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/L

#211 Simplified cluster clean logic
  hack/cluster-clean.sh
Labels: approved, lgtm, size/M

#297 Bug 1770941: must-gather does not collect logs of Completed , Running 0/1 or CBLO ocs pods
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#293 csv-merger: Add text to identify internal CRDs
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/0.0.2/ocs-operator.v0.0.2.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/L

#298 Change CSV maintainer to red hat support
  deploy/olm-catalog/ocs-operator/0.0.2/ocs-operator.v0.0.2.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/S

#299 Bug 1772043: Change CSV maintainer to red hat support
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#300 Check for minimum number of storage nodes
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, size/M

#301 Bug 1768874: Check for minimum number of storage nodes
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#296 Fixing must-gather ceph resources according to shell check
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, ok-to-test, size/M

#303 Preserve rack FailureDomain if previously assigned
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, ok-to-test, size/M

#306 Bug 1772196: Preserve rack FailureDomain if previously assigned
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#305 fix(ocs-operator): Fixes panic of ocs-operator when running vmware
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/M

#307 Bug 1769596: Fixes panic of ocs-operator when running vmware
  pkg/controller/storagecluster/reconcile.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#304 Timeout ceph must gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, ok-to-test, size/XS

#308 Bug 1770293: Add timeout for ceph commands
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#309 Bump noobaa-operator to 2.0.8
  deploy/olm-catalog/ocs-operator/0.0.2/ocs-operator.v0.0.2.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, ok-to-test, size/S

#314 storagecluster: Do not set ownerRefs for StorageClasses
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
Labels: approved, lgtm, size/S

#315 Bug 1755623: storagecluster: Do not set ownerRefs for StorageClasses
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#189 Functest for upgrading the operator via olm
  functests/cluster_upgrade_test.go
  functests/config.go
  functests/setup_teardown.go
  go.sum
  hack/cluster-deploy.sh
  hack/common.sh
  hack/functest.sh
  hack/gen-deployment-yaml.sh
  pkg/deploy-manager/common.go
  pkg/deploy-manager/storagecluster.go
  pkg/deploy-manager/subscription.go
  tools/cluster-deploy/cluster-deploy.go
Labels: approved, lgtm, size/L

#317 Remove all unused references to local-storage registry image.
  functests/cluster_upgrade_test.go
  functests/config.go
  functests/setup_teardown.go
  hack/cluster-clean.sh
  hack/cluster-deploy.sh
  hack/common.sh
  hack/functest.sh
  hack/gen-deployment-yaml.sh
  pkg/deploy-manager/subscription.go
  tools/cluster-deploy/cluster-deploy.go
Labels: approved, lgtm, size/M

#316 Bug 1770941: Bump noobaa-operator to 2.0.8
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/S

#321 makes UpgradeTests as Pending
  functests/cluster_upgrade_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#313 Remove "internal" prefix from BackingStore and BucketClass
  deploy/olm-catalog/ocs-operator/0.0.2/ocs-operator.v0.0.2.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/S

#322 enhance(must-gather): Removes collection of empty files
  must-gather/collection-scripts/gather
Labels: approved, lgtm, size/XS

#323 Bug 1766646: must-gather: some current.log files remains empty
  must-gather/collection-scripts/gather
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#328 Bug 1774927: backing store and bucket class cards shouldn't be internal
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#324 fix(must-gather): updates collection script to collect CLBO pod logs
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/XS

#326 Bug 1768773: remove dependency on local storage operator
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#325 fix(must-gather): Updates gather script to collect pod spec of non-runing pods
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/S

#331 Bug 1770941: updates collection script to collect CLBO pod logs
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#332 Bug 1775059: Collect yaml file for osd-prepare pods in ocs-must-gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#327 enhance(must-gather): adds timeout and improves logging
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm, size/M

#333 Bug 1775567: must-gather stuck at "Collecting operator pod logs"
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#319 Bug 1768874: Disable CephObjectStore when the cloud provider is AWS.
  functests/storageclusterinitialization_test.go
  go.mod
  go.sum
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
  pkg/controller/storagecluster/platform_detection.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#335 Add more resources to RGW #334
  pkg/controller/defaults/resources.go
Labels: approved, lgtm, ok-to-test, size/XS

#336 fix(must-gather): fixes must-gather not able to collect o/p of ceph commands
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/XS

#340 fix(must-gather): fix collection of ceph volume o/p and prepare volume log
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/XS

#343 Bug 1776723: must_gather_command folder does not have any ceph command output files
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#342 enhance(must-gather): updates scripts to collect logs in a debug.log
  go.mod
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm, size/M

#348 Bump noobaa operator v2.0.9 + core v5.2.11
  deploy/olm-catalog/ocs-operator/0.0.2/ocs-operator.v0.0.2.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, ok-to-test, size/S

#350 Fix #347 - set go.mod dep k8s.io/cloud-provider kubernetes-1.14.9
  go.mod
  go.sum
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/XXL
