Repository red-hat-storage/ocs-operator, pull requests merged in 2019-09, with the labels that each got.

#79 Fix verify-latest-csv CI job
  .gitignore
  Makefile
  go.mod
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#78 fixes rook components placement config
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/XS

#73 csv: Update rook-ceph image
  deploy/olm-catalog/ocs-operator/0.0.1/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, size/M

#80 Updated README.md to include node label/taint details
  README.md
Labels: approved, lgtm, size/S

#82 Remove Rook-Ceph mgr anti-affinity
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/S

#83 doc: Add workarounds for known issue with taints
  README.md
Labels: approved, lgtm, size/S

#87 rbac: Update ClusterRole rules for ocs-operator
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  go.mod
  go.sum
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, size/M

#91 Openshift CI e2e build and deploy scripts
  Makefile
  hack/cluster-clean.sh
  hack/cluster-deploy.sh
  hack/common.sh
  hack/functest.sh
  openshift-ci/Dockerfile.deploy
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.registry.intermediate
Labels: approved, lgtm, size/L

#92 Don't enforce fixed name for StorageClusterInit
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/S

#54 unit testing for ocsinitialization_controller
  go.mod
  pkg/controller/ocsinitialization/ocsinitialization_controller_test.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: approved, lgtm, ok-to-test, size/XXL

#64 adding storageclusterinitialization CR/CRD to existing validation tests
  test/crd_validation_test.go
Labels: approved, lgtm, ok-to-test, size/S

#94 Openshift e2e CI debug
  hack/cluster-deploy.sh
  openshift-ci/Dockerfile.deploy
Labels: approved, lgtm, ok-to-test, size/S

#93 Automatically create StorageClusterInitialization for every StorageCluster
  go.mod
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#89 Bump rook version to 1.1.0-beta.0 and enable managed PDBs
  Makefile
  cmd/manager/main.go
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/util/status.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/XXL

#95 Change failure domain to zone for all cephv1.PoolSpecs
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#96 [Trivial] Remove fencing design that moved to rook.
  design/fencing_mitigation.md
Labels: approved, lgtm, ok-to-test, size/M

#84 doc: Clarify tainting of nodes
  README.md
Labels: approved, lgtm, size/M

#57 unit testing for storagecluster controllers
  go.mod
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller_test.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/XXL

#101 Move api from v1alpha1 to v1
  cmd/manager/main.go
  deploy/crds/ocs_v1_ocsinitialization_cr.yaml
  deploy/crds/ocs_v1_ocsinitialization_crd.yaml
  deploy/crds/ocs_v1_storagecluster_cr.yaml
  deploy/crds/ocs_v1_storagecluster_crd.yaml
  deploy/crds/ocs_v1_storageclusterinitialization_cr.yaml
  deploy/crds/ocs_v1_storageclusterinitialization_crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocsinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storagecluster.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storageclusterinitialization.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/addtoscheme_ocs_v1.go
  pkg/apis/ocs/v1/doc.go
  pkg/apis/ocs/v1/ocsinitialization_types.go
  pkg/apis/ocs/v1/register.go
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/storageclusterinitialization_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/apis/ocs/v1/zz_generated.defaults.go
  pkg/apis/ocs/v1/zz_generated.openapi.go
  pkg/apis/ocs/v1alpha1/doc.go
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
  pkg/controller/ocsinitialization/ocsinitialization_controller_test.go
  pkg/controller/ocsinitialization/sccs.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/utils.go
  pkg/controller/storageclusterinitialization/generate.go
  pkg/controller/storageclusterinitialization/noobaa_system_reconciler.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller_test.go
  pkg/controller/util/status.go
  test/crd_validation_test.go
Labels: approved, lgtm, size/L

#106 Revert "Change failure domain to zone for all cephv1.PoolSpecs"
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/XS

#102 New CSV: Bump rook version to v1.1.0-beta.1 and enable it's features
  deploy/deploy-with-olm.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/reconcile.go
  tools/csv-merger/csv-merger.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L

#109 updated csv-merger to remove duplicate CRDs in CSV
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/S

#108 csv: Fix alm-examples and regenerate CSV
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/S

#120 added permissions for ocs-operator to update storageClass
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, size/XS

#121 csv: Update images
  deploy/olm-catalog/ocs-operator/0.0.1/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, size/S

#122 storagecluster: Set topologyKey for podAntiAffinity
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/XS

#123 added NOOBAA_CORE_IMAGE and NOOBAA_MONGODB_IMAGE as env vars in OCS operator
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  tools/csv-checksum/csv-checksum.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test, size/M

#103 must-gather: Changes ceph gather script to collect ceph cmd output from toolbox
  deploy/crds/ocs_v1_storageclusterinitialization_crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storageclusterinitialization.crd.yaml
  go.mod
  hack/latest-csv-checksum.md5
  must-gather/collection-scripts/gather_ceph_resources
  pkg/apis/ocs/v1/storageclusterinitialization_types.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller_test.go
Labels: approved, lgtm, size/L

#126 Storage cluster initialization fixes
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/S

#124 updated ensureCephObjectStore func in StorageClusterInitialization
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/XS

#125 updated ensureCephObjectStoreUser func in StorageClusterInitialization
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/XS

#127 Use Recreate strategy for ocs-operator deployment
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, size/XS

#129 refactor(must-gather): remove info collections for cephnfs
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/XS

#133 csv: Allow setting images with envvars
  hack/generate-latest-csv.sh
Labels: approved, lgtm, size/S

#137 Additional README info pertaining to debugging e2e tests and the replica 2 workaround
  README.md
Labels: approved, lgtm, size/M

#136 Adds Owner Reference info to storageClusterInitialization resources
  pkg/controller/storageclusterinitialization/noobaa_system_reconciler.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/M

#138 Update openapi generated files
  .gitignore
  Makefile
  deploy/crds/ocs_v1_storageclusterinitialization_crd.yaml
  go.mod
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/apis/ocs/v1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#140 fix: custom placement not getting applied to CephCluster
  go.mod
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/S

#141 Add make targets for common prow tests
  Makefile
  build/Dockerfile
  hack/lint.sh
  hack/verify-generated.sh
  hack/verify-latest-csv.sh
  hack/verify-operator-sdk-gen.sh
Labels: approved, lgtm, size/M

#130 updated StorageCluster controller to reflect accurate .Status.Phase
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/util/status.go
Labels: approved, lgtm, size/M

#142 Changes Required Pod AntiAffinity to Preferred for MDS
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/S

#143 Changes RequiredDuringScheduling AntiAffinity to Preferred
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/S

#139 Allow customization of Ceph daemon resource requirements
  deploy/crds/ocs_v1_storagecluster_crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/M

#147 storagecluster: Remove misplaced return
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/XS

#148 Integrate new Rook 1.1.1 release
  deploy/olm-catalog/ocs-operator/0.0.1/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  functests/config.go
  functests/pvc_creation_test.go
  functests/setup_teardown.go
  go.mod
  hack/functest.sh
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm, size/L

#151 'make red-hat-storage-ocs-ci' for running downstream ocs-ci tests
  Makefile
  README.md
  hack/common.sh
  hack/functest.sh
  hack/red-hat-storage-ocs-ci-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#152 Default RBD storageclass to "ext4"
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/XS

#153 storageclusterinit: Do not set "pool" param for CephFS SC
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/XS

#155 Openshift ci build tools for red-hat-storage/ocs-ci execution
  hack/lint.sh
  hack/red-hat-storage-ocs-ci-tests.sh
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/M

#158 enhance: Adds support to generate CSVs in MacOS
  hack/source-manifests.sh
Labels: approved, lgtm, size/S

#159 Revert "storageclusterinit: Use provided CEPH_IMAGE for toolbox"
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/S

#160 build: Fix script breakages caused by 8ac9676
  hack/source-manifests.sh
Labels: approved, lgtm, size/XS

#164 deploy,csv: Add missing RBAC for deploying ServiceMonitors
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, size/XS

#161 Fix GOPATH dir permissions for build root container
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/S

#165 enhance: Adds go arch flags for building ocs-operator.
  Makefile
Labels: approved, lgtm, size/XS

#162 adding Resources spec to CSV for owned StorageCluster CRD
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/S

#171 Fixes openshift-ci tools container group GOPATH dir permissions
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#167 Disable MDB controllers.
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/reconcile.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test, size/XS

#168 bugfix - updated name spec of managed resources
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/S

#173 Adds support to run ceph commands from must-gather pod
  deploy/crds/ocs_v1_storageclusterinitialization_crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storageclusterinitialization.crd.yaml
  go.mod
  hack/latest-csv-checksum.md5
  must-gather/Centos-Base.repo
  must-gather/Dockerfile
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/templates/ceph.conf.template
  must-gather/templates/keyring.template
  pkg/apis/ocs/v1/storageclusterinitialization_types.go
  pkg/apis/ocs/v1/zz_generated.openapi.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller_test.go
Labels: approved, lgtm, size/L

#175 Temporarily set StorageClassDeviceSet.portable to false
  pkg/apis/ocs/v1/storagecluster_types.go
Labels: approved, lgtm, size/XS

#176 Add openshift ci build root container /etc/passwd permissions
  hack/common.sh
  hack/red-hat-storage-ocs-ci-tests.sh
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/S
