Repository red-hat-storage/ocs-operator, pull requests merged in 2019-10, with the labels that each got.

#177 enhance(must-gather): Adds support to collect osd prepare logs
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm, size/S

#170 Set default ResourceRequirements on all resources under OCS
  deploy/crds/ocs_v1_storageclusterinitialization_crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storageclusterinitialization.crd.yaml
  go.mod
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storageclusterinitialization_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/apis/ocs/v1/zz_generated.openapi.go
  pkg/controller/defaults/defaults.go
  pkg/controller/defaults/placements.go
  pkg/controller/defaults/resources.go
  pkg/controller/defaults/utils.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storageclusterinitialization/noobaa_system_reconciler.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
  pkg/deploy-manager/storagecluster.go
Labels: approved, lgtm, size/XL

#178 ocs-ci test-suite tools pod workaround
  Makefile
  hack/cluster-deploy.sh
  hack/common.sh
  hack/dump-debug-info.sh
  hack/functest.sh
  hack/red-hat-storage-ocs-ci-tests.sh
Labels: approved, lgtm, size/M

#180 Additional debug output when generating latest csv
  hack/source-manifests.sh
Labels: approved, lgtm, size/XS

#181 adding appropriate label to namespace created
  deploy/deploy-with-olm.yaml
  go.mod
  pkg/deploy-manager/common.go
  pkg/deploy-manager/subscription.go
Labels: approved, lgtm, size/S

#182 Dump stdout of source containers when executing source-manifests.sh for CSV gen
  hack/source-manifests.sh
Labels: approved, lgtm, size/S

#187 fix(must-gather): Freezing ocs-must-gather base image to 4.2
  go.mod
  must-gather/Dockerfile
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm, size/S

#190 fixed error handling when failing to Get noobaa cr
  pkg/controller/storageclusterinitialization/noobaa_system_reconciler.go
Labels: approved, lgtm, ok-to-test, size/S

#188 Improve `make cluster-deploy` and `make cluster-clean`
  functests/setup_teardown.go
  hack/cluster-clean.sh
  hack/common.sh
  pkg/deploy-manager/subscription.go
  tools/cluster-deploy/cluster-deploy.go
Labels: approved, lgtm, size/L

#193 Use latest master for ocs-ci test runs
  hack/common.sh
  hack/red-hat-storage-ocs-ci-tests.sh
Labels: approved, lgtm, size/S

#195 Add davidvossel to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#197 update rook version from v1.1.1 to v1.1.2
  deploy/olm-catalog/ocs-operator/0.0.1/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, ok-to-test, size/S

#150 Enable zone detection and automatic OSD placement calculation
  cmd/manager/main.go
  deploy/crds/ocs_v1_storagecluster_crd.yaml
  deploy/crds/ocs_v1_storageclusterinitialization_crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storagecluster.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storageclusterinitialization.crd.yaml
  deploy/role.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/devicesetconfig.go
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/storageclusterinitialization_types.go
  pkg/apis/ocs/v1/topologymap.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/apis/ocs/v1/zz_generated.openapi.go
  pkg/controller/defaults/defaults.go
  pkg/controller/defaults/placements.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/utils.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller_test.go
  pkg/controller/util/status.go
  test/crd_validation_test.go
Labels: approved, lgtm, size/XL

#198 updated noobaa version from v2.0.1 to v2.0.2
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/internal/codelocation/code_location.go
  vendor/github.com/onsi/ginkgo/internal/leafnodes/benchmarker.go
  vendor/github.com/onsi/ginkgo/internal/remote/aggregator.go
  vendor/github.com/onsi/ginkgo/internal/remote/server.go
  vendor/github.com/onsi/ginkgo/internal/spec/spec.go
  vendor/github.com/onsi/ginkgo/internal/spec/specs.go
  vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go
  vendor/github.com/onsi/ginkgo/reporters/default_reporter.go
  vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
  vendor/github.com/onsi/ginkgo/reporters/teamcity_reporter.go
  vendor/github.com/onsi/ginkgo/types/types.go
  vendor/github.com/onsi/gomega/.travis.yml
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/format/format.go
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/assignable_to_type_of_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_a_directory.go
  vendor/github.com/onsi/gomega/matchers/be_a_regular_file.go
  vendor/github.com/onsi/gomega/matchers/be_an_existing_file.go
  vendor/github.com/onsi/gomega/matchers/be_closed_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_element_of_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_empty_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_equivalent_to_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_false_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_identical_to.go
  vendor/github.com/onsi/gomega/matchers/be_nil_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_numerically_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_sent_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_temporally_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_true_matcher.go
  vendor/github.com/onsi/gomega/matchers/consist_of.go
  vendor/github.com/onsi/gomega/matchers/contain_element_matcher.go
  vendor/github.com/onsi/gomega/matchers/contain_substring_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_cap_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_key_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_key_with_value_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_occurred_matcher.go
  vendor/github.com/onsi/gomega/matchers/receive_matcher.go
  vendor/github.com/onsi/gomega/matchers/semi_structured_data_support.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraph.go
  vendor/github.com/onsi/gomega/matchers/type_support.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/XL

#201 Add skip-range option to csv generation
  hack/generate-unified-csv.sh
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/XS

#203 storageclusterinit: Set Spec.DataPool for CephObjectStore
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/XS

#205 Stabilization fixes for `make red-hat-storage-ocs-ci`
  pkg/deploy-manager/storagecluster.go
Labels: approved, lgtm, size/M

#208 Bug 1762335: csv: Change OCS_IMAGE to quay.io/ocs-operator:4.2.0
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#213 zone detection: check for nil topology labels
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, size/XS

#214 Expect a canary pod for each osd deployment
  pkg/deploy-manager/storagecluster.go
Labels: approved, lgtm, size/S

#209 Bug 1759288: storageclusterinit: Set Spec.DataPool for CephObjectStore
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#215 Remove README text related to a workaround we have addressed
  README.md
Labels: approved, lgtm, size/S

#219 must-gather:Adds support to collect ocs related operator logs
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/S

#221 Bug 1762236: must-gather doesn't collect openshift-storage pod logs if StorageCluster creation is not yet triggered
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#222 fix(must-gather): fix syntax error for noobaa gather script
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm, size/XS

#220 updated hack/cluster-clean.sh not to delete PVs, but only PVCs
  hack/cluster-clean.sh
Labels: approved, lgtm, ok-to-test, size/XS

#223 Bug 1764525: must-gather : error in syntax reported during ocs must-gather
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#228 fix(must-gather): Adds a safe replace function for sed
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/S

#229 Bug 1757863: most must_gather_commands files with output of ceph commands are empty
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#232 Update latest csv to noobaa 2.0.3
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/go.uber.org/multierr/.travis.yml
  vendor/go.uber.org/multierr/CHANGELOG.md
  vendor/go.uber.org/multierr/Makefile
  vendor/go.uber.org/multierr/README.md
  vendor/go.uber.org/multierr/error.go
  vendor/go.uber.org/multierr/go113.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#234 Bug 1757863: most must_gather_commands files with output of ceph commands are empty
  must-gather/Dockerfile
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#233 enhance(must-gather): This PR changes sed delimiter and also the must-gather base image to 4.2.0
  must-gather/Dockerfile
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/XS

#230 storageclusterinit: Update secret name for StorageClasses
  deploy/olm-catalog/ocs-operator/0.0.1/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/daemon/ceph/model/pool.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#236 Bug 1762335: Use 4.2 image in deploy-with-olm.yaml
  deploy/deploy-with-olm.yaml
  go.mod
  go.sum
  hack/common.sh
  hack/gen-deployment-yaml.sh
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/go.uber.org/multierr/.travis.yml
  vendor/go.uber.org/multierr/CHANGELOG.md
  vendor/go.uber.org/multierr/Makefile
  vendor/go.uber.org/multierr/README.md
  vendor/go.uber.org/multierr/error.go
  vendor/go.uber.org/multierr/go113.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#239 Check for one canary per node running osd
  pkg/deploy-manager/storagecluster.go
Labels: approved, lgtm, size/M

#207 OCSInitialization "enableCephTools" option
  deploy/crds/ocs_v1_ocsinitialization_crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocsinitialization.crd.yaml
  functests/ceph_tools_test.go
  go.mod
  hack/latest-csv-checksum.md5
  hack/red-hat-storage-ocs-ci-tests.sh
  pkg/apis/ocs/v1/ocsinitialization_types.go
  pkg/apis/ocs/v1/zz_generated.openapi.go
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
  pkg/controller/ocsinitialization/ocsinitialization_controller_test.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/L

#241 Set small mem request for osds in our ci storagecluster
  pkg/deploy-manager/storagecluster.go
Labels: approved, lgtm, size/XS

#242 Revert to non-master image for Rook-Ceph in latest CSV
  deploy/olm-catalog/ocs-operator/0.0.1/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, size/M

#243 Bug 1764984: Update Rook-Ceph image (1.1.4) and NooBaa image (2.0.3)
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/daemon/ceph/model/pool.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#247 Bug 1751956: Operator shouldn't allow creation of a second StorageCluster in the same namespace
  functests/config.go
  functests/storagecluster_creation_test.go
  go.mod
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/deploy-manager/config.go
  pkg/deploy-manager/storagecluster.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#227 disables InstallMode: AllNamespaces
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/S

#249 Update noobaa to 2.0.4
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, size/XS

#250 Bug 1763150: Update noobaa to 2.0.4
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#248 refactor(must-gather): Make use oc adm inspect
  must-gather/Dockerfile
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm, size/S

#256 Fix OwnerReferences for Init Objects
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  go.sum
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
Labels: approved, lgtm, size/M

#257 Dumping noobaa objects to debug info
  hack/dump-debug-info.sh
Labels: approved, lgtm, size/XS

#255 Bump to noobaa-operator 2.0.5
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, ok-to-test, size/S
