Repository red-hat-storage/ocs-operator, pull requests merged in 2019-08, with the labels that each got.

#12 adds OCSInitialData resource
  Gopkg.lock
  Gopkg.toml
  README.md
  cmd/manager/main.go
  deploy/crds/ocs_v1alpha1_ocsinitialization_cr.yaml
  deploy/crds/ocs_v1alpha1_ocsinitialization_crd.yaml
  deploy/role.yaml
  pkg/apis/ocs/group.go
  pkg/apis/ocs/v1alpha1/ocsinitialization_types.go
  pkg/apis/ocs/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/ocs/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_ocsinitialization.go
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
Labels: approved, lgtm, size/XL

#6 Add StorageDeviceSets to StorageCluster CRD.
  deploy/crds/ocs_v1alpha1_ocsinitialization_crd.yaml
  deploy/crds/ocs_v1alpha1_storagecluster_crd.yaml
  deploy/crds/ocs_v1alpha1_storagedeviceset_cr.yaml
  deploy/crds/ocs_v1alpha1_storagedeviceset_crd.yaml
  deploy/role.yaml
  pkg/apis/ocs/v1alpha1/storagecluster_types.go
  pkg/apis/ocs/v1alpha1/storagedeviceset_types.go
  pkg/apis/ocs/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/ocs/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_storagedeviceset.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagedeviceset/storagedeviceset_controller.go
Labels: approved, lgtm, ok-to-test, size/L

#14 Update OWNERS
  OWNERS
Labels: approved, size/XS

#15 Extend the OWNERS file to unblock a merging impasse
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#19 Move manifests to different location in registry image
  deploy/Dockerfile
  hack/build-registry-bundle.sh
Labels: approved, lgtm, size/S

#18 enhance: Adds support to collect the json output of ceph commands
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/XS

#24 changed noobaa resources names and labels in gather_noobaa_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm, ok-to-test, size/XS

#28 Update a comment
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/XS

#32 Fixed a broken link and Openshift
  README.md
Labels: approved, lgtm, size/S

#33 Updates ocs-must-gather image registry with upstream
  must-gather/README.md
Labels: approved, lgtm, size/XS

#30 Updates to CSV and OLM deployment
  deploy/crds/ocs_v1alpha1_storagecluster_cr.yaml
  deploy/deploy-with-olm.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/rookcephfilesystems.crd.yaml
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/XL

#29 Add StorageClusterInitialization CRD
  deploy/crds/ocs_v1alpha1_storageclusterinitialization_cr.yaml
  deploy/crds/ocs_v1alpha1_storageclusterinitialization_crd.yaml
  deploy/role.yaml
  pkg/apis/ocs/v1alpha1/storageclusterinitialization_types.go
  pkg/apis/ocs/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_storageclusterinitialization.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Labels: approved, lgtm, size/L

#36 Add StorageClusterInitialization to CSV
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storageclusterinitialization.crd.yaml
Labels: approved, lgtm, size/M

#39 Add CSV check to the documentation
  README.md
Labels: approved, lgtm, size/S

#43 Set 'GO111MODULE=on' when building ocs-operator
  Makefile
Labels: approved, lgtm, size/XS

#37 updates CSV : Deploy Local-Storage-Operator
  deploy/deploy-with-olm.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#44 Lock operator-sdk version and force use of vendor dir for builds
  Makefile
Labels: approved, lgtm, ok-to-test, size/S

#45 Fix makefile path location variable
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#47 api: Update generated files
  deploy/crds/ocs_v1alpha1_storageclusterinitialization_crd.yaml
  pkg/apis/ocs/v1alpha1/storagecluster_types.go
  pkg/apis/ocs/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#51 adds Placement Configuration for rook-ceph agents and services
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  pkg/controller/storagecluster/reconcile.go
Labels: approved, ok-to-test, size/M

#55 Adds 'watch' RBAC for ceph cluster objects
  deploy/role.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#58 Unbreak ocs-operator
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/M

#59 updates build/Dockerfile to use ubi8-minimal base image
  build/Dockerfile
Labels: approved, lgtm, size/XS

#62 deploy: Point ocs-dev registry image
  deploy/deploy-with-olm.yaml
Labels: approved, lgtm, size/XS

#49 updated CSV & Bundle to enable OCS Monitoring
  deploy/olm-catalog/ocs-operator/0.0.1/role_binding_metrics.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/role_binding_monitor.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/role_metrics.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/role_monitor.yaml
Labels: approved, lgtm, size/M

#65 csv: Update alm-examples
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#67 api: Add Portable property to StorageDeviceSet
  deploy/crds/ocs_v1alpha1_storagecluster_cr.yaml
  deploy/crds/ocs_v1alpha1_storagecluster_crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storagecluster.crd.yaml
  go.mod
  go.sum
  pkg/apis/ocs/v1alpha1/storagecluster_types.go
  pkg/controller/storagecluster/reconcile.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/network.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1alpha2/network.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1alpha2/types.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1alpha2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#68 updates permission of ocs-operator serviceaccount
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, ok-to-test, size/S

#56 follow-up for openshift/ocs-operator/pull/51
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/L

#70 Improve Latest CSV Generation Workflow.
  Makefile
  README.md
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test, size/M

#72 csv: Use image versions inplace of SHA
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
Labels: approved, lgtm, size/S

#74 Tool to build checksum for csv generation
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  tools/csv-checksum/csv-checksum.go
Labels: approved, lgtm, size/L

#66 Move initialization tasks from OCSInit to StorageClusterInit
  deploy/crds/ocs_v1alpha1_ocsinitialization_crd.yaml
  deploy/crds/ocs_v1alpha1_storageclusterinitialization_crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocsinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/storageclusterinitialization.crd.yaml
  go.mod
  go.sum
  pkg/apis/ocs/v1alpha1/ocsinitialization_types.go
  pkg/apis/ocs/v1alpha1/storageclusterinitialization_types.go
  pkg/apis/ocs/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/ocs/v1alpha1/zz_generated.openapi.go
  pkg/controller/ocsinitialization/generate.go
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
  pkg/controller/storageclusterinitialization/generate.go
  pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL
