Repository red-hat-storage/ocs-operator, pull requests merged in 2019-07, with the labels that each got.

#3 Fix lint issues for CI
  version/version.go
Labels: approved, lgtm, ok-to-test, size/XS

#9 enhance: Adds code for OCS-must-gather
  Makefile
  must-gather/Dockerfile
  must-gather/OWNERS
  must-gather/README.md
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm, size/L

#10 refactors Reconcile to support Update and prepare for more resource types
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller.go
Labels: approved, lgtm, size/M

#4 [Design] Fencing mitigation.
  design/fencing_mitigation.md
Labels: approved, lgtm, ok-to-test, size/M
