Repository red-hat-storage/ocs-operator, pull requests merged in 2019-12, with the labels that each got.

#349 Bug 1778805: Backport 4.2 - Bump noobaa operator v2.0.9 + core v5.2.11
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/S

#353 Bug 1778805: deploy: Disable csi-snapshotter in Rook deployment
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#352 deploy: Disable csi-snapshotter in Rook deployment
  deploy/olm-catalog/ocs-operator/0.0.2/ocs-operator.v0.0.2.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/XS

#354 fix(functest): fixes duplicate call for must-gather functest.
  hack/functest.sh
Labels: approved, lgtm, size/XS

#361 defaults: Reduce CPU request for OSD to 1
  pkg/controller/defaults/resources.go
Labels: approved, lgtm, size/XS

#362 Bug 1780157: defaults: Reduce CPU request for OSD to 1
  pkg/controller/defaults/resources.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#355 Update CSV for 4.3.0
  deploy/olm-catalog/ocs-operator/4.3.0/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/noobaa-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/noobaa-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocsinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/rook-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/rook-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/rook-monitor-role.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/rook-monitor-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/storagecluster.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/storageclusterinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/ocs-operator.package.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/L

#360 Fix #351 - exclude non-owned (required) CRDs manifests
  deploy/olm-catalog/ocs-operator/4.3.0/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/objectbucketclaim.crd.yaml
  go.sum
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test, size/L

#337 Fix Scripts according to shellcheck
  Makefile
  hack/build-functest.sh
  hack/cluster-clean.sh
  hack/common.sh
  hack/functest.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/red-hat-storage-ocs-ci-tests.sh
  hack/shellcheck-test.sh
  hack/source-manifests.sh
  hack/verify-latest-deploy-yaml.sh
  hack/verify-operator-sdk-gen.sh
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_noobaa_resources
  must-gather/functests/functests.sh
  must-gather/functests/integration/command_output_test.sh
Labels: approved, lgtm, ok-to-test, size/L

#373 Fix productization requirements in CSV
  deploy/deploy-with-olm.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  go.mod
  hack/latest-csv-checksum.md5
  pkg/deploy-manager/subscription.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/M

#376 Bug 1784031: [release-4.2] Fix productization requirements in CSV
  deploy/deploy-with-olm.yaml
  deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
  go.sum
  hack/latest-csv-checksum.md5
  pkg/deploy-manager/subscription.go
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#363 Add documentation on the OpenShift-CI integration and OLM catalog generation
  README.md
  docs/catalog-generation.md
  docs/openshift-ci.md
Labels: approved, lgtm, size/L

#378 Fixing the source-manifests.sh script
  hack/source-manifests.sh
Labels: approved, lgtm, ok-to-test, size/XS
