Repository red-hat-storage/ocs-operator, pull requests merged in 2020-07, with the labels that each got.

#534 added rook-csi-resizer to relatedImages
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test

#595 Bug 1847982: Release 4.5: backport pr #534
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test

#597 Update OSD QoS to Guaranteed
  pkg/controller/defaults/resources.go
Labels: approved, lgtm

#568 Bump OCS Operator to version 4.6.0
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/latest-csv-checksum.md5
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
  version/version.go
Labels: approved, lgtm

#599 Bug 1836359: Update OSD QoS to Guaranteed
  pkg/controller/defaults/resources.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#602 Prevent multiple mds from running on the same node
  pkg/controller/defaults/placements.go
  pkg/controller/storagecluster/placement.go
Labels: approved, lgtm

#591 Reverting Noobaa's SCC priority
  pkg/controller/ocsinitialization/sccs.go
Labels: approved, lgtm, ok-to-test

#588 Fix a bad substitution
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm

#589 Remove the host from crush map
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#600 Bug 1846085: [release-4.5] Updates don't work on StorageClass
  pkg/controller/storagecluster/initialization_reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#608 Bug 1840539: [release 4.5] Remove the host from the crush map
  pkg/controller/storagecluster/reconcile.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#610 do not encode rgw label endpoint
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
Labels: approved, lgtm

#613 Fix problematic permissions
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  hack/source-manifests.sh
Labels: approved, lgtm

#617 Bug 1851328: [release-4.5] Fix problematic permissions
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  hack/source-manifests.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#620 must-gather: Add more timeout to ceph and noobaa resources
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm

#618 Properly append LabelSelector
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/placement.go
  pkg/controller/storagecluster/placement_test.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#623 Bug 1854651: [release 4.5] backport pr 618 - fix segfault
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/placement.go
  pkg/controller/storagecluster/placement_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#625 Add csv resource
  must-gather/collection-scripts/gather
Labels: approved, lgtm

#627 external cluster: Fix propagation of connected status
  pkg/controller/util/status.go
Labels: approved, lgtm

#609 Undo and cleanly redo whitespace changes included in #563
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#614 Add code coverage for unit-tests.
  Makefile
Labels: approved, lgtm

#624 Add must-gather image to csv-merger relatedImages
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  tools/csv-checksum/csv-checksum.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#629 Shellcheck cleanup - make shellcheck actually run and fail
  hack/build-must-gather.sh
  hack/build-operator-index.sh
  hack/build-operator.sh
  hack/common.sh
  hack/ensure-operator-sdk.sh
  hack/generate-appregistry.sh
  hack/generate-k8s-openapi.sh
  hack/generate-latest-csv.sh
  hack/operator-sdk-common.sh
  hack/red-hat-storage-ocs-ci-tests.sh
  hack/shellcheck-test.sh
  hack/source-manifests.sh
  hack/verify-operator-bundle.sh
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#631 source-manifests: fix csv generation
  hack/source-manifests.sh
Labels: approved, lgtm

#636 Fix OCS tools and enable "make" tasks on MacOs environments
  go.mod
  go.sum
  hack/common.sh
  hack/ensure-opm.sh
  hack/lint.sh
  hack/operator-sdk-common.sh
  hack/shellcheck-test.sh
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, ok-to-test

#639 must-gather: Add more resources to must-gather
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#642 Change maintainer email
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#643 Bug 1817538: [release-4.5] change maintainer email
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#644 Fix incorrect quoting of must-gather commands
  must-gather/collection-scripts/gather
Labels: approved, lgtm

#647 Bug 1860034: Toolbox updated to point to the renamed secret keys
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#637 Added cephcluster_test in storagecluster and made necessary refactor changes
  pkg/controller/storagecluster/cephcluster_test.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#649 must-gather: fix newly uncovered shellcheck error
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#651 Bug 1861657: [release-4.4] owning ob obc crds
  deploy/olm-catalog/ocs-operator/4.4.0/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#634 Add MCG spec section to the storage cluster CRD
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#655 Update noobaa image reference and regenerate latest csv
  deploy/olm-catalog/ocs-operator/manifests/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, needs-ok-to-test

#587 Few CRD fixes for Rook-Ceph
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/cephcluster.go
Labels: approved, lgtm

#658 must-gather: Remove timeout option from oc inspect commands
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm

#660 updates BackingStore and NooBaa CRDs
  deploy/olm-catalog/ocs-operator/manifests/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/noobaa.crd.yaml
Labels: approved, lgtm
