Repository red-hat-storage/ocs-operator, pull requests merged in 2020-03, with the labels that each got.

#430 Reduce TargetSizeRatio from .5 to .49 to avoid HEALTH_WARN
  pkg/controller/storagecluster/initialization_reconciler.go
Labels: approved, kind/bug, lgtm, size/XS

#433 Adds new OLM annotations to CSV
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/XS

#424 ob and obc will move to owned instead of required
  deploy/olm-catalog/ocs-operator/4.3.0/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  go.sum
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test, size/L

#345 Adding Testcase to check accuracy of the data
  functests/common.go
  functests/data_validation_test.go
Labels: approved, lgtm, ok-to-test, size/L

#438 Hide ObjectBuckets & ObjectBucketClaims APIs
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/XS

#437 disable volume expansion for OCS PV
  pkg/controller/storagecluster/initialization_reconciler.go
Labels: approved, lgtm, size/XS

#440 Bug 1810011: PV resize should be blocked in OCS 4.3
  pkg/controller/storagecluster/initialization_reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#393 OCS Independent Mode
  deploy/crds/ocs_v1_storagecluster_crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/M

#444 Bump to OCS v4.4.0
  deploy/olm-catalog/ocs-operator/4.4.0/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/noobaa-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/noobaa-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/ocsinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/rook-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/rook-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/rook-monitor-role.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/rook-monitor-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/storagecluster.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/storageclusterinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/ocs-operator.package.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  version/version.go
Labels: approved, lgtm, size/XXL

#432 generate relatedImages in ocs CSV
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test, size/M

#448 Check for nil pointer with StorageClass name
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#449 Pedantic spelling corrections for StorageClass
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#457 Disable upgrade test.
  functests/cluster_upgrade_test.go
Labels: approved, lgtm

#460 Bug 1798571: [release-4.4] Make ObjectBucket & ObjectBucketClaim CRs owned and hide their APIs
  deploy/olm-catalog/ocs-operator/4.4.0/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/noobaa-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/noobaa-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/ocsinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/rook-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/rook-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/rook-monitor-role.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/rook-monitor-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/storagecluster.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/storageclusterinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/ocs-operator.package.yaml
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
  version/version.go
Labels: approved, bugzilla/valid-bug, lgtm

#447 Fix incorrect container image URL
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#446 Adds skipRange to CSV
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm

#436 Adds crombus to the owner file.
  must-gather/OWNERS
Labels: approved, lgtm, size/XS

#461 [Release 4.4] Fix incorrect container image URL
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, lgtm

#462 Bug 1798052: [release-4.4] backport 432 - generate relatedImages in OCS CSV
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, lgtm

#463 Master bump version to 4.5.0
  deploy/olm-catalog/ocs-operator/4.5.0/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/noobaa-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/noobaa-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/ocsinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/rook-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/rook-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/rook-monitor-role.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/rook-monitor-role_binding.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/storagecluster.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/storageclusterinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/ocs-operator.package.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  version/version.go
Labels: approved, lgtm

#464 Add Umanga to the OWNERS.
  OWNERS
Labels: approved, lgtm

#465 Support overriding resizer image
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  docs/catalog-generation.md
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  tools/csv-checksum/csv-checksum.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#466 remove hardcoded IMAGE_RUN_CMD in common.sh
  hack/common.sh
Labels: approved, lgtm

#467 Bug 1818124: Support overriding resizer image
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  docs/catalog-generation.md
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  tools/csv-checksum/csv-checksum.go
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, lgtm

#469 Bug 1818124: Support overriding resizer image
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  docs/catalog-generation.md
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  tools/csv-checksum/csv-checksum.go
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, lgtm
