Repository red-hat-storage/ocs-operator, pull requests merged in 2020-06, with the labels that each got.

#513 Add rbd, subvolume and listing of pool names command in ceph must-gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#527 Add gather pvc info from all namespaces
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#535 Add noobaa raw output for noobaa obc list
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm

#477 creates default rook-ceph-operator-config ConfigMap
  deploy/crds/ocs.openshift.io_ocsinitializations_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocsinitialization.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/ocsinitialization_types.go
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
  pkg/controller/ocsinitialization/ocsinitialization_controller_test.go
Labels: approved, lgtm

#442 Expose noobaa endpoint resource management to OCS operator
  pkg/controller/defaults/resources.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/deploy-manager/storagecluster.go
Labels: ok-to-test, size/M

#543 fix: Handled placements for storageDeviceSets
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#538 fix: add missing Rook-Ceph operator env variable
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#539 fix: OBC StorageClass for external cluster
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
Labels: approved, lgtm

#546 Improve formatting in getPlacement()
  pkg/controller/storagecluster/placement.go
Labels: approved, lgtm

#488 Add controller-expand-secret and namespace to SC
  pkg/controller/storagecluster/initialization_reconciler.go
Labels: approved, lgtm

#536 go.mod: replace non-existent tag
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#544 Makefile: run deps-update when go.mod changes
  Makefile
Labels: approved, lgtm

#550 Makefile: let `make` do the same as `make all`
  Makefile
Labels: approved, lgtm

#551 Makefile: fix typo in PHONY list
  Makefile
Labels: approved, lgtm

#549 Added cephfilesystem to internal-object annotations
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#554 Don't set CSI provisioner node affinity in default config
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#556 Delete the storageclasses during uninstall
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm

#558 StorageCluster: delete the default node selector labels during uninstall
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm

#560 StorageCluster: remove node taints during uninstall
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm

#540 Disable CephObjectStore when the cloud provider is Azure and gcp.
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/platform_detection.go
Labels: approved, lgtm

#559 Simplify getStorageClusterEligibleNodes() a bit more
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#565 must-gather: add more ceph commands
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, ok-to-test

#564 Optional timestamp while generating CSV
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#511 Creating a new noobaa SCC
  pkg/controller/ocsinitialization/sccs.go
Labels: approved, lgtm, ok-to-test

#571 Fix GCP cloud platform ProvideID is gce(google compute engine)
  pkg/controller/storagecluster/platform_detection.go
Labels: approved, lgtm, ok-to-test

#567 Refactor: Moving the logic for modifying/creating CephCluster
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#569 independent mode: expose rgw endpoint as a label
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
Labels: approved, lgtm

#522 Support metadata pvc for a given OSD
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  test/crd_validation_test.go
Labels: approved, lgtm, ok-to-test

#580 encore rgw endpoint for external mode
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
Labels: approved, lgtm

#585 Bug 1847875: [release-4.5] independent mode: expose rgw endpoint as a label
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#593 Move ObjectBucket and ObjectBucketClaim CRDs to owned instead of required.
  deploy/olm-catalog/ocs-operator/manifests/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#594 Bug 1798571: Release 4.5: owning ob and obc crds
  deploy/olm-catalog/ocs-operator/manifests/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#576 Bug 1849105: [release-4.5] StorageCluster: delete the default node selector labels during uninstall
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#563 Refactor: Moving StorageClusterInit in a new file.
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storageclusterinit.go
Labels: approved, lgtm

#577 Bug 1849105: [release-4.5] StorageCluster: remove node taints during uninstall
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#590 Ceph(fix): Updates given to StorageClass won't work.
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/initialization_reconciler.go
Labels: approved, lgtm
