Repository red-hat-storage/ocs-operator, pull requests merged in 2020-08, with the labels that each got.

#664 Bug 1858900:must-gather: Remove timeout option from oc inspect commands
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#661 Remove RGW storage class as required from the UI validation
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, kind/bug, lgtm

#669 Bug 1862449: Remove validation for RGW Endpoint during creation of External Storge cluster in OCS UI
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#665 Update noobaa-core image
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
Labels: approved, lgtm, ok-to-test

#659 use controller-gen v0.2.5 to fix validations for int-or-string types
  Makefile
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
Labels: approved, lgtm

#671 Added the pattern to the end of the command
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#652 Refactored cephcluster_tests.go
  pkg/controller/storagecluster/cephcluster_test.go
Labels: approved, lgtm

#668 Add csi log level to rook-ceph-operator-config configmap
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
Labels: approved, lgtm

#672 Bug 1840539: [release 4.5] Added the pattern to the end of the command
  pkg/controller/storagecluster/reconcile.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#673 Bug 1859516: x-int-or-string is not allowed for some fields
  Makefile
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#667 Lint fix index image validation
  deploy/bundlemanifests/noobaa-metrics-role.yaml
  deploy/bundlemanifests/noobaa-metrics-role_binding.yaml
  deploy/bundlemanifests/rook-metrics-role.yaml
  deploy/bundlemanifests/rook-metrics-role_binding.yaml
  deploy/bundlemanifests/rook-monitor-role.yaml
  deploy/bundlemanifests/rook-monitor-role_binding.yaml
  deploy/olm-catalog/ocs-operator/manifests/noobaa-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/manifests/noobaa-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/rook-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/manifests/rook-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/manifests/rook-monitor-role.yaml
  deploy/olm-catalog/ocs-operator/manifests/rook-monitor-role_binding.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#676 removes mhrivnak (me) from OWNERS
  OWNERS
Labels: approved, lgtm

#675 Reconcile CephObjectStores, CephObjectStoreUsers, and CephFilesystems
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/storageclusterinit.go
Labels: approved, lgtm

#645 StorageCluster: perform delete of cephCluster
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm

#683 add agarwal-mudit(myself) to OWNERS file
  OWNERS
Labels: approved, lgtm

#682 Fix uninstall lint error
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm

#674 Added annotation to the Job
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#677 Remove validation for ceph-fs Storage class in UI for External mode creation
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#685 Bug 1866155: Remove validation for ceph-fs in UI for External Mode Creation
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#592 Refactor: initialization_reconciler.go
  pkg/controller/storagecluster/cephblockpools.go
  pkg/controller/storagecluster/cephfilesystem.go
  pkg/controller/storagecluster/cephobjectstores.go
  pkg/controller/storagecluster/cephobjectstoreusers.go
  pkg/controller/storagecluster/external_resources.go
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/storageclasses.go
Labels: approved, lgtm

#686 Bug 1857802: [release-4.5] Reconcile CephObjectStores, CephObjectStoreUsers, and CephFilesystems
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#691 enables RBD per image IO stats collection by default
  pkg/controller/storagecluster/cephblockpools.go
Labels: approved, lgtm

#641 Design document for Custom Resource Metrics Exporter
  docs/design/metrics-exporter.md
Labels: approved, lgtm

#687 Containerize operator binary build
  Makefile
  build/Dockerfile.build
  hack/build-container.sh
  hack/common.sh
  hack/go-build.sh
Labels: approved, lgtm

#692 Feature design template
  docs/design/template.md
Labels: approved, lgtm

#696 Update to newer rook/ceph:v1.4 tag to pick up csv fix
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/generate-latest-csv.sh
Labels: approved, lgtm

#653 Refactor: initialization_reconciler_test.go
  pkg/controller/storagecluster/cephblockpools_test.go
  pkg/controller/storagecluster/cephfilesystem_test.go
  pkg/controller/storagecluster/cephobjectstores_test.go
  pkg/controller/storagecluster/cephobjectstoreusers_test.go
  pkg/controller/storagecluster/external_resources_test.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/storageclasses_test.go
Labels: approved, lgtm

#699 Correct the make target in the build container
  build/Dockerfile.build
Labels: approved, lgtm

#698 Update the CSV
  deploy/olm-catalog/ocs-operator/manifests/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
Labels: approved, lgtm

#615 Separating node topology, racks and failure domains logic
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/topology.go
Labels: approved, lgtm, ok-to-test

#697 Disable validation of CephFS secrets
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#706 [release-4.5] Bug 1866155: Disable validation of CephFS secrets
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#693 Bug 1867885: [release-4.5][Backport] Lint fix index image validation
  deploy/bundlemanifests/noobaa-metrics-role.yaml
  deploy/bundlemanifests/noobaa-metrics-role_binding.yaml
  deploy/bundlemanifests/rook-metrics-role.yaml
  deploy/bundlemanifests/rook-metrics-role_binding.yaml
  deploy/bundlemanifests/rook-monitor-role.yaml
  deploy/bundlemanifests/rook-monitor-role_binding.yaml
  deploy/olm-catalog/ocs-operator/manifests/noobaa-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/manifests/noobaa-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/rook-metrics-role.yaml
  deploy/olm-catalog/ocs-operator/manifests/rook-metrics-role_binding.yaml
  deploy/olm-catalog/ocs-operator/manifests/rook-monitor-role.yaml
  deploy/olm-catalog/ocs-operator/manifests/rook-monitor-role_binding.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#689 StorageCluster: log unknown error in deleteStorageClasses
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm, ok-to-test

#703 remove CSI_ENABLE_SNAPSHOTTER from rook ENV
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#710 enhances containerized build
  build/Dockerfile.build
  hack/build-container.sh
Labels: approved, lgtm

#711 must-gather: add ROOK_CEPH_SECRET creds used by operator
  must-gather/templates/pod.template
Labels: approved, lgtm

#713 Add ability to set noobaa cleanup policy during uninstall
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, ok-to-test

#722 Revert PR #675
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/cephfilesystem.go
  pkg/controller/storagecluster/cephobjectstores.go
  pkg/controller/storagecluster/cephobjectstoreusers.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/storageclusterinit.go
Labels: approved, lgtm

#726 Bug 1857802: Revert PR #675
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/cephfilesystem.go
  pkg/controller/storagecluster/cephobjectstores.go
  pkg/controller/storagecluster/cephobjectstoreusers.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#717 Fix logger instantiation
  cmd/manager/main.go
Labels: approved, lgtm

#721 Change the default max number of noobaa endpoint
  pkg/controller/storagecluster/noobaa_system_reconciler.go
Labels: approved, lgtm, ok-to-test

#688 Update verify targets
  Makefile
  deploy/csv-templates/crds/cephblockpools.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephclients.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephclusters.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephfilesystems.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephnfses.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectrealms.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectstores.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectstoreusers.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectzonegroups.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectzones.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephrbdmirrors.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/noobaa-crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_ocsinitializations_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusterinitializations_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs_v1_ocsinitialization_cr.yaml
  deploy/csv-templates/crds/ocs_v1_storagecluster_cr.yaml
  deploy/csv-templates/crds/ocs_v1_storageclusterinitialization_cr.yaml
  deploy/csv-templates/noobaa-csv.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/csv-templates/rook-csv.yaml.in
  docs/catalog-generation.md
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  hack/source-manifests.sh
  hack/verify-generated.sh
  hack/verify-latest-csv.sh
  hack/verify-latest-deploy-yaml.sh
  tools/csv-checksum/csv-checksum.go
Labels: approved, lgtm

#621 Adding 'SnapshotClass' into OCS-Operator
  cmd/manager/main.go
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/role.yaml
  go.mod
  go.sum
  hack/common.sh
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/generate.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/storageclusterinit.go
  pkg/controller/storagecluster/volumesnapshotterclasses.go
  pkg/controller/storagecluster/volumesnapshotterclasses_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#728 Fix CSV templates after SnapshotClass update
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/csv-templates/rook-csv.yaml.in
Labels: approved, lgtm

#638 Ceph object store for external cluster
  pkg/controller/storagecluster/cephobjectstores.go
  pkg/controller/storagecluster/cephobjectstores_test.go
  pkg/controller/storagecluster/external_resources.go
  pkg/controller/storagecluster/external_resources_test.go
  pkg/controller/storagecluster/generate.go
  pkg/controller/storagecluster/storageclasses.go
Labels: approved, lgtm, ok-to-test

#714 Whitelist instead of Blacklist to hide internal objects
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#525 Added support for multus in OCS
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/crds/ocs_v1_storagecluster_cr.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs_v1_storagecluster_cr.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  docs/multus.md
  go.sum
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, ok-to-test

#596 Refactoring of all functional tests under `functest` dir
  functests/ceph_tools_test.go
  functests/cluster_upgrade_test.go
  functests/data_validation_test.go
  functests/must-gather_test.go
  functests/pvc_creation_test.go
  functests/storagecluster_creation_test.go
  functests/storageclusterinitialization_test.go
Labels: approved, lgtm, ok-to-test

#666 Remove excess logs from OCS operator
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, needs-ok-to-test

#718 StorageCluster: add uninstall mode
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#730 change from label to annotation for the uninstall-cleanup policy
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#731 StorageCluster: set uninstall defaults
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#720 Re-structure of ocs-must-gather
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_namespaced_resources
Labels: approved, lgtm

#732 Add labels for supported architectures
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#729 Fix CephObjectStore name exceeding 64 char length
  pkg/controller/storagecluster/external_resources_test.go
  pkg/controller/storagecluster/generate.go
Labels: approved, lgtm, needs-ok-to-test

#734 StorageCluster: Update the storagecluster uninstall annotations
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, needs-ok-to-test

#716 Enable Monitoring for external mode
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/external_resources.go
  pkg/controller/storagecluster/storagecluster_controller.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#735 Fix shellcheck errors
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_namespaced_resources
Labels: approved, lgtm

#632 Add a check to verify RGW endpoint is reachable or not
  pkg/controller/storagecluster/external_resources.go
  pkg/controller/storagecluster/external_resources_test.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
Labels: approved, lgtm, ok-to-test
