Repository red-hat-storage/ocs-operator, pull requests merged in 2020-01, with the labels that each got.

#383 Remove kshlm from OWNERS
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#380 Added some additionalPrinterColumns for StorageCluster
  deploy/crds/ocs_v1_ocsinitialization_crd.yaml
  deploy/crds/ocs_v1_storagecluster_crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocsinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/storagecluster.crd.yaml
  go.mod
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/ocsinitialization_types.go
  pkg/apis/ocs/v1/storagecluster_types.go
Labels: approved, lgtm, size/M

#389 Added more detailed description and some missing details.
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test, size/L

#382 Align 'generate-latest-csv' script with existing env variables
  hack/generate-latest-csv.sh
Labels: approved, lgtm, ok-to-test, size/XS

#392 functest: enabling upgrade test
  functests/cluster_upgrade_test.go
Labels: approved, lgtm, size/XS

#397 Add egafford to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#396 functest: Always output must-gather info
  functests/must-gather_test.go
Labels: approved, lgtm, size/XS

#385 Annotating the internal CRDs
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test, size/XS

#399 Bug 1788545 - Add new variable continueUpgradeAfterChecksEvenIfNotHealthy to Rook-Ceph deployment
  deploy/olm-catalog/ocs-operator/4.3.0/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/reconcile.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/priorityclasses.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/register.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1alpha2/priorityclasses.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1alpha2/storage.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1alpha2/types.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1alpha2/zz_generated.deepcopy.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#400 fix: tear down failure in CI
  functests/setup_teardown.go
  go.mod
  go.sum
  pkg/deploy-manager/common.go
  pkg/deploy-manager/config.go
  pkg/deploy-manager/storagecluster.go
Labels: approved, lgtm, size/L

#370 ci: Use ubi8 base for test images
  openshift-ci/Dockerfile.deploy
Labels: approved, lgtm, size/XS
