Repository red-hat-storage/ocs-operator, pull requests merged in 2020-05, with the labels that each got.

#475 Annotation feature gate for Console
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#489 Fixing a comment
  pkg/controller/storagecluster/platform_detection.go
Labels: approved, lgtm

#497 Changes in the Ceph Cluster CR for external cluster
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#479 Adding 'Ready' phase for External StorageCluster Mode
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/util/status.go
Labels: approved, lgtm, ok-to-test

#492 Add new platform GCP and AZURE
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/platform_detection.go
Labels: approved, lgtm

#496 removes CSV check from CI test target
  Makefile
Labels: approved, lgtm

#504 updates build-tools to install go1.13.3
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#506 adds gcc to build tools
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#495 Add get subscription command in must-gather
  must-gather/collection-scripts/gather
Labels: approved, lgtm

#493 Use _ (underscore) instead of space char in oc command output filenames
  must-gather/collection-scripts/gather
Labels: approved, lgtm, ok-to-test

#498 Create ocs-on-a-disconnected-environment.md
  docs/ocs-on-a-disconnected-environment.md
Labels: approved, lgtm, needs-ok-to-test

#499 Add annotation to activate UI validation over external cluster metadata
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#501 BUG 1834327 Add ROOK_CSI_ALLOW_UNSUPPORTED_VERSION to rook operator env
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#515 Always reconcile operator SCCs
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
Labels: approved, lgtm

#517 Revert owning OB and OBC CRDs
  deploy/olm-catalog/ocs-operator/4.5.0/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#518 Bug 1823937: [release-4.4] Revert owning OB and OBC CRDs
  deploy/olm-catalog/ocs-operator/4.4.0/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#491 If Docker is not found, use podman to build the containers.
  hack/common.sh
Labels: approved, lgtm, ok-to-test

#505 Adding OBC StorageClass in converged mode
  deploy/olm-catalog/ocs-operator/manifests/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephclient.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  pkg/controller/defaults/placements.go
  pkg/controller/storagecluster/generate.go
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/platform_detection.go
Labels: approved, lgtm, ok-to-test

#500 Ceph: Create resources automatically for external Cluster
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephclient.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.openapi.go
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#524 Fix outdated CSV files
  deploy/olm-catalog/ocs-operator/manifests/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephclient.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
Labels: approved

#528 [hotfix CI] pass the pvc name as expected by rook to StorageCluster
  pkg/deploy-manager/storagecluster.go
Labels: approved, lgtm

#519 Update validation annotation used by the UI
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#508 Customizable labels for OCS deployment
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
  pkg/controller/storagecluster/placement.go
  pkg/controller/storagecluster/placement_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  test/crd_validation_test.go
Labels: approved, lgtm, ok-to-test

#510 Avoid running osd being marked out
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#531 Bug 1833317: Added script to avoid healthy osd from marking out
  pkg/controller/storagecluster/reconcile.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#529 Update Rook version from 1.3.2 to 1.3.4
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  vendor/github.com/rook/rook/pkg/apis/edgefs.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/edgefs.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#530 Update CSV to add credentials export script
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#494 adds OCP must-gather to tests
  functests/setup_teardown.go
  hack/dump-debug-info.sh
  hack/functest.sh
Labels: approved, lgtm

#509 Adds Structural schema to OCS CRDs
  Makefile
  deploy/crds/ocs.openshift.io_ocsinitializations_crd.yaml
  deploy/crds/ocs.openshift.io_storageclusterinitializations_crd.yaml
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  hack/latest-csv-checksum.md5
  tools/tools.go
  vendor/github.com/openshift/build-machinery-go/LICENSE
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/doc.go
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/default.mk
  vendor/github.com/openshift/build-machinery-go/make/doc.go
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/doc.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/tmp.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/operator.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/help.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/github.com/openshift/build-machinery-go/scripts/doc.go
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/github.com/openshift/build-machinery-go/scripts/update-deps.sh
  vendor/modules.txt
Labels: approved, lgtm
