Repository red-hat-storage/ocs-operator, pull requests merged in 2020-04, with the labels that each got.

#470 Cleaning up the CSV based on recent changes
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#473 dockerfile: removes hardcoded image registry link
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm

#472 Disable automatic mon resizing.
  go.sum
  pkg/controller/defaults/defaults.go
Labels: approved, lgtm

#429 Independent mode initialization and cluster status
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/util/status.go
Labels: approved, lgtm, size/L

#476 Hide Ceph Client api
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#480 Removed hardcoded portable=true
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, ok-to-test

#483 Bug 1816820: Removed hardcoded portable=true
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm, ok-to-test

#481 A job template to remove failed disk
  cmd/manager/main.go
  deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  vendor/github.com/onsi/ginkgo/.travis.yml
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/ginkgo/internal/remote/syscall_dup_linux_riscv64.go
  vendor/github.com/onsi/ginkgo/internal/remote/syscall_dup_unix.go
  vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
  vendor/github.com/onsi/ginkgo/reporters/teamcity_reporter.go
  vendor/github.com/onsi/ginkgo/types/types.go
  vendor/github.com/onsi/gomega/.travis.yml
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/assertion/assertion.go
  vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/consist_of.go
  vendor/github.com/onsi/gomega/matchers/contain_elements_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_error_matcher.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraph.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraphmatching.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/edge/edge.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/node/node.go
  vendor/github.com/openshift/api/pkg/serialization/serialization.go
  vendor/github.com/openshift/api/template/v1/codec.go
  vendor/github.com/openshift/api/template/v1/consts.go
  vendor/github.com/openshift/api/template/v1/doc.go
  vendor/github.com/openshift/api/template/v1/generated.pb.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/api/template/v1/legacy.go
  vendor/github.com/openshift/api/template/v1/register.go
  vendor/github.com/openshift/api/template/v1/types.go
  vendor/github.com/openshift/api/template/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/template/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
Labels: approved, lgtm

#484 Bug 1821219: A job template to remove failed disk
  cmd/manager/main.go
  deploy/olm-catalog/ocs-operator/4.4.0/ocs-operator.v4.4.0.clusterserviceversion.yaml
  deploy/role.yaml
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  vendor/github.com/onsi/ginkgo/.travis.yml
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/ginkgo/internal/remote/syscall_dup_linux_riscv64.go
  vendor/github.com/onsi/ginkgo/internal/remote/syscall_dup_unix.go
  vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
  vendor/github.com/onsi/ginkgo/reporters/teamcity_reporter.go
  vendor/github.com/onsi/ginkgo/types/types.go
  vendor/github.com/onsi/gomega/.travis.yml
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/assertion/assertion.go
  vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/consist_of.go
  vendor/github.com/onsi/gomega/matchers/contain_elements_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_error_matcher.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraph.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraphmatching.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/edge/edge.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/node/node.go
  vendor/github.com/openshift/api/pkg/serialization/serialization.go
  vendor/github.com/openshift/api/template/v1/codec.go
  vendor/github.com/openshift/api/template/v1/consts.go
  vendor/github.com/openshift/api/template/v1/doc.go
  vendor/github.com/openshift/api/template/v1/generated.pb.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/api/template/v1/legacy.go
  vendor/github.com/openshift/api/template/v1/register.go
  vendor/github.com/openshift/api/template/v1/types.go
  vendor/github.com/openshift/api/template/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/template/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#485 Changed job name and added --force flag
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm
