Repository red-hat-storage/ocs-operator, pull requests merged in 2020-10, with the labels that each got.

#789 Remove StorageClusterInitialization
  deploy/crds/ocs.openshift.io_storageclusterinitializations_crd.yaml
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/crds/ocs_v1_storageclusterinitialization_cr.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusterinitializations_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs_v1_storageclusterinitialization_cr.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storageclusterinitialization.crd.yaml
  functests/storageclusterinitialization_test.go
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/storageclusterinitialization_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/storagecluster/cephblockpools.go
  pkg/controller/storagecluster/cephblockpools_test.go
  pkg/controller/storagecluster/cephfilesystem.go
  pkg/controller/storagecluster/cephfilesystem_test.go
  pkg/controller/storagecluster/cephobjectstores.go
  pkg/controller/storagecluster/cephobjectstores_test.go
  pkg/controller/storagecluster/cephobjectstoreusers.go
  pkg/controller/storagecluster/cephobjectstoreusers_test.go
  pkg/controller/storagecluster/external_resources.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storageclasses.go
  pkg/controller/storagecluster/storageclasses_test.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/storageclusterinit.go
  pkg/controller/storagecluster/volumesnapshotterclasses.go
  pkg/controller/storagecluster/volumesnapshotterclasses_test.go
  test/crd_validation_test.go
Labels: approved, lgtm

#806 Bug 1883767: Using placement strategies in cluster-service.yaml causes ocs-operator to crash
  pkg/controller/storagecluster/placement.go
  pkg/controller/storagecluster/placement_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#808 Bug 1885585: Update noobaa and dependencies
  go.mod
  go.sum
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, ok-to-test

#809 must-gather: make Dockerfile compatible with docker and buildah
  must-gather/Dockerfile
Labels: approved, lgtm

#740 Added the framework for the OCS rules and alerts
  .gitignore
  Makefile
  hack/gen-promethues-rules.sh
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/Makefile
  metrics/mixin/README.md
  metrics/mixin/alerts/alerts-external.libsonnet
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/alerts/services-external.libsonnet
  metrics/mixin/alerts/services.libsonnet
  metrics/mixin/build/external.jsonnet
  metrics/mixin/build/internal.jsonnet
  metrics/mixin/build/jsonnet/kube-prometheus-external.libsonnet
  metrics/mixin/build/jsonnet/kube-prometheus.libsonnet
  metrics/mixin/build/jsonnet/prometheus.libsonnet
  metrics/mixin/build/jsonnetfile.json
  metrics/mixin/build/jsonnetfile.lock.json
  metrics/mixin/config.libsonnet
  metrics/mixin/lib/alerts-external.jsonnet
  metrics/mixin/lib/alerts.jsonnet
  metrics/mixin/lib/rules.jsonnet
  metrics/mixin/mixin-external.libsonnet
  metrics/mixin/mixin.libsonnet
  metrics/mixin/rules/rules.libsonnet
Labels: approved, lgtm

#811 Set storagecluster.status.failuredomain
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, ok-to-test

#799 [release-4.6] e2e: Update from master
  Makefile
  functests/common.go
  functests/data_validation_test.go
  functests/pvc_creation_test.go
  functests/setup_teardown.go
  hack/common.sh
  hack/functest.sh
  pkg/deploy-manager/common.go
  pkg/deploy-manager/config.go
  pkg/deploy-manager/subscription.go
Labels: approved, bugzilla/valid-bug, lgtm

#803 storagecluster: Fix order of func calls in deleteResources
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm, ok-to-test

#815 Allow the rook-ceph-tools pod to run on OCS tainted nodes.
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
Labels: approved, lgtm, ok-to-test

#805 must-gather: add noobaa cli to must-gather
  must-gather/collection-scripts/gather_noobaa_resources
  must-gather/templates/noobaa.template
Labels: approved, lgtm

#812 Add commands to gather_clusterscoped_resources.
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_namespaced_resources
Labels: approved, lgtm

#773 Introduce flexible scaling
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/topology.go
  pkg/controller/storagecluster/topology_test.go
Labels: approved, lgtm, ok-to-test

#822 Add missing CSV changes for removing StorageClusterInitialization
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
Labels: approved, lgtm

#816 must-gather: skip ceph collection in external mode OCS
  must-gather/collection-scripts/gather
Labels: approved, lgtm

#818 must-gather: add more info for ceph crash
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#798 Added table driven tests on cephobjectstoreusers_test.go
  pkg/controller/storagecluster/cephobjectstoreusers_test.go
Labels: approved, lgtm

#833 [release-4.6] Bug 1873580: Remove StorageClusterInitialization
  deploy/crds/ocs.openshift.io_storageclusterinitializations_crd.yaml
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/crds/ocs_v1_storageclusterinitialization_cr.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusterinitializations_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs_v1_storageclusterinitialization_cr.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storageclusterinitialization.crd.yaml
  functests/storageclusterinitialization_test.go
  must-gather/collection-scripts/gather_noobaa_resources
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/storageclusterinitialization_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/storagecluster/cephblockpools.go
  pkg/controller/storagecluster/cephblockpools_test.go
  pkg/controller/storagecluster/cephfilesystem.go
  pkg/controller/storagecluster/cephfilesystem_test.go
  pkg/controller/storagecluster/cephobjectstores.go
  pkg/controller/storagecluster/cephobjectstores_test.go
  pkg/controller/storagecluster/cephobjectstoreusers.go
  pkg/controller/storagecluster/cephobjectstoreusers_test.go
  pkg/controller/storagecluster/external_resources.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storageclasses.go
  pkg/controller/storagecluster/storageclasses_test.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/storageclusterinit.go
  pkg/controller/storagecluster/volumesnapshotterclasses.go
  pkg/controller/storagecluster/volumesnapshotterclasses_test.go
  test/crd_validation_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#834 must-gather: Fix shellcheck errors in gather_noobaa_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm

#635 Add TargetSizeRatio of .49 to RGW data pool
  pkg/controller/storagecluster/cephobjectstores.go
Labels: approved, lgtm

#841 Allow NooBaa CR to not be reconciled
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#843 noobaa must-gather - Add important notifications collection
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm, ok-to-test

#850 fix ceph cluster delete ordering
  deploy/csv-templates/crds/cephclusters.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectstores.ceph.rook.io.crd.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/uninstall_reconciler.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm

#794 UnitTests: Add test TestDeleteStorageClasses
  pkg/controller/storagecluster/uninstall_reconciler_test.go
Labels: approved, lgtm, ok-to-test

#820 ceph: Add missing fields in osd purge job
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#797 Added table driven tests to cephobjectstores_test.go
  pkg/controller/storagecluster/cephobjectstores_test.go
Labels: approved, lgtm

#848 Bug 1888614: Changed the execution of connection closing, to avoid closing uncreated connection.
  pkg/controller/storagecluster/external_resources.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#819 Fix Unbalanced distribution of OSD pods by TSC for more than 3 AZs
  pkg/controller/defaults/placements.go
Labels: approved, lgtm, ok-to-test

#854 Enhance logging of deleteNoobaaSystems func
  pkg/controller/storagecluster/noobaa_system_reconciler.go
Labels: approved, lgtm, ok-to-test

#814 Resolve errors reconciling metrics-exporter
  pkg/controller/storagecluster/exporter.go
  pkg/controller/storagecluster/prometheus.go
Labels: approved, lgtm

#807 UnitTests: Add Uninstall tests
  pkg/controller/storagecluster/uninstall_reconciler_test.go
Labels: approved, lgtm, ok-to-test

#804 refactor: helper functions to generate placement structs
  pkg/controller/defaults/placements.go
Labels: approved, lgtm

#857 must-gather: Fix oc get command
  must-gather/collection-scripts/gather_clusterscoped_resources
Labels: approved, lgtm

#860 must-gather: add jq command to must-gather helper pod
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#861 must-gather: delete helper pod after collecting ceph crash info
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#855 Bug 1886873: fix ceph cluster delete ordering
  deploy/csv-templates/crds/cephclusters.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectstores.ceph.rook.io.crd.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/uninstall_reconciler.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#832 Enabling 'snapshotter' feature in external cluster mode
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, needs-ok-to-test

#847 must-gather: Fix noobaa script shellcheck errors
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm

#867 [release-4.6] Bug 1886308: Enabling 'snapshotter' feature in external cluster mode
  pkg/controller/storagecluster/reconcile.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, needs-ok-to-test

#856 Fix errors in managed resources reconciliation
  pkg/controller/storagecluster/cephobjectstoreusers.go
  pkg/controller/storagecluster/storageclasses.go
  pkg/controller/storagecluster/volumesnapshotterclasses.go
Labels: approved, lgtm

#842 Use resource infrastructure instead of Nodes
  cmd/manager/main.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/storagecluster/cephblockpools_test.go
  pkg/controller/storagecluster/cephfilesystem_test.go
  pkg/controller/storagecluster/cephobjectstores.go
  pkg/controller/storagecluster/cephobjectstores_test.go
  pkg/controller/storagecluster/cephobjectstoreusers.go
  pkg/controller/storagecluster/cephobjectstoreusers_test.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
  pkg/controller/storagecluster/platform_detection.go
  pkg/controller/storagecluster/storageclasses.go
  pkg/controller/storagecluster/storageclasses_test.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/uninstall_reconciler_test.go
  pkg/controller/storagecluster/volumesnapshotterclasses_test.go
Labels: approved, lgtm

#870 csv-merger: Add OCS Toleration to metrics-exporter
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#738 functests: Additional fixes and optimizations
  functests/common.go
  functests/config.go
  functests/must-gather/must_gather_test.go
  functests/must-gather_test.go
  functests/ocs/ceph_tools_test.go
  functests/ocs/cluster_upgrade_test.go
  functests/ocs/data_validation_test.go
  functests/ocs/ocs_test.go
  functests/ocs/pvc_creation_test.go
  functests/ocs/storagecluster_creation_test.go
  functests/setup_teardown.go
  hack/build-functest.sh
  hack/common.sh
  hack/functest.sh
  pkg/deploy-manager/config.go
Labels: approved, lgtm

#876 must-gather: some improvements in snapshot info collection
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm
