Repository red-hat-storage/ocs-operator, pull requests merged in 2020-12, with the labels that each got.

#859 Add new property in storagedeviceset
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#927 Added OCS CPU telemetry metric rules
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/build/jsonnetfile.lock.json
  metrics/mixin/rules/rules.libsonnet
Labels: approved, lgtm

#926 updates Dockerfile.registry for apiextensions/v1 support
  build/Dockerfile.registry
  nsswitch.conf
Labels: approved, lgtm

#912 Upgrade to Rook v1.5.1
  deploy/csv-templates/crds/cephblockpools.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephblockpools.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephclients.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephclients.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephclusters.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephclusters.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephfilesystems.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephfilesystems.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephnfses.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephnfses.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephobjectrealms.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectrealms.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephobjectstores.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectstores.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephobjectstoreusers.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectstoreusers.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephobjectzonegroups.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectzonegroups.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephobjectzones.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectzones.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/cephrbdmirrors.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephrbdmirrors.ceph.rook.io.crds.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephclient.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephfilesystem.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephnfs.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectrealm.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstoreuser.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectzone.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectzonegroup.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephrbdmirror.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocsinitialization.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  hack/common.sh
  pkg/deploy-manager/storagecluster.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#904 must-gather: collect OBC of all namespaces
  must-gather/collection-scripts/gather_namespaced_resources
Labels: approved, lgtm

#929 Updates dependency and NooBaa image
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/noobaa-crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/noobaa-csv.yaml
  deploy/olm-catalog/ocs-operator/manifests/backingstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/bucketclass.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/noobaa.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/objectbucket.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/objectbucketclaim.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  hack/common.sh
  tools/csv-merger/csv-merger.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/bindata.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/crd_kinds.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/register.go
  vendor/github.com/noobaa/noobaa-operator/v2/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorcondition_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lib/leader/leader.go
  vendor/modules.txt
Labels: approved, lgtm

#931 install ginkgo but don't edit the go.mod file
  hack/build-functest.sh
Labels: approved, lgtm

#933 must-gather: add ceph df detail cmd for ceph
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#935 Updated OCS telemeter rule name to match with OCP pattern
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/rules/rules.libsonnet
Labels: approved, lgtm

#936 updates openshift/api to enable Quickstart APIs for Console
  go.mod
  go.sum
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/template/v1/generated.pb.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/api/template/v1/types.go
  vendor/github.com/openshift/api/template/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#937 Adding minKubeVersion to CSV
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#932 functests: improvements to allow StorageCluster with different configurations
  functests/config.go
  functests/ocs/cluster_upgrade_test.go
  functests/ocs/storagecluster_creation_test.go
  functests/setup_teardown.go
  pkg/deploy-manager/config.go
  pkg/deploy-manager/storagecluster.go
Labels: approved, lgtm

#907 Add annotation in CSV to make StorageCluster the initialization resource
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#864 add new property TuneFastDeviceClass
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#908 Fix Usability Issues in UI by adding relevant annotations in the Operator
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  pkg/controller/storagecluster/storageclasses.go
  tools/csv-merger/csv-merger.go
Labels: approved, kind/bug, lgtm

#946 Refactor device tuning code
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#947 update crd changes for TuneFastDeviceClass
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
Labels: approved, lgtm

#944 cephcluster: tune devices according to the deviceType
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#945 storagecluster: remove the deviceType from validateStorageDeviceSets
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#938 cephcluster: add annotation for each deviceType in cephCR
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#885 Refactor status updates into a post reconcile phase and add component image reconcile status
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/cephcluster_test.go
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/topology.go
  pkg/controller/storagecluster/topology_test.go
Labels: approved, lgtm, ok-to-test

#958 Update csv
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
Labels: approved, lgtm

#909 Track platforms that support external mode from CSV
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#925 Storageclass and snapshotclass refactor
  pkg/controller/storagecluster/external_resources.go
  pkg/controller/storagecluster/storageclasses.go
  pkg/controller/storagecluster/storageclasses_test.go
  pkg/controller/storagecluster/uninstall_reconciler.go
  pkg/controller/storagecluster/uninstall_reconciler_test.go
  pkg/controller/storagecluster/volumesnapshotterclasses.go
Labels: approved, kind/cleanup, lgtm

#939 Adds support for OCS quickstarts
  cmd/manager/main.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/quickstart_constants.go
  pkg/controller/storagecluster/quickstarts.go
  pkg/controller/storagecluster/quickstarts_test.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/uninstall_reconciler.go
  pkg/controller/storagecluster/uninstall_reconciler_test.go
  vendor/github.com/openshift/api/console/v1/0000_10_consoleclidownload.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consoleexternalloglink.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consolelink.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consolenotification.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consolequickstart.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consoleyamlsample.crd.yaml
  vendor/github.com/openshift/api/console/v1/doc.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types.go
  vendor/github.com/openshift/api/console/v1/types_console_cli_download.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/types_console_link.go
  vendor/github.com/openshift/api/console/v1/types_console_notification.go
  vendor/github.com/openshift/api/console/v1/types_console_quick_start.go
  vendor/github.com/openshift/api/console/v1/types_console_yaml_sample.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#962 source ocs-operator CSV in OCP CI
  deploy/csv-templates/crds/noobaa/noobaa-crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_ocsinitializations_crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs/ocs_v1_ocsinitialization_cr.yaml
  deploy/csv-templates/crds/ocs/ocs_v1_storagecluster_cr.yaml
  deploy/csv-templates/crds/rook/cephblockpools.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephclients.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephclusters.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephfilesystems.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephnfses.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephobjectrealms.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephobjectstores.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephobjectstoreusers.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephobjectzonegroups.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephobjectzones.ceph.rook.io.crds.yaml
  deploy/csv-templates/crds/rook/cephrbdmirrors.ceph.rook.io.crds.yaml
  hack/generate-unified-csv.sh
  hack/source-manifests.sh
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#956 Add configurable number of CephObjectStore gateway instances
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/defaults/defaults.go
  pkg/controller/storagecluster/cephobjectstores.go
  pkg/controller/storagecluster/cephobjectstores_test.go
Labels: approved, lgtm

#964 update rook to include arbiter/stretch cluster changes
  deploy/csv-templates/crds/rook/cephclusters.ceph.rook.io.crds.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  hack/go-build.sh
  pkg/controller/defaults/defaults.go
  pkg/controller/storagecluster/cephcluster.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/keys.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/placement.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/labels.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/placement.go
  vendor/modules.txt
Labels: approved, lgtm

#940 Add Stretch configuration to the Storage Cluster
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  functests/config.go
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/defaults/defaults.go
  pkg/controller/storagecluster/cephblockpools.go
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/placement.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/topology.go
  pkg/deploy-manager/arbiter.go
  pkg/deploy-manager/config.go
  pkg/deploy-manager/storagecluster.go
  tools/cluster-deploy/cluster-deploy.go
Labels: approved, lgtm

#948 Contribution Guide
  CONTRIBUTING.md
  DCO
Labels: approved, lgtm

#970 Change typo in contribution guide
  CONTRIBUTING.md
Labels: approved, lgtm

#972 hack: fix OCS Operator image in source-manifests.sh
  hack/source-manifests.sh
Labels: approved, lgtm
