Repository red-hat-storage/ocs-operator, pull requests merged in 2020-02, with the labels that each got.

#395 hack: Cleanup and consolidate common variables
  Makefile
  deploy/olm-catalog/ocs-operator/ocs-operator.package.yaml
  hack/build-registry-bundle.sh
  hack/cluster-deploy.sh
  hack/common.sh
  hack/dump-debug-info.sh
  hack/ensure-operator-sdk.sh
  hack/functest.sh
  hack/gen-deployment-yaml.sh
  hack/generate-k8s-openapi.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/latest-csv-checksum.md5
  hack/operator-sdk-common.sh
  hack/shellcheck-test.sh
  hack/source-manifests.sh
  hack/verify-operator-sdk-gen.sh
  must-gather/functests/functests.sh
Labels: approved, lgtm, size/L

#402 functest: increases the timeout for cluster teardown
  pkg/deploy-manager/common.go
Labels: approved, lgtm, size/XS

#404 hack: Follow up of Cleanup and Consolidating of common variables
  Makefile
  hack/build-must-gather.sh
  hack/build-operator.sh
  hack/clean.sh
  hack/common.sh
Labels: approved, lgtm, size/M

#398 fix(ocs-operator): removes use of storageClassDeviceSet PVC for mons
  deploy/crds/ocs_v1_storagecluster_crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/storagecluster.crd.yaml
  go.sum
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, size/M

#406 Added Deleting Phase to the Storage Cluster
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/util/status.go
Labels: approved, lgtm, size/S

#381 Adding noobaa's core and db images to a new environment variables for the noobaa operator
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test, size/S

#412 Add output of oc commands in must-gather
  must-gather/collection-scripts/gather
Labels: approved, lgtm, size/S

#413 Bug 1775432- sets mon_osd_full_ratio=.85 & mon_osd_nearfull_ratio =.75
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/XS

#409 changes the sequence of Provided APIs
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  hack/latest-csv-checksum.md5
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, size/L

#415 Updates go modules
  go.mod
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#417 deps-update: updates rook to v1.2.4
  deploy/olm-catalog/ocs-operator/4.3.0/cephblockpool.crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/generate-latest-csv.sh
  hack/latest-csv-checksum.md5
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/annotations.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/blockpool.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/keys.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1alpha2/types.go
  vendor/github.com/rook/rook/pkg/daemon/ceph/model/pool.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L

#414 Bug 1797918 - Enables balancer module
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, ok-to-test, size/XS

#359 Adding version string into OCS storage cluster
  deploy/crds/ocs_v1_storagecluster_crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/reconcile.go
  version/version.go
Labels: approved, lgtm, ok-to-test, size/M

#405 BZ-1788492: Adding pod anti affinity for zones on mon and mds pods
  pkg/controller/defaults/placements.go
  pkg/controller/storagecluster/initialization_reconciler.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/M

#401 Bug 1795532 - throttle background ceph activity on gp2 devices
  deploy/crds/ocs_v1_storagecluster_crd.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/ocs-operator.v4.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ocs-operator/4.3.0/storagecluster.crd.yaml
  hack/latest-csv-checksum.md5
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, size/M

#410 Updates the reconcile logic to use storageDevicePVC for mons
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, size/M

#419 set mon_osd_backfillfull_ratio=.8
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, ok-to-test, size/XS

#408 Updates the must-gather Docker file to use origin-cli image
  must-gather/Dockerfile
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm, size/L

#425 Adds temporary fix for collection storagecluster
  must-gather/collection-scripts/gather
Labels: approved, lgtm, size/XS

#421 Change noobaa system reconcile to use "smart" desired state
  pkg/controller/storagecluster/noobaa_system_reconciler.go
  pkg/controller/storagecluster/noobaa_system_reconciler_test.go
Labels: approved, lgtm, ok-to-test, size/L
