Repository red-hat-storage/ocs-operator, pull requests merged in 2020-09, with the labels that each got.

#736 StorageCluster: propagate uninstall mode
  deploy/csv-templates/crds/cephclusters.ceph.rook.io.crd.yaml
  deploy/csv-templates/crds/cephobjectstores.ceph.rook.io.crd.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  pkg/controller/storagecluster/reconcile.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/annotations.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/keys.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/annotations.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#737 Deploy OCS prometheus alerts - substitute for PR #733
  build/Dockerfile.build
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/role.yaml
  hack/build-container.sh
  hack/common.sh
  pkg/controller/storagecluster/prometheus.go
  pkg/controller/storagecluster/reconcile.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/labels.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/labels.go
Labels: approved, lgtm

#670 must-gather: Add feature for collecting logs at particular time
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_namespaced_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm

#741 removed duplicated line
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#561 StorageCluster: make readability enhancement
  pkg/controller/storagecluster/placement.go
Labels: approved, lgtm

#745 StorageCluster: set default UninstallAnnotations
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, needs-ok-to-test

#746 Fixed cluster failure when Netwok is not specified.
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, ok-to-test

#748 Reconcile external resources
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/external_resources.go
  pkg/controller/storagecluster/external_resources_test.go
Labels: approved, lgtm, needs-ok-to-test

#752 Adding the CRDs missed while creating external reconcile PR
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
Labels: approved, lgtm, needs-ok-to-test

#707 Fix and refactor failing e2e tests
  Makefile
  functests/common.go
  functests/data_validation_test.go
  functests/pvc_creation_test.go
  functests/setup_teardown.go
  hack/cluster-clean.sh
  hack/common.sh
  hack/dump-debug-info.sh
  hack/functest.sh
  openshift-ci/Dockerfile.registry.build
  pkg/deploy-manager/common.go
  pkg/deploy-manager/config.go
  pkg/deploy-manager/subscription.go
Labels: approved, lgtm

#758 Fixed incorrect logr usage
  pkg/controller/storagecluster/exporter.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, ok-to-test

#770 Added temporary placeholder Prometheus alert rule yamls
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: approved, lgtm

#753 Enhance Uninstall logging and comments
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm, ok-to-test

#709 Design: OSD Topology Spread Constraints
  docs/design/osd-topology-spread-constraints.md
Labels: approved, lgtm

#761 Move the uninstall code from reconcile.go to uninstall_reconcile.go to organize it in better way.
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm, ok-to-test

#766 fixed cephTools update when spec is changed
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
Labels: approved, lgtm

#759 added case tables for storageCluster_controller unit tests
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
  pkg/controller/storagecluster/topology_test.go
Labels: approved, lgtm

#767 added case tables for ocsinitialization_controller_test.go
  pkg/controller/ocsinitialization/ocsinitialization_controller_test.go
Labels: approved, lgtm

#774 Update osd-topology-spread-constraints.md
  docs/design/osd-topology-spread-constraints.md
Labels: approved, lgtm

#754 Update CSV to enable Minimal Deployment and Encryption in UI
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#765 Add test TestSetRookUninstallandCleanupPolicy
  pkg/controller/storagecluster/uninstall_reconciler_test.go
Labels: approved, lgtm, ok-to-test

#763 Refactored cephblockpools_test.go to table-driven tests
  pkg/controller/storagecluster/cephblockpools_test.go
Labels: approved, lgtm

#764 Refactored cephfilesystem_test.go to table-driven tests
  pkg/controller/storagecluster/cephfilesystem_test.go
Labels: approved, lgtm

#760 fixed getPlacement() for custom placement configurations
  pkg/controller/storagecluster/placement.go
  pkg/controller/storagecluster/placement_test.go
Labels: approved, lgtm, ok-to-test

#727 Supporting OSD Topology Spread Constraints
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/apis/ocs/v1/zz_generated.deepcopy.go
  pkg/controller/defaults/defaults.go
  pkg/controller/defaults/placements.go
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/cephcluster_test.go
  pkg/controller/storagecluster/initialization_reconciler_test.go
  pkg/controller/storagecluster/placement.go
  pkg/controller/storagecluster/storagecluster_controller.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm, ok-to-test

#778 Bug 1881071:Made monitoring optional during external cluster initilization
  pkg/controller/storagecluster/cephcluster.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#648 Avoid bash script to purge osds in job template
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#791 StorageCluster: fix logging errors
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm

#787 Bug 1883253: Update CSV to enable Minimal Deployment and Encryption in UI
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#777 Bug 1865825: [release-4.6] External resource reconciliation
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/external_resources.go
  pkg/controller/storagecluster/external_resources_test.go
Labels: bugzilla/severity-high, bugzilla/valid-bug, ok-to-test

#739 restores YAML manifests for Prometheus rules
  build/Dockerfile
  build/Dockerfile.build
  hack/build-operator.sh
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  openshift-ci/Dockerfile.deploy
  pkg/controller/storagecluster/prometheus.go
  pkg/controller/storagecluster/reconcile.go
Labels: approved, lgtm

#795 storagecluster: Fix typo in logs
  pkg/controller/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm, needs-ok-to-test
