Repository red-hat-storage/ocs-operator, pull requests merged in 2021-02, with the labels that each got.

#1009 must-gather: collect timestamp and total time taken by the MG
  must-gather/collection-scripts/gather
Labels: approved, lgtm

#1003 Job: Removes the OSD IDs from the label
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1028 StorageCluster: fix logic to determine minimum nodes
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/topology.go
Labels: approved, lgtm

#1001 must-gather: noobaa-db pod collection on postgres label
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved, lgtm

#1018 Must-gather: skip the ceph collection
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#1032 Must-gather: update pre-install.sh script
  must-gather/collection-scripts/pre-install.sh
Labels: approved, lgtm

#1035 must-gather:log the total time taken by collection script
  must-gather/collection-scripts/gather
Labels: approved, lgtm

#1030 Bug 1913357: [release-4.7] Fail validation if arbiter and flexibleScaling both are enabled
  controllers/storagecluster/reconcile.go
  controllers/util/events.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1033 Must-gather: update uninstall script
  must-gather/collection-scripts/post-uninstall.sh
Labels: approved, lgtm

#966 Make cephcluster monitoring port, in external cluster mode, configurable
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/storagecluster_controller.go
Labels: approved, lgtm, ok-to-test

#1021 Bug 1909793: [release-4.6] update rook to 1.4.9
  deploy/csv-templates/noobaa-csv.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/annotations.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/labels.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/types.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1019 Bug 1909793: Backport: [Release 4.6] adds tunefastdeviceclass property
  deploy/crds/ocs.openshift.io_storageclusters_crd.yaml
  pkg/apis/ocs/v1/storagecluster_types.go
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/reconcile.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1041 Bug 1914203: [release-4.7] StorageCluster: fix logic to determine minimum nodes
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/topology.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1024 Adds checks for quickstart CRD
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/quickstarts.go
  controllers/storagecluster/quickstarts_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  go.sum
  main.go
Labels: approved, lgtm

#1047 ceph: raise mon_max_pg_per_osd from 300 to 600
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1059 Adds RBAC for CustomResourceDefinitions
  config/rbac/role.yaml
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  go.sum
Labels: approved, lgtm

#1027 StorageCluster: add test cases for insufficient zones and regions
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/topology_test.go
Labels: approved, lgtm

#1036 Schedule 2 RGW pods when arbiter is enabled
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/placement.go
Labels: approved, lgtm

#1060 storagecluster: Change event type from error to warning
  controllers/storagecluster/reconcile.go
  controllers/util/events.go
Labels: approved, lgtm

#1034 StorageCluster: generate cephReplicatedSpec to abstract out arbiter values
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/generate.go
Labels: approved, lgtm

#1067 Bug 1927885: reverted readiness logic to match behavior of 4.6
  controllers/storagecluster/readiness.go
  controllers/storagecluster/reconcile.go
  main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1070 StorageCluster: fix the logic for the minimum number of nodes
  controllers/storagecluster/cephcluster.go
Labels: approved, lgtm

#1031 Enable new topology labels from Kubernetes
  api/v1/storagecluster_types.go
  api/v1/topologymap.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/topology.go
  controllers/storagecluster/topology_test.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, lgtm

#1071 Bug 1927885: [release-4.7] reverted readiness logic to match behavior of 4.6
  controllers/storagecluster/readiness.go
  controllers/storagecluster/reconcile.go
  main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1074 Bug 1915807: [release-4.7] Enable new topology labels from Kubernetes
  api/v1/storagecluster_types.go
  api/v1/topologymap.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/topology.go
  controllers/storagecluster/topology_test.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1049 Must-gather: add no headers in skip ceph collection
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#1044 must-gather:do not create helper pod if storagecluster is deleted
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/post-uninstall.sh
  must-gather/collection-scripts/pre-install.sh
Labels: approved, lgtm

#1063 Create a route for Ceph RGW
  config/rbac/role.yaml
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/routes.go
  controllers/storagecluster/routes_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/uninstall_reconciler.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  main.go
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/legacy.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#1043 StorageCluster:Fixed placement config for rack failure domain and modified labelselector
  controllers/defaults/placements.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: approved, lgtm

#1023 added DBType=postgres to noobaa CR
  controllers/storagecluster/noobaa_system_reconciler.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: approved, lgtm, ok-to-test

#1080 Bug 1922113: [release-4.7] - added DBType=postgres to noobaa CR
  controllers/storagecluster/noobaa_system_reconciler.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#1056 storagecluster: Fix noobaa uninstall logs
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: approved, lgtm

#1048 Must-gather: add bg process for ceph cmds
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#1072 Allow metrics to be disabled
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, lgtm

#1058 storagecluster: Update uninstall error as an events
  controllers/storagecluster/reconcile.go
  controllers/util/events.go
Labels: approved, lgtm

#1057 Bug 1915737: [release-4.7] storagecluster: Fix noobaa uninstall logs
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1055 Add a master branch configuration for openshift-ci
  Makefile
  hack/build-master-appregistry.sh
  hack/generate-master-appregistry.sh
  openshift-ci/Dockerfile.registry.build.master
  openshift-ci/Dockerfile.registry.master
Labels: approved, lgtm

#1085 Bug 1909793: Fix fasttune check for Azure storageclass
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1083 Bug 1927338: [release-4.7] storagecluster: Update uninstall error as an events
  controllers/storagecluster/reconcile.go
  controllers/util/events.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1016 Use Golang 1.15 for security fixes to Golang std library
  functests/must-gather/must_gather_test.go
  functests/ocs/ceph_tools_test.go
  functests/ocs/cluster_upgrade_test.go
  functests/ocs/data_validation_test.go
  functests/ocs/ocs_test.go
  functests/ocs/pvc_creation_test.go
  functests/ocs/storagecluster_creation_test.go
  go.mod
  hack/build-functest.sh
  vendor/modules.txt
Labels: approved, lgtm

#1086 Bug 1906016: [release-4.7] Use Golang 1.15 for security fixes to Golang std library
  functests/must-gather/must_gather_test.go
  functests/ocs/ceph_tools_test.go
  functests/ocs/cluster_upgrade_test.go
  functests/ocs/data_validation_test.go
  functests/ocs/ocs_test.go
  functests/ocs/pvc_creation_test.go
  functests/ocs/storagecluster_creation_test.go
  go.mod
  hack/build-functest.sh
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1084 Bug 1915730: [release-4.7] Create a route for Ceph RGW
  config/rbac/role.yaml
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/routes.go
  controllers/storagecluster/routes_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/uninstall_reconciler.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  main.go
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/legacy.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1053 Localizing build process.
  hack/source-manifests.sh
Labels: approved, lgtm

#1042 Define reconcile strategy for rook-config-override
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, lgtm

#1091 Bug 1928471: [release-4.7] Define reconcile strategy for rook-config-override
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1089 Fix camelCase for product title in quickstart
  controllers/storagecluster/quickstart_constants.go
Labels: approved, lgtm

#1096 Fix "OpenShift(R)" usage in Quickstarts
  controllers/storagecluster/quickstart_constants.go
Labels: approved, lgtm

#1092 Fix the OSD placement logic when arbiter is enabled
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#1078 Bug 1788492: use stricter podAntiAffinity rules for mons in non-stretched cluster
  controllers/defaults/placements.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/placement_test.go
  controllers/storagecluster/storagecluster_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1095 Update rook version to get OSD placement fixes
  deploy/bundle/manifests/cephobjectstore.crd.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/crds/rook/cephobjectstores.ceph.rook.io.crds.yaml
  deploy/csv-templates/rook-csv.yaml.in
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/placement.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/placement.go
  vendor/modules.txt
Labels: approved, lgtm
