Repository red-hat-storage/ocs-operator, pull requests merged in 2021-09, with the labels that each got.

#1324 Fix server listen flake forever
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
  controllers/storagecluster/storagecluster_controller_test.go
Labels: lgtm, approved

#1321 Remove Dockerfile.deploy unused by CI
  openshift-ci/Dockerfile.deploy
Labels: lgtm, approved

#1325 hack: remove custom vars for openshift ci
  hack/common.sh
  hack/generate-latest-csv.sh
Labels: lgtm, approved

#1326 Fix StorageCluster reconcile failure when peerSecretNames is empty or invalid
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephblockpools_test.go
Labels: lgtm, approved

#1332 Fix VolumeSnapshotClass creation for Ceph RBD
  controllers/storagecluster/volumesnapshotterclasses.go
Labels: lgtm, approved, ok-to-test

#1330 ocs: remove utils/ready.go
  controllers/util/ready.go
Labels: lgtm, approved

#1335 storagecluster: move topology map reconciliation into its own resourceManager
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/topology.go
Labels: lgtm, approved

#1327 must-gather: wait for PIDs to be avaliable
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved

#1339 Bug 2000865: [release-4.9] revert: creation of thick provisioned storage class in 4.9
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1341 noobaa: don't set NodeAffinity for standalone
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved

#1333 must-gather: collect noobaa db pod info
  must-gather/collection-scripts/gather_namespaced_resources
  must-gather/collection-scripts/gather_noobaa_resources
Labels: lgtm, approved, ok-to-test

#1328 must-gather: collect some of the odf-operator and storagesystem relat…
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved, ok-to-test

#1350 add check for PodAntiAffinity not nil
  controllers/storagecluster/placement.go
  controllers/storagecluster/placement_test.go
Labels: lgtm, approved, ok-to-test

#1353 Inject default label to noobaa_system_reconciler
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved, ok-to-test
