Repository red-hat-storage/ocs-operator, pull requests merged in 2021-07, with the labels that each got.

#1249 MUST-GATHER: LOGS OF BG PROCESS IN PRE-INSTALL SCRIPT
  must-gather/collection-scripts/pre-install.sh
Labels: approved, lgtm, ok-to-test

#1252 hack/source-manifests: Update noobaa cmd
  hack/source-manifests.sh
Labels: approved, lgtm

#1254 Bug 1978578: [release-4.6] fixed cephTools update when spec is changed
  pkg/controller/ocsinitialization/ocsinitialization_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1255 must-gather: remove the standard pod template
  must-gather/collection-scripts/pre-install.sh
  must-gather/templates/pod.template
  must-gather/templates/pod.template.standard
Labels: approved, lgtm

#1248 Refactored log statements for OCSInitialization and PersistentVolume controllers
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/ocsinitialization/sccs.go
  controllers/persistentvolume/reconcile.go
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#1258 must-gather: change file permission for gather_common_ceph_resources.…
  must-gather/collection-scripts/gather_common_ceph_resources
Labels: approved, lgtm

#1257 Bug 1979263: [release-4.8] revert: creation of thick provisioned storage class in 4.8
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1259 [release-4.8]Bug 1979012: Disable thick provisioning support from UI
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1236 must-gather: update OWNERS file
  must-gather/OWNERS
Labels: approved, lgtm

#1265 ceph: add retry to acquire flock
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1262 ocs: update dependencies for rook image version
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  go.mod
  go.sum
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/object.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#1246 Update OCS operator version at build time
  hack/common.sh
  hack/go-build.sh
Labels: approved, lgtm

#1176 pass monitoring labels to CephCluster
  controllers/storagecluster/cephcluster.go
Labels: approved, lgtm

#1272 ceph: disable many objects warning
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1269 Bug 1979155: [release-4.7] must-gather: remove the standard pod template
  must-gather/collection-scripts/pre-install.sh
  must-gather/templates/pod.template
  must-gather/templates/pod.template.standard
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1270 must-gather: call gather_common_ceph_resources with proper args
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#1271 Ceph toolbox will run as non-root user
  controllers/ocsinitialization/ocsinitialization_controller.go
Labels: approved, lgtm

#1193 Change rookv1.NetworkSpec to cephv1.NetworkSpec and pass full networkspec if it is specified.
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  go.mod
  go.sum
  vendor/gotest.tools/v3/LICENSE
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/assert/cmp/result.go
  vendor/gotest.tools/v3/assert/result.go
  vendor/gotest.tools/v3/internal/difflib/LICENSE
  vendor/gotest.tools/v3/internal/difflib/difflib.go
  vendor/gotest.tools/v3/internal/format/diff.go
  vendor/gotest.tools/v3/internal/format/format.go
  vendor/gotest.tools/v3/internal/source/defers.go
  vendor/gotest.tools/v3/internal/source/source.go
  vendor/modules.txt
Labels: approved, lgtm

#1279 Bug 1979514: [release-4.6] must-gather: remove the standard pod template
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/templates/pod.template
  must-gather/templates/pod.template.standard
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1276 controller: inject default label to CephCluster
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: approved, lgtm

#1283 ocs: replace avoid with skip where possible
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/cephobjectstores_test.go
  controllers/storagecluster/cephobjectstoreusers.go
  controllers/storagecluster/cephobjectstoreusers_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/platform_detection.go
  controllers/storagecluster/routes.go
  controllers/storagecluster/routes_test.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
Labels: approved, lgtm

#1239 Remove quickstarts from OCS
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/quickstart_constants.go
  controllers/storagecluster/quickstarts.go
  controllers/storagecluster/quickstarts_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/uninstall_reconciler.go
  controllers/storagecluster/uninstall_reconciler_test.go
  main.go
Labels: approved, lgtm
