Repository red-hat-storage/ocs-operator, pull requests merged in 2021-08, with the labels that each got.

#1290 add recording rules for cephcluster latency metrics
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/rules/rules.libsonnet
Labels: approved, lgtm

#1275 StorageCluster spec and controller changes to enable CephBlockPool mirroring
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, lgtm

#1253 Pool mirroring metrics
  deploy/bundle/manifests/exporter-role.yaml
  metrics/internal/collectors/ceph-block-pool.go
  metrics/internal/collectors/ceph-block-pool_test.go
  metrics/internal/collectors/ceph-object-store.go
  metrics/internal/collectors/ceph-object-store_test.go
  metrics/internal/collectors/ceph-rbd-mirror.go
  metrics/internal/collectors/ceph-rbd-mirror_test.go
  metrics/internal/collectors/registry.go
  metrics/internal/collectors/testUtil.go
  rbac/exporter-role.yaml
Labels: approved, lgtm

#1295 Fix ocs performance latency recording rules
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/rules/rules.libsonnet
Labels: lgtm, approved

#1298 Allow DBStorageClass to be set from Storage Cluster CR for Noobaa
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: lgtm, approved, ok-to-test

#1280 Clean up before running must-gather
  must-gather/collection-scripts/pre-install.sh
Labels: lgtm, approved

#1264 Bug 1977329: [release-4.8] Allow DBStorageClass to be set from Storage Cluster CR for Noobaa
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, bugzilla/severity-high

#1296 must-gather: collect logs for RegionalDR
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved, ok-to-test

#1287 OCS: Upgrade rbac manifests to use api v1
  deploy/bundle/manifests/exporter-role.yaml
  deploy/bundle/manifests/exporter-role_binding.yaml
  deploy/bundle/manifests/exporter-service-role.yaml
  deploy/bundle/manifests/exporter-service-role_binding.yaml
  deploy/bundle/manifests/noobaa-metrics-role.yaml
  deploy/bundle/manifests/noobaa-metrics-role_binding.yaml
  deploy/bundle/manifests/rook-metrics-role.yaml
  deploy/bundle/manifests/rook-metrics-role_binding.yaml
  deploy/bundle/manifests/rook-monitor-role.yaml
  deploy/bundle/manifests/rook-monitor-role_binding.yaml
  rbac/exporter-role.yaml
  rbac/exporter-role_binding.yaml
  rbac/exporter-service-role.yaml
  rbac/exporter-service-role_binding.yaml
  rbac/noobaa-metrics-role.yaml
  rbac/noobaa-metrics-role_binding.yaml
  rbac/rook-metrics-role.yaml
  rbac/rook-metrics-role_binding.yaml
  rbac/rook-monitor-role.yaml
  rbac/rook-monitor-role_binding.yaml
Labels: lgtm, approved

#1306 Fixed usage of global mock variables in unit-tests
  CONTRIBUTING.md
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
  controllers/storagecluster/placement_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/topology_test.go
Labels: approved

#1310 Use .ci-operator.yaml file for OpenShift CI builds
  .ci-operator.yaml
Labels: lgtm, approved

#1315 openshift-ci: add Dockerfile for index w/noobaa bundle
  openshift-ci/build-operator-index-ci.sh
  openshift-ci/database/index.db
  openshift-ci/index.Dockerfile
Labels: lgtm, approved

#1311 add ClusterResourceQuota prometheus alert for overprovisioning
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/alerts-external.libsonnet
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/alerts/cluster-resource-quota.libsonnet
  metrics/mixin/config.libsonnet
Labels: lgtm, approved, mvp, priority/1-high

#1316 storagecluster: refactor error handling in cephconfig.go
  controllers/storagecluster/cephconfig.go
Labels: lgtm, needs-ok-to-test, approved

#1312 add OBC quota prometheus alerts
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/alerts-external.libsonnet
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/alerts/obc.libsonnet
  metrics/mixin/config.libsonnet
Labels: lgtm, approved, mvp, priority/1-high

#1224 block creation of StorageClass until prerequisites are met
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/bundle/manifests/cephcluster.crd.yaml
  deploy/bundle/manifests/cephobjectstore.crd.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectstores.yaml
  deploy/csv-templates/rook-csv.yaml.in
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner/api/provisioner.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/placement.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/modules.txt
Labels: lgtm, approved, mvp, priority/2-medium

#1305 Remove NooBaa CSV
  deploy/bundle/manifests/backingstore.crd.yaml
  deploy/bundle/manifests/bucketclass.crd.yaml
  deploy/bundle/manifests/namespacestore.crd.yaml
  deploy/bundle/manifests/noobaa-metrics-role.yaml
  deploy/bundle/manifests/noobaa-metrics-role_binding.yaml
  deploy/bundle/manifests/noobaa.crd.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  docs/catalog-generation.md
  hack/build-operator-index.sh
  hack/common.sh
  hack/generate-master-csv.sh
  hack/generate-unified-csv.sh
  hack/verify-latest-csv.sh
  rbac/noobaa-metrics-role.yaml
  rbac/noobaa-metrics-role_binding.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1318 Update csv annotation with mcg-standalone feature
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1286 Fix external resources updation when json input change
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved, ok-to-test, mvp, priority/1-high

#1320 Support standalone NooBaa
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/uninstall_reconciler.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: lgtm, approved

#1322 hack: change ocs-must-gather image in openshift CI
  hack/common.sh
Labels: lgtm, approved

#1323 Add BlaineEXE to OWNERS
  OWNERS
Labels: lgtm, approved
