Repository red-hat-storage/ocs-operator, pull requests merged in 2021-10, with the labels that each got.

#1354 Bug 2005970: [release-4.8] add check for PodAntiAffinity not nil
  controllers/storagecluster/placement.go
  controllers/storagecluster/placement_test.go
  functests/common.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1357 [release-4.9]Bug 2000860: Remove thick-provisioner from UI supported features annotation list
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1356 Reduce the mon_data_avail_warn to 15%
  controllers/storagecluster/cephconfig.go
Labels: lgtm, approved, ok-to-test

#1365 build: support AWS/Graviton (aarch64)
  hack/ensure-operator-sdk.sh
  hack/ensure-opm.sh
  hack/operator-sdk-common.sh
Labels: lgtm, approved, ok-to-test

#1379 must-gather: remove invalid ceph commands
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved

#1381 cleanup: failure getting the subvolumegroup
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved

#1360 BUG 1938647: use SecurityContextConstraints API from Ceph-CSI
  controllers/ocsinitialization/sccs.go
  go.mod
  go.sum
  vendor/github.com/ceph/ceph-csi/api/LICENSE
  vendor/github.com/ceph/ceph-csi/api/deploy/ocp/doc.go
  vendor/github.com/ceph/ceph-csi/api/deploy/ocp/scc.go
  vendor/github.com/ceph/ceph-csi/api/deploy/ocp/scc.yaml
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1387 Refactor code to rename variables to refer to catalog image
  functests/config.go
  functests/ocs/cluster_upgrade_test.go
  functests/setup_teardown.go
  hack/cluster-deploy.sh
  hack/functest.sh
  hack/gen-deployment-yaml.sh
  pkg/deploy-manager/subscription.go
  tools/cluster-deploy/cluster-deploy.go
Labels: lgtm, approved
