Repository red-hat-storage/ocs-operator, pull requests merged in 2021-03, with the labels that each got.

#1102 Bug 1931590: [release 4.7] Update rook version to get OSD placement fixes
  deploy/bundle/manifests/cephobjectstore.crd.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/crds/rook/cephobjectstores.ceph.rook.io.crds.yaml
  deploy/csv-templates/rook-csv.yaml.in
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/placement.go
  vendor/github.com/rook/rook/pkg/apis/rook.io/v1/placement.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1087 Delete kms resources while uninstalling StorageCluster
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/kms_resources.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/uninstall_reconciler.go
Labels: approved, lgtm, ok-to-test

#1105 Bug 1925249: [release-4.7] Delete kms resources while uninstalling StorageCluster
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/kms_resources.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/uninstall_reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#1099 unmanage labels for exporter ServiceMonitor
  controllers/storagecluster/exporter.go
Labels: approved, lgtm

#1107 Must-Gather: Fix duplicate collection of objectbucketclaims
  must-gather/collection-scripts/gather_namespaced_resources
Labels: approved, lgtm

#1100 Must-gather: add top level directory structure png
  must-gather/docs/Directory-Structure-Top-Level.png
Labels: approved, lgtm

#1112 hack/source-manifests: Do not use quotes
  hack/source-manifests.sh
Labels: approved, lgtm

#1109 Must-gather: refactor the crash and volume collection
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#1098 rename metrics-exporter spec to monitoring
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1088 Disable CephObjectStore when the cloud provider is IBMCloud
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/platform_detection.go
  controllers/storagecluster/storageclasses_test.go
Labels: approved, lgtm, ok-to-test

#1110 must gather: small patch to fix the error message
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#1104 Enabled block pool tab under ocs operator
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#1117 must-gather: Readme update with how to contribute
  must-gather/README.md
Labels: approved, lgtm

#1120 Bug 1926182: [release-4.7] Support disabling reconciliation of monitoring related resources using a dedicated reconcile strategy flag
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1108 Bug 1936405: unmanage labels for exporter ServiceMonitor
  pkg/controller/storagecluster/exporter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1113 Increase mon failover timeout to 15 min for IBMCloudPlatformType
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: approved, lgtm, ok-to-test

#1122 Bug 1922421:[release-4.7] Increase mon failover timeout to 15 min for IBMCloudPlatformType
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, needs-ok-to-test

#1118 Set failure domain to host if flexibleScaling is enabled
  controllers/storagecluster/topology.go
Labels: approved, lgtm

#1125 Bug 1937837: [release-4.6] Increase mon failover timeout to 15 min for IBMCloudPlatformType
  deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml
  deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
  pkg/controller/storagecluster/cephcluster.go
  pkg/controller/storagecluster/cephcluster_test.go
  pkg/controller/storagecluster/platform_detection.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#953 Refactor Platform_detection.go
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/cephobjectstores_test.go
  controllers/storagecluster/cephobjectstoreusers.go
  controllers/storagecluster/cephobjectstoreusers_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/platform_detection.go
  controllers/storagecluster/routes.go
  controllers/storagecluster/routes_test.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
Labels: approved, lgtm, ok-to-test

#1054 OCS-Operator now supports multiple external monitoring IPs
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/external_resources.go
Labels: approved, lgtm, ok-to-test

#1131 Bug 1942354: [release-4.6] hack/source-manifests: Do not use quotes
  hack/source-manifests.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1119 Generate ci-operator bundle for master branches of all projects
  hack/generate-master-appregistry.sh
  hack/generate-master-bundle.sh
  hack/generate-master-csv.sh
  openshift-ci/Dockerfile.bundle.master
Labels: approved, lgtm

#1127 Delete csi kms resource
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/kms_resources.go
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: approved, lgtm, ok-to-test

#1133 Enable Noobaa KMS configuration only when the cluster-wide encryption is enabled
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
Labels: approved, lgtm, ok-to-test

#1132 must-gather: skip noobaa collection when storagecluster is not present
  must-gather/collection-scripts/gather
Labels: approved, lgtm

#1137 Update CSV to enable Multus in UI
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test

#1128 add ManagedResources spec for Ceph dashboard
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
Labels: approved, lgtm

#1134 storagecluster: Change the phase when spec is not valid
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1140 Create RBD StorageClass with thick provisioning
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, lgtm

#1129 Inject labels to all the monitoring resources created by OCS
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/exporter.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/prometheus.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller_test.go
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm
