Repository red-hat-storage/ocs-operator, pull requests merged in 2021-06, with the labels that each got.

#1158 Storagecluster: generate mgr spec in a function
  controllers/defaults/resources.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: approved, lgtm

#1197 Disable UI support for tainting user selected nodes dedicated
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#1153 Refactor: Move job template code to another file and add unit tests
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/job_templates.go
  controllers/storagecluster/job_templates_test.go
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm, ok-to-test

#1201 must-gather: helper pod fails to run on tainted nodes
  must-gather/templates/pod.template.latest
  must-gather/templates/pod.template.standard
Labels: approved, lgtm

#1198 Re-Change job template name to its original one,
  controllers/storagecluster/job_templates.go
Labels: approved, lgtm, ok-to-test

#1202 must-gather: no ceph collection even when sc is present
  must-gather/collection-scripts/gather
Labels: approved, lgtm

#1206 Bug 1966149: [release-4.8] Re-Change the job template name back to its original one
  controllers/storagecluster/reconcile.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#1209 GateWay spec's 'Instances' field should be minimum 1
  controllers/storagecluster/external_resources.go
Labels: approved, lgtm, ok-to-test

#1211 topology: fix crash in determinePlacementRack
  controllers/storagecluster/topology.go
  controllers/storagecluster/topology_test.go
Labels: approved, lgtm

#1208 must-gather: collect logs for RegionalDR
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_namespaced_resources
Labels: approved, lgtm

#1215 Update the ocs-osd-removal template description
  controllers/storagecluster/job_templates.go
Labels: approved, lgtm

#1204 update external-snapshotter version to v4.1.0
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/uninstall_reconciler_test.go
  controllers/storagecluster/volumesnapshotterclasses.go
  controllers/storagecluster/volumesnapshotterclasses_test.go
  go.mod
  go.sum
  main.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#1217 Adding 'thick-provision' storageclass to External cluster
  controllers/storagecluster/external_resources.go
Labels: approved, lgtm, ok-to-test

#1222 Bug 1962281: Update the ocs-osd-removal template description #1215
  controllers/storagecluster/reconcile.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1221 Bumping NooBaa version
  deploy/bundle/manifests/namespacestore.crd.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/crds/noobaa/noobaa-crd.yaml
  deploy/csv-templates/noobaa-csv.yaml
  hack/common.sh
Labels: approved, lgtm, ok-to-test

#1226 Set the operator readiness state to true on StorageCluster removal
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1228 Bump ocs-operator to v4.9.0
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  hack/common.sh
  hack/generate-master-appregistry.sh
  hack/generate-master-bundle.sh
  version/version.go
Labels: approved, lgtm

#1229 Add RBAC for creating service monitors from mgr sidecar
  deploy/bundle/manifests/rook-monitor-mgr-role.yaml
  deploy/bundle/manifests/rook-monitor-mgr-role_binding.yaml
  rbac/rook-monitor-mgr-role.yaml
  rbac/rook-monitor-mgr-role_binding.yaml
Labels: approved, lgtm

#1225 Don't report Ready when CephCluster has not reached ClusterStateCreated
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#1194 deps: update Golang to 1.16
  go.mod
Labels: approved, lgtm

#1220 must-gather: collect ceph CR's logs when external cluster is deployed
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_common_ceph_resources
Labels: approved, lgtm

#1234 Thick Provision SC Parameters has to be updated
  controllers/storagecluster/external_resources.go
Labels: approved, lgtm, ok-to-test

#1238 Update Rook image version
  deploy/bundle/manifests/cephblockpool.crd.yaml
  deploy/bundle/manifests/cephclient.crd.yaml
  deploy/bundle/manifests/cephcluster.crd.yaml
  deploy/bundle/manifests/cephfilesystem.crd.yaml
  deploy/bundle/manifests/cephfilesystemmirror.crd.yaml
  deploy/bundle/manifests/cephnfs.crd.yaml
  deploy/bundle/manifests/cephobjectrealm.crd.yaml
  deploy/bundle/manifests/cephobjectstore.crd.yaml
  deploy/bundle/manifests/cephobjectstoreuser.crd.yaml
  deploy/bundle/manifests/cephobjectzone.crd.yaml
  deploy/bundle/manifests/cephobjectzonegroup.crd.yaml
  deploy/bundle/manifests/cephrbdmirror.crd.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/bundle/manifests/volumereplication.crd.yaml
  deploy/bundle/manifests/volumereplicationclass.crd.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephblockpools.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclients.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephfilesystemmirrors.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephfilesystems.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephnfses.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectrealms.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectstores.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectstoreusers.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectzonegroups.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectzones.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephrbdmirrors.yaml
  deploy/csv-templates/crds/rook/replication.storage.openshift.io_volumereplicationclasses.yaml
  deploy/csv-templates/crds/rook/replication.storage.openshift.io_volumereplications.yaml
  deploy/csv-templates/rook-csv.yaml.in
  hack/common.sh
Labels: approved, lgtm

#1241 Updates DEBUG_EXPORTS.sh and adds new make target
  Makefile
  extras/DEBUG_EXPORTS.sh
Labels: approved, lgtm

#1240 logger: add zap flags to commandline
  main.go
Labels: approved, lgtm

#1244 must-gather: Don't download and install jq
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm
