Repository red-hat-storage/ocs-operator, pull requests merged in 2021-01, with the labels that each got.

#894 Refactor: Introduce an interface to enforce a developer to create a func for resource creation and deletion both
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/cephobjectstoreusers.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
  controllers/storagecluster/quickstarts.go
  controllers/storagecluster/quickstarts_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/uninstall_reconciler.go
  controllers/storagecluster/uninstall_reconciler_test.go
  controllers/storagecluster/volumesnapshotterclasses.go
Labels: approved, kind/cleanup, lgtm

#943 Updating the annotation for newly enabled features
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test

#968 must-gather: gather ceph logs only when storageclusters is present
  must-gather/collection-scripts/gather
Labels: approved, lgtm

#976 [release-4.7] Release 4.7 newly enabled features
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, priority/critical-urgent

#975 Changing NooBaa's SCC to RunAsAny instead of RunAsRange
  controllers/ocsinitialization/sccs.go
Labels: approved, lgtm, ok-to-test

#983 Remove usage of outdated coreos/prometheus-operator
  go.mod
  main.go
  vendor/github.com/coreos/prometheus-operator/LICENSE
  vendor/github.com/coreos/prometheus-operator/NOTICE
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#987 Must-gather: Add SCC to cluster-scoped must-gather
  must-gather/collection-scripts/gather_clusterscoped_resources
Labels: approved, lgtm, ok-to-test

#986 Fixes typos and numberings for the list in Getting Started Quickstart
  controllers/storagecluster/quickstart_constants.go
Labels: approved, lgtm

#955 cephcluster: tune disks according to plaftorm
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/platform_detection.go
  controllers/storagecluster/storagecluster_controller_test.go
Labels: approved, lgtm

#988 Must-gather: Update OWNERS file
  must-gather/OWNERS
Labels: approved, lgtm

#977 must-gather: add helper pod yaml with compatible secret for <4.6
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/templates/pod.template.latest
  must-gather/templates/pod.template.standard
Labels: approved, lgtm

#981 update readme
  README.md
Labels: approved, lgtm

#969 Removes the OSD IDs from the osd removal job name
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#989 Adjust mon_max_pg_per_osd for Rook-Ceph
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#990 Refactor: Remove redundant logger from StorageClusterReconciler methods
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/ocsinitialization/sccs.go
  controllers/persistentvolume/reconcile.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/cephobjectstores_test.go
  controllers/storagecluster/cephobjectstoreusers.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/topology.go
  controllers/storagecluster/topology_test.go
  controllers/storagecluster/uninstall_reconciler.go
  controllers/storagecluster/uninstall_reconciler_test.go
  controllers/storagecluster/volumesnapshotterclasses.go
Labels: approved, lgtm

#992 storagecluster: Enhance Noobaa ensureDeleted logging
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: approved, lgtm

#1002 Bug 1915737: [release-4.7] storagecluster: Enhance Noobaa ensureDeleted logging
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#601 Design document for admission controllers in OCS
  docs/design/admission-webhooks.md
Labels: approved, lgtm

#1004 Makefile: re-add target update-generated
  Makefile
Labels: approved, lgtm

#993 fix misspelling across codebase
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/placement_test.go
  controllers/storagecluster/reconcile.go
  controllers/util/predicates.go
  pkg/deploy-manager/config.go
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#995 remove ineffectual assignment from prometheus.go
  controllers/storagecluster/placement_test.go
  controllers/storagecluster/prometheus.go
Labels: approved, lgtm

#1010 Fail validation if arbiter and flexibleScaling both are enabled
  controllers/storagecluster/reconcile.go
  controllers/util/events.go
Labels: approved, lgtm

#1005 Remove OCS CPU telemetry metric rules
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/rules/rules.libsonnet
Labels: approved, lgtm

#1007 Add LogCollector to CephCluster CRD
  controllers/storagecluster/cephcluster.go
Labels: approved, lgtm

#967 Make must-gather more efficient
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/post-uninstall.sh
  must-gather/collection-scripts/pre-install.sh
Labels: approved, lgtm
