Repository red-hat-storage/ocs-operator, pull requests merged in 2021-04, with the labels that each got.

#1142 Annotation for thick-provisioner and pool-management feature
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#1145 Use curl instead of wget
  hack/golangci_lint.sh
  hack/shellcheck-test.sh
Labels: approved, lgtm

#1143 test: fix verify-latest-csv
  hack/verify-latest-csv.sh
Labels: approved, lgtm

#1147 Adds noobaa.namespacestores.io to the exposed APIs
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#1146 storagecluster: Fix Update in validateStorageClusterSpec
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1148 storagecluster: Fix intermediate ready phase in storage cluster during installation
  controllers/storagecluster/cephcluster.go
Labels: approved, lgtm

#1111 must-gather: add logs in debug file that were skipped
  must-gather/collection-scripts/gather_ceph_resources
Labels: approved, lgtm

#1114 [Ocs extend cluster limit] Implementing an automated way to recover from read-only mode
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm, ok-to-test

#1157 Fix tests after fake client update
  controllers/ocsinitialization/ocsinitialization_controller_test.go
Labels: approved, lgtm

#1162 hack: fix new shellcheck issue SC2269
  hack/common.sh
Labels: approved, lgtm

#1160 Add volume replication operator image to CSV
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm

#1161 Allow passing explicit DeviceClass
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, lgtm

#1155 storagecluster: Increase mons db allocated space
  controllers/storagecluster/cephcluster.go
Labels: approved, lgtm

#1159 predicates: avoid theoretical nil pointer deref
  controllers/util/predicates.go
Labels: approved, lgtm

#1163 Explicit osd weight
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: approved, lgtm

#1164 do not pass labels as map of single empty string
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1154 updated noobaa core\operator images in common.sh
  controllers/ocsinitialization/sccs.go
  deploy/bundle/manifests/namespacestore.crd.yaml
  deploy/bundle/manifests/noobaa.crd.yaml
  deploy/bundle/manifests/objectbucketclaim.crd.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/crds/noobaa/noobaa-crd.yaml
  deploy/csv-templates/noobaa-csv.yaml
  hack/common.sh
  hack/source-manifests.sh
Labels: approved, lgtm, ok-to-test

#1167 fix noobaa core desired image
  controllers/storagecluster/reconcile.go
Labels: approved, lgtm

#1165 Update CSV to use taint-nodes
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, lgtm, ok-to-test

#1166 storagecluster: Add PriorityClasses to the cephcluster definition
  controllers/storagecluster/cephcluster.go
Labels: approved, lgtm

#1169 storagecluster: Add PriorityClasses support for all resources
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/external_resources.go
Labels: approved, lgtm

#1173 Bug 1776876: [release-4.8] Add priority Class for the ceph resources
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/external_resources.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1170 hack: Change the order of the IMAGE_BUILD_CMD
  hack/build-appregistry.sh
  hack/build-container.sh
  hack/build-master-appregistry.sh
  hack/build-must-gather.sh
  hack/build-operator-bundle.sh
  hack/build-operator-index.sh
  hack/build-operator.sh
  hack/common.sh
  hack/docker-common.sh
  hack/source-manifests.sh
  hack/verify-operator-bundle.sh
Labels: approved, lgtm
