Repository red-hat-storage/ocs-operator, pull requests merged in 2022-09, with the labels that each got.

#1786 Fix StorageCluster is in error state for few minutes after installing
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#1789 disaster recovery: create clusterclaims during reconcile
  config/rbac/role.yaml
  controllers/storagecluster/clusterclaims.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/uninstall_reconciler.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/modules.txt
  vendor/open-cluster-management.io/api/LICENSE
  vendor/open-cluster-management.io/api/cluster/v1/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1/doc.go
  vendor/open-cluster-management.io/api/cluster/v1/register.go
  vendor/open-cluster-management.io/api/cluster/v1/types.go
  vendor/open-cluster-management.io/api/cluster/v1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1/zz_generated.swagger_doc_generated.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/0000_00_clusters.open-cluster-management.io_managedclustersets.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1alpha1/0000_01_clusters.open-cluster-management.io_managedclustersetbindings.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1alpha1/0000_02_clusters.open-cluster-management.io_clusterclaims.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1alpha1/0000_03_clusters.open-cluster-management.io_placements.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1alpha1/0000_04_clusters.open-cluster-management.io_placementdecisions.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1alpha1/0000_05_clusters.open-cluster-management.io_addonplacementscores.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1alpha1/0001_02_clusters.open-cluster-management.io_clusterclaims.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1alpha1/doc.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/register.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/types.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/types_addonplacementscore.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#1790 Integration with Thales enterprise key management
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/kms_resources.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
Labels: lgtm, approved

#1793 Add user iamniting in approver list
  OWNERS
Labels: lgtm, approved

#1772 Adding a metric to show advance cluster feature use
  go.mod
  go.sum
  metrics/internal/collectors/cluster-advance-feature-use.go
  metrics/internal/collectors/registry.go
  vendor/k8s.io/client-go/listers/storage/v1/csidriver.go
  vendor/k8s.io/client-go/listers/storage/v1/csinode.go
  vendor/k8s.io/client-go/listers/storage/v1/expansion_generated.go
  vendor/k8s.io/client-go/listers/storage/v1/storageclass.go
  vendor/k8s.io/client-go/listers/storage/v1/volumeattachment.go
  vendor/modules.txt
Labels: lgtm, approved

#1798 Return csv version instead of name
  controllers/storagecluster/clusterclaims.go
Labels: lgtm, approved

#1799 Package and CSV version updates to 4.12
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  hack/common.sh
  version/version.go
Labels: lgtm, approved

#1785 Security fixes: privilege escalation control, run as non root, drop capabilities
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
Labels: lgtm, approved

#1792 must-gather: add ceph log last commands
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved, ok-to-test

#1796 🧹hack scripts shebang cleanup
  hack/build-appregistry.sh
  hack/build-container.sh
  hack/build-functest.sh
  hack/build-master-appregistry.sh
  hack/build-metrics-exporter.sh
  hack/build-must-gather.sh
  hack/build-operator-bundle.sh
  hack/build-operator-index.sh
  hack/build-operator.sh
  hack/clean.sh
  hack/cluster-clean.sh
  hack/cluster-deploy.sh
  hack/common.sh
  hack/docker-common.sh
  hack/dump-debug-info.sh
  hack/ensure-operator-sdk.sh
  hack/ensure-opm.sh
  hack/functest.sh
  hack/gen-deployment-yaml.sh
  hack/gen-protobuf.sh
  hack/generate-appregistry.sh
  hack/generate-latest-csv.sh
  hack/generate-master-appregistry.sh
  hack/generate-master-bundle.sh
  hack/generate-master-csv.sh
  hack/generate-unified-csv.sh
  hack/go-build.sh
  hack/golangci_lint.sh
  hack/operator-sdk-common.sh
  hack/red-hat-storage-ocs-ci-tests.sh
  hack/shellcheck-test.sh
  hack/source-manifests.sh
  hack/ticketgen/ticketcheck.sh
  hack/ticketgen/ticketgen.sh
  hack/verify-dependencies.sh
  hack/verify-generated.sh
  hack/verify-latest-csv.sh
  hack/verify-latest-deploy-yaml.sh
  hack/verify-operator-bundle.sh
Labels: lgtm, approved, ok-to-test

#1782 Ceph Non-resilient Pools - Dev Preview
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephconfig.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/storageclasses.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: lgtm, approved

#1755 add metrics for total objects and bucket count
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/internal/collectors/object-bucket.go
  metrics/mixin/rules/rules.libsonnet
Labels: lgtm, approved

#1800 Give correct name for poolName in the non-resilient pool storageclass
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#1797 remove vr and vrc CRDs from owned
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/bundle/manifests/volumereplication.crd.yaml
  deploy/bundle/manifests/volumereplicationclass.crd.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1769 Remove volume replication operator image from ocs-operator
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1803 Some corrections in Non-Resilient cephblockpool & storageclass
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#1801 Advanced feature metric should be send per ODF installation
  metrics/internal/collectors/cluster-advance-feature-use.go
Labels: lgtm, approved

#1734 Fix 'CephOSDVersionMismatch' and 'CephMonVersionMismatch' alerts
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#1750 Add StorageProfile support
  Makefile
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/storageclassclaim_types.go
  config/crd/bases/ocs.openshift.io_storageclassclaims.yaml
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storageclassclaim/storageclassclaim_controller.go
  controllers/storagecluster/backingstorageclasses.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/uninstall_reconciler.go
  deploy/bundle/manifests/storageclassclaim.crd.yaml
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclassclaims.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  go.mod
  services/provider/client/client.go
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  services/provider/server/server_test.go
  services/provider/server/storageclaim.go
Labels: lgtm, approved

#1760 NFS Dev Preview : Allow volume expansion for NFS & deploy a NFS volumesnapshot class
  controllers/storagecluster/generate.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/volumesnapshotterclasses.go
  controllers/storagecluster/volumesnapshotterclasses_test.go
Labels: lgtm, approved

#1806 Bug 2125958: Add permissions to storagecluster reconciler
  config/rbac/role.yaml
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  main.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1805 Add separate 'SharedIndexInformer' to each feature providers
  metrics/internal/collectors/cluster-advance-feature-use.go
Labels: lgtm, approved

#1802 reduce cardinality for odf_system_bucket_count and odf_system_objects_total
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/rules/rules.libsonnet
Labels: lgtm, approved

#1809 fix bugs in storageclassclaim controller for storageprofile
  controllers/storageclassclaim/storageclassclaim_controller.go
Labels: lgtm, approved

#1810 Upgrade ocs metrics exporter & ocs operator to use golang 1.18 image
  Dockerfile
  metrics/Dockerfile
Labels: lgtm, approved

#1804 Remove PV controller
  config/rbac/role.yaml
  controllers/persistentvolume/persistentvolume_controller.go
  controllers/persistentvolume/persistentvolume_controller_test.go
  controllers/persistentvolume/reconcile.go
  controllers/persistentvolume/reconcile_test.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  main.go
Labels: lgtm, approved

#1811 WaitForCacheSync in storageclassclaim Reconcile
  controllers/storageclassclaim/storageclassclaim_controller.go
  main.go
Labels: lgtm, approved

#1814 Various QoL changes from jarrpa-dev
  .github/workflows/ocs-operator-ci.yaml
  Makefile
  controllers/storagecluster/storagecluster_controller_test.go
  hack/build-functest.sh
  hack/common.sh
  hack/source-manifests.sh
Labels: lgtm, approved

#1818 Various fixes to initial GitHub Actions
  .github/workflows/ocs-operator-ci.yaml
  .golangci.yaml
  Makefile
  api/v1alpha1/groupversion_info.go
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/ocsinitialization/ocsinitialization_controller_test.go
  controllers/storageclassclaim/storageclassclaim_controller.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/uninstall_reconciler.go
  controllers/storagecluster/uninstall_reconciler_test.go
  functests/common.go
  hack/golangci_lint.sh
  hack/verify-operator-bundle.sh
  metrics/internal/collectors/object-bucket_test.go
  metrics/internal/exporter/registry.go
  pkg/deploy-manager/common.go
  pkg/deploy-manager/config.go
  test/crd_validation_test.go
  tools/cluster-deploy/cluster-deploy.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1813 Remove privileged access from metrics-exporter
  controllers/ocsinitialization/sccs.go
  deploy/bundle/manifests/ceph-conf.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/deploy/ceph-conf.yaml
  metrics/deploy/deployment.yaml
  metrics/internal/cache/rbd-mirror.go
  rbac/ceph-conf.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1824 Fix few mistakes in workflow & add code-spell workflow
  .github/workflows/ocs-operator-ci.yaml
  controllers/storageclassclaim/storageclassclaim_controller.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/job_templates.go
  controllers/storagecluster/provider_server_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/topology.go
  controllers/storagecluster/volumesnapshotterclasses.go
  controllers/storageconsumer/storageconsumer_controller.go
  docs/design/metrics-exporter.md
  docs/design/osd-topology-spread-constraints.md
  docs/openshift-ci.md
  hack/cluster-deploy.sh
  hack/red-hat-storage-ocs-ci-tests.sh
  main.go
  must-gather/collection-scripts/gather_namespaced_resources
  must-gather/collection-scripts/gather_noobaa_resources
  pkg/deploy-manager/storagecluster.go
  services/provider/server/server.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1817 Limit OCS operator leaderElection & cache to operator namespace
  main.go
Labels: lgtm, approved

#1699 Remove NooBaa SCCs generation
  controllers/ocsinitialization/sccs.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/crds/noobaa/noobaa-crd.yaml
  deploy/csv-templates/noobaa-csv.yaml
  hack/common.sh
  openshift-ci/database/index.db
Labels: lgtm, approved, ok-to-test

#1826 Fix permissions for newly added resources
  deploy/bundle/manifests/exporter-role.yaml
  metrics/deploy/rbac.yaml
  rbac/exporter-role.yaml
Labels: lgtm, approved

#1827 add "noobaa-standalone" daemonplacement for MCG standalone deployment
  controllers/defaults/placements.go
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved, ok-to-test

#1830 add nil pointer check to ObjectStore collector
  metrics/internal/collectors/cluster-advance-feature-use.go
Labels: lgtm, approved
