Repository red-hat-storage/ocs-operator, pull requests merged in 2022-06, with the labels that each got.

#1701 fix namespace problem in storageclassclaim controller
  controllers/storageclassclaim/storageclassclaim_controller.go
  controllers/util/k8sutil.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  main.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1704 odf-to-odf: initialize map when adding labels
  controllers/storageclassclaim/storageclassclaim_controller.go
Labels: lgtm, approved

#1703 odf to odf: start using LoadBalancer type for ocs-provider-server svc
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
Labels: lgtm, approved

#1698 fix noobaa uninstall process
  controllers/storagecluster/uninstall_reconciler.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/crds/noobaa/noobaa-crd.yaml
  deploy/csv-templates/noobaa-csv.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/LICENSE
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/Srcfile
  vendor/github.com/emicklei/go-restful/bench_test.sh
  vendor/github.com/emicklei/go-restful/compress.go
  vendor/github.com/emicklei/go-restful/compressor_cache.go
  vendor/github.com/emicklei/go-restful/compressor_pools.go
  vendor/github.com/emicklei/go-restful/compressors.go
  vendor/github.com/emicklei/go-restful/constants.go
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/coverage.sh
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/curly_route.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/doc.go
  vendor/github.com/emicklei/go-restful/entity_accessors.go
  vendor/github.com/emicklei/go-restful/filter.go
  vendor/github.com/emicklei/go-restful/json.go
  vendor/github.com/emicklei/go-restful/jsoniter.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/log/log.go
  vendor/github.com/emicklei/go-restful/logger.go
  vendor/github.com/emicklei/go-restful/mime.go
  vendor/github.com/emicklei/go-restful/options_filter.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_expression.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/router.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/github.com/emicklei/go-restful/web_service_container.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/common/doc.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test

#1708 cleanup: No NODE_OUTPUT_DIR to collect volume logs
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved

#1710 enable cephfs in consumer mode.
  controllers/storagecluster/external_resources.go
Labels: lgtm, approved

#1717 Bug 2088587: backport to 4.11 - fix noobaa uninstall
  controllers/storagecluster/uninstall_reconciler.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/crds/noobaa/noobaa-crd.yaml
  deploy/csv-templates/noobaa-csv.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/LICENSE
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/Srcfile
  vendor/github.com/emicklei/go-restful/bench_test.sh
  vendor/github.com/emicklei/go-restful/compress.go
  vendor/github.com/emicklei/go-restful/compressor_cache.go
  vendor/github.com/emicklei/go-restful/compressor_pools.go
  vendor/github.com/emicklei/go-restful/compressors.go
  vendor/github.com/emicklei/go-restful/constants.go
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/coverage.sh
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/curly_route.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/doc.go
  vendor/github.com/emicklei/go-restful/entity_accessors.go
  vendor/github.com/emicklei/go-restful/filter.go
  vendor/github.com/emicklei/go-restful/json.go
  vendor/github.com/emicklei/go-restful/jsoniter.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/log/log.go
  vendor/github.com/emicklei/go-restful/logger.go
  vendor/github.com/emicklei/go-restful/mime.go
  vendor/github.com/emicklei/go-restful/options_filter.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_expression.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/router.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/github.com/emicklei/go-restful/web_service_container.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/common/doc.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#1721 must-gather: add Yati as an approver for must-gather
  must-gather/OWNERS
Labels: lgtm, approved

#1719 Fix KMS regression in MCG deployment
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
Labels: lgtm, approved

#1726 Fix `encryptionMethod` condition
  controllers/storageclassclaim/storageclassclaim_controller.go
Labels: lgtm, approved

#1728 odf to odf: keep the old nodeport provider service
  controllers/storagecluster/provider_server.go
Labels: lgtm, approved

#1732 storagecluster: add CephCluster reconcile strategy
  Makefile
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/noobaa-csv.yaml
  hack/common.sh
  hack/golangci_lint.sh
Labels: approved

#1730 Add support to create volumesnapshotclass per storageclassclaim
  config/rbac/role.yaml
  controllers/storageclassclaim/storageclassclaim_controller.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#1739 Bug 2101741: [release-4.10] collect mirroring resources in separate f…
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1715 must-gather: collects output for storageclassclaim
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved
