Repository red-hat-storage/ocs-operator, pull requests merged in 2022-02, with the labels that each got.

#1468 ocs-to-ocs: make sure no storageConsumer exists in the provider
  controllers/storagecluster/uninstall_reconciler.go
Labels: lgtm, approved

#1469 ocs-to-ocs: verify consumer is onboarded before offboarding
  controllers/storagecluster/external_resources.go
Labels: lgtm, approved

#1470 api: split connection string into 2 new fields
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/external_ocs.go
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: lgtm, approved

#1475 must-gather: skip helper pod creation and ceph log collection
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/post-uninstall.sh
  must-gather/collection-scripts/pre-install.sh
Labels: lgtm, approved, Bug

#1480 rgw-kms: fix invalid memory issue
  controllers/storagecluster/cephobjectstores.go
Labels: lgtm, approved, ok-to-test

#1442 Fix no RBD mirroring daemon alert when daemon is down issue
  deploy/bundle/manifests/exporter-role.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/internal/collectors/ceph-cluster.go
  metrics/internal/collectors/ceph-cluster_test.go
  metrics/internal/collectors/ceph-rbd-mirror.go
  metrics/internal/collectors/ceph-rbd-mirror_test.go
  metrics/internal/collectors/registry.go
  metrics/mixin/alerts/mirroring.libsonnet
  rbac/exporter-role.yaml
Labels: lgtm, approved

#1477 api: Add StorageProviderEndpoint field in the storageCluster status
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/external_ocs.go
  controllers/storagecluster/provider_server.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: lgtm, approved

#1445 storageconsumer: modify api status for rbd, cephfs and cephuser
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/bundle/manifests/storageconsumer.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
Labels: lgtm, approved

#1486 provider: create resources to add permissions to the server
  controllers/storagecluster/provider_server.go
  deploy/bundle/manifests/provider-role.yaml
  deploy/bundle/manifests/provider-role_binding.yaml
  deploy/bundle/manifests/provider-sa.yaml
  rbac/provider-role.yaml
  rbac/provider-role_binding.yaml
  rbac/provider-sa.yaml
Labels: lgtm, approved

#1446 StorageConsumer: [Ceph rbd] Add controller changes to provide storage service for consumers
  config/rbac/role.yaml
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
Labels: lgtm, approved

#1484 Remove clusterresourcequota metrics
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/internal/collectors/registry.go
  metrics/internal/collectors/storagequota.go
  metrics/internal/collectors/storagequota_test.go
  metrics/mixin/alerts/cluster-resource-quota.libsonnet
  vendor/github.com/openshift/client-go/quota/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/typed/quota/v1/appliedclusterresourcequota.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/typed/quota/v1/clusterresourcequota.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/typed/quota/v1/doc.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/typed/quota/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/typed/quota/v1/quota_client.go
  vendor/github.com/openshift/client-go/quota/listers/quota/v1/appliedclusterresourcequota.go
  vendor/github.com/openshift/client-go/quota/listers/quota/v1/clusterresourcequota.go
  vendor/github.com/openshift/client-go/quota/listers/quota/v1/expansion_generated.go
  vendor/modules.txt
Labels: lgtm, approved, Bug

#1485 validate onboarding ticket signature.
  services/provider/server/server.go
Labels: lgtm, approved

#1492 StorageConsumer: [CephFS] Add controller changes to provide storage service for consumers
  config/rbac/role.yaml
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
Labels: lgtm, approved

#1403 storagecluster: allow any storageclass for storagequota
  controllers/storagecluster/reconcile.go
Labels: lgtm, approved, Bug

#1496 ocs-to-ocs: fetch cephFilesystemSubVolumeGroup resources
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#1504 ocs-to-ocs: check if ticket date is greater than current date
  services/provider/server/server.go
Labels: lgtm, approved

#1503 Storageconsumer: Added changes to fix cephresource spec update
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/storageconsumer/storageconsumer_controller.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#1509 rgw-kms: skip unsupported configs
  controllers/storagecluster/cephobjectstores.go
Labels: lgtm, approved, ok-to-test, Bug

#1516 ocs-to-ocs: list within namespace
  controllers/storagecluster/provider_server.go
  deploy/bundle/manifests/provider-role.yaml
  rbac/provider-role.yaml
  services/provider/server/consumer.go
Labels: lgtm, approved

#1501 expose option to force remove the OSD in osd removal template
  controllers/storagecluster/job_templates.go
  controllers/storagecluster/job_templates_test.go
Labels: lgtm, approved

#1519 controllers: Do not list node in the namespace
  controllers/storagecluster/provider_server.go
  deploy/bundle/manifests/provider-role.yaml
  rbac/provider-role.yaml
Labels: lgtm, approved

#1482 Skip SC creation for vault SA based kms encryption
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved, Bug

#1522 storageconsumer: Fix nil map and subvolume group naming
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#1527 StorageConsumer: fix caps for cephClientCephFSNode and cephClientCephFSProvisioner
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#1525 update capacity only if requested and granted capacity are different
  controllers/storagecluster/external_resources.go
Labels: lgtm, approved

#1524 fix onboardingTicket unmarshalling
  services/provider/server/server.go
Labels: lgtm, approved

#1537 Controller: StorageConsumer fix to update kind field in cephResources status
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#1539 Update rbac to correctly read rook resources
  deploy/bundle/manifests/provider-role.yaml
  rbac/provider-role.yaml
  services/provider/server/server.go
Labels: lgtm, approved

#1541 prefix `client` before ceph username
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#1544 Return granted capacity in UpdataCapacity grpc response
  services/provider/server/server.go
Labels: lgtm, approved

#1543 ocs-to-ocs: get mgr pod hostIP
  deploy/bundle/manifests/provider-role.yaml
  rbac/provider-role.yaml
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#1547 rook-ceph: change osd_memory_target value to 0.8
  controllers/storagecluster/cephconfig.go
Labels: lgtm, approved

#1530 ocs to ocs: small general fixes
  controllers/storagecluster/external_ocs.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/reconcile.go
Labels: lgtm, approved

#1548 Inject toleration to rook-ceph-tools
  api/v1/ocsinitialization_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_ocsinitializations.yaml
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/ocsinitialization/ocsinitialization_controller_test.go
  deploy/bundle/manifests/ocsinitialization.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_ocsinitializations.yaml
Labels: lgtm, approved, Bug

#1433 Decreasing the timeout of 'ODF_standardized_metrics.rules' group to 30s
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/alerts-external.libsonnet
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/rules/rules.libsonnet
Labels: lgtm, approved, ok-to-test, Bug

#1559 [review comment] Set allowVolumeExpansion to False for encrypted SC
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#1560 Bug 2044288: [release-4.10] Set allowVolumeExpansion to False for encrypted SC
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1556 controllers: exit reconcile loop immediately after updating the storagecluster annotations
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/uninstall_reconciler.go
  controllers/storagecluster/uninstall_reconciler_test.go
Labels: lgtm, approved
