Repository red-hat-storage/ocs-operator, pull requests merged in 2022-11, with the labels that each got.

#1877 delete Secret for external RHCS
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/uninstall_reconciler.go
Labels: lgtm, approved

#1879 Sync all the libsonnet changes to metrics deploy files
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved

#1875 Enable verbose logging when rbd mirroing is enabled for debugging
  config/rbac/role.yaml
  controllers/storagecluster/cephrbdmirrors.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  main.go
Labels: lgtm, approved

#1868 Update NooBaa core and endpoint default CPU resource values
  controllers/defaults/resources.go
Labels: lgtm, approved, ok-to-test

#1886 must-gather: collect journal and kernel logs for all nodes
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved

#1887 Bug 2124280: [release-4.10] Sync all the libsonnet changes to metrics deploy files
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: bugzilla/valid-bug, bugzilla/severity-high

#1888 Bug 2124282: [release-4.9] Sync all libsonnet changes
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: bugzilla/valid-bug, bugzilla/severity-high
