Repository red-hat-storage/ocs-operator, pull requests merged in 2022-04, with the labels that each got.

#1609 Implement GetStorageClassClaimConfig RPC call
  api/v1alpha1/storageclassclaim_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclassclaims.yaml
  deploy/bundle/manifests/storageclassclaim.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclassclaims.yaml
  services/provider/server/server.go
  services/provider/server/server_test.go
  services/provider/server/storageclaim.go
Labels: lgtm, approved

#1617 cleanup: resolve syntax error
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved

#1616 add csi nfs image to the csv
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1618 add a option to disable route for cephobjectstore
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/routes.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: lgtm, approved, ok-to-test

#1600 add termination policy to TLS in cephobjectstore route
  controllers/storagecluster/routes.go
Labels: lgtm, approved, ok-to-test

#1607 ocs to ocs: create default storageclassclaims
  controllers/storagecluster/external_ocs.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/uninstall_reconciler.go
Labels: lgtm, approved

#1625 must-gather: collect volumesnapshot of all namespaces
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved

#1627 server: remove mock calls from the actual server
  services/provider/server/server.go
  services/provider/server/server_mock.go
Labels: lgtm, approved

#1614 fix cluster resource quota names containing double ocs prefix
  controllers/storagecluster/generate.go
Labels: lgtm, approved, ok-to-test

#1593 Add an annotation to disable wizard flow in console
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1512 update imagefeature in rbd storageclass
  controllers/storagecluster/storageclasses.go
  services/provider/server/server.go
Labels: lgtm, approved

#1626 Add missing StorageClassClaim entry to PROJECT
  PROJECT
  config/manifests/bases/ocs-operator.clusterserviceversion.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
Labels: lgtm, approved

#1629 Update ceph-csi/api and use k8s.gcr.io for csi nfsplugin image
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/ceph/ceph-csi/api/deploy/ocp/scc.yaml
  vendor/modules.txt
Labels: lgtm, approved

#1636 add StorageType as input param for FulfillStorageClassClaim
  services/provider/client/client.go
Labels: lgtm, approved

#1624 Revert "add termination policy to TLS in cephobjectstore route"
  controllers/storagecluster/routes.go
Labels: lgtm, approved, ok-to-test

#1635 storagecluster: Add CephNFS deployment
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  config/rbac/role.yaml
  controllers/defaults/placements.go
  controllers/defaults/resources.go
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephnfs.go
  controllers/storagecluster/cephnfs_test.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
  controllers/storagecluster/uninstall_reconciler.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  pkg/deploy-manager/storagecluster.go
Labels: lgtm, approved

#1612 hack: update ticketgen scripts
  hack/ticketgen/README.md
  hack/ticketgen/ticketcheck.sh
  hack/ticketgen/ticketgen.sh
Labels: lgtm, approved

#1630 controllers: Fix the list options
  controllers/storagecluster/external_resources.go
Labels: lgtm, approved

#1619 Add unit test for storageclassclaim RPC
  services/provider/server/server_test.go
Labels: lgtm, approved

#1622 must-gather: empty the pids as it is exceeding the limits
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved

#1637 use `quay.io/ceph/ceph:v16` for ceph image
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: lgtm, approved

#1639 [BZ: 2076468]Added extra rook configs for provider clusters
  controllers/storagecluster/cephconfig.go
  controllers/storagecluster/cephconfig_test.go
Labels: lgtm, approved

#1603 ocs-to-ocs: storageclassclaim cntrl provider change
  api/v1alpha1/storageclassclaim_types.go
  config/rbac/role.yaml
  controllers/storageclassclaim/storageclassclaim_controller.go
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  services/provider/server/server.go
  services/provider/server/storageclaim.go
Labels: lgtm, approved

#1642 ocs-to-ocs: fix wrong error check
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#1419 Notify if KMS connection to the server is lost
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: lgtm, approved

#1640 Add an annotation to disable components flow in console
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1646 Bug 2074591: [release 4.9] add a option to disable route for cephobjectstore
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/routes.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1608 Implement StorageClassClaim creation for consumer cluster
  api/v1alpha1/storageclassclaim_types.go
  config/rbac/role.yaml
  controllers/storageclassclaim/storageclassclaim_controller.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
Labels: lgtm, approved
