Repository red-hat-storage/ocs-operator, pull requests merged in 2022-08, with the labels that each got.

#1735 odf-to-odf: Introduce heartbeat mechanism to check connectivity
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  build/Dockerfile
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  config/rbac/role.yaml
  controllers/storagecluster/external_ocs.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/consumer-role.yaml
  deploy/bundle/manifests/consumer-role_binding.yaml
  deploy/bundle/manifests/consumer-sa.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/bundle/manifests/provider-role.yaml
  deploy/bundle/manifests/storageconsumer.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  hack/go-build.sh
  rbac/consumer-role.yaml
  rbac/consumer-role_binding.yaml
  rbac/consumer-sa.yaml
  rbac/provider-role.yaml
  services/consumer/main.go
  services/provider/client/client.go
  services/provider/pb/provider.pb.go
  services/provider/pb/provider_grpc.pb.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/server.go
Labels: lgtm, approved

#1648 Moving the defaults for rookceph operator from configmap to csv
  controllers/ocsinitialization/ocsinitialization_controller.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1762 odf-to-odf: clean consumer cr status
  controllers/storageconsumer/consumer_test.go
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#1767 must-gather: collect JSON output for "rbd snap ls --all" as well
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved, ok-to-test

#1768 Initialize rookCephOperatorCM if data is nil
  controllers/storagecluster/external_resources.go
Labels: lgtm, approved

#1763 Enable adjustable control for sidecar logs
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1770 Initialize the rookcephoperatorconfig CM while creation & cleanup externalresources test
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/external_resources_test.go
Labels: lgtm, approved

#1718 hack: make golangci-lint.sh more verbose
  .golangci.yaml
  controllers/storageclassclaim/storageclassclaim_controller.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/generate.go
  hack/golangci_lint.sh
Labels: lgtm, approved

#1749 must-gather: removes duplicate pods -owide output
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved

#1757 Bug 2107073: [release-4.10] mark enableRookCSICephFS as true always in consumer cluster
  controllers/storagecluster/external_resources.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#1773 Add two new variables for Ceph-CSI to set as metadata on RBD & CephFS
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/ocsinitialization/ocsoperator_config.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1766 rename kube_pv and add LVM pvs count
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#1781 Bug 2119517: [release 4.6] expose option to force remove the OSD in osd
  pkg/controller/storagecluster/reconcile.go
Labels: lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1779 Bug 2119513: [release 4.8] expose option to force remove the OSD in osd…
  api/v1/zz_generated.deepcopy.go
  controllers/storagecluster/reconcile.go
Labels: approved, bugzilla/valid-bug, bugzilla/severity-high

#1780 Bug 2119516:[release-4.7]expose option to force remove the OSD in osd
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  hack/source-manifests.sh
Labels: bugzilla/valid-bug, bugzilla/severity-high

#1775 rook: add logCollector in storageCluster and update to rook v1.9.9
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/bundle/manifests/cephcluster.crd.yaml
  deploy/bundle/manifests/cephobjectstore.crd.yaml
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/bundle/manifests/storagecluster.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectstores.yaml
  deploy/csv-templates/rook-csv.yaml.in
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/labels.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/object.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#1783 Updates annotation to disable features in Console
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1791 Set CSI_ENABLE_METADATA by default false
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved
