Repository red-hat-storage/ocs-operator, pull requests merged in 2022-03, with the labels that each got.

#1563 uninstall: delete CephCluster at the start of uninstall
  controllers/storagecluster/uninstall_reconciler.go
  controllers/storagecluster/uninstall_reconciler_test.go
Labels: lgtm, approved

#1568 Add default toleration to rbd-mirror pod
  controllers/defaults/placements.go
  controllers/storagecluster/cephrbdmirrors.go
Labels: lgtm, approved, Bug

#1460 unitTests: Add tests for ocs to ocs provider side code
  controllers/storagecluster/provider_server_test.go
  controllers/storagecluster/uninstall_reconciler_test.go
Labels: lgtm, approved

#1574 validate correct cephUserType annotation
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#1576 must-gather: add output for desc vrc
  must-gather/collection-scripts/gather_clusterscoped_resources
Labels: lgtm, approved

#1562 hack: add tools for working with consumer onboarding tickets
  .gitignore
  hack/ticketgen/ticketcheck.go
  hack/ticketgen/ticketcheck.sh
  hack/ticketgen/ticketgen.sh
Labels: lgtm, approved

#1579 Package and CSV version updates
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  hack/common.sh
  version/version.go
Labels: lgtm, approved

#1580 Reset external resource cache when monitoring endpoints are not reachable
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#1583 ocs-to-ocs: correct the name of healthchecker cephclient
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#1586 controllers: correct logging of verifyNoStorageConsumerExist func
  controllers/storagecluster/uninstall_reconciler.go
  controllers/storagecluster/uninstall_reconciler_test.go
Labels: lgtm, approved

#1588 Bug 2062990:[release-4.10] controllers: correct logging of verifyNoStorageConsumerExist func
  controllers/storagecluster/uninstall_reconciler.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1587 add StorageClassClaim CR and controller
  api/v1alpha1/storageclassclaim_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclassclaims.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storageclassclaims.yaml
  config/crd/patches/webhook_in_storageclassclaims.yaml
  config/rbac/role.yaml
  config/rbac/storageclassclaim_editor_role.yaml
  config/rbac/storageclassclaim_viewer_role.yaml
  config/samples/ocs_v1alpha1_storageclassclaim.yaml
  controllers/storageclassclaim/storageclassclaim_controller.go
  controllers/storagecluster/external_ocs.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/reconcile.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/bundle/manifests/storageclassclaim.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclassclaims.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  main.go
Labels: lgtm, approved

#1584 ocs to ocs: add AcknowledgeOnboarding service
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  controllers/storagecluster/external_ocs.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/reconcile.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/status.go
  deploy/bundle/manifests/storageconsumer.crd.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  services/provider/client/client.go
  services/provider/pb/provider.pb.go
  services/provider/pb/provider_grpc.pb.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
Labels: lgtm, approved

#1590 ocs to ocs: fix onboarding acknowledegement
  controllers/storagecluster/external_ocs.go
  controllers/storagecluster/reconcile.go
  services/provider/server/consumer.go
  services/provider/server/server.go
Labels: lgtm, approved

#1592 Delete cephRBDMirror while deleting StorageCluster
  controllers/storagecluster/uninstall_reconciler.go
Labels: lgtm, approved

#1443 Add check to verify the presence of openshift-dr-system ns
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved

#1577 must-gather: adds output for crds of managed services
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved

#1598 Bug 2066997: [release-4.9] set upgrade conditions in external mode deployment
  controllers/storagecluster/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1597 set upgrade conditions to true in external mode deployment
  controllers/storagecluster/reconcile.go
Labels: lgtm, approved

#1595 ocs: add RPC calls for storageclassClaim
  services/provider/client/client.go
  services/provider/pb/provider.pb.go
  services/provider/pb/provider_grpc.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
Labels: lgtm, approved

#1605 implement FulfillStorageClassClaim and RevokeStorageClassClaim RPC call
  services/provider/client/client.go
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  services/provider/server/storageclaim.go
  services/provider/server/storageclaim_test.go
Labels: lgtm, approved
