Repository red-hat-storage/ocs-operator, pull requests merged in 2023-11, with the labels that each got.

#2244 Syncing latest changes from main for ocs-operator
  .github/workflows/conf/commitlintrc.json
  .github/workflows/ocs-operator-ci.yaml
  controllers/util/clusters.go
  controllers/util/util.go
Labels: lgtm, approved

#2245 Use exact ceph image version v17.2.6 instead of v17
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: lgtm, approved

#2231 Altering restrictions for StorageProfile API
  api/v1/storagecluster_types.go
  api/v1/storageprofile_types.go
  config/crd/bases/ocs.openshift.io_storageprofiles.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageprofiles.yaml
  deploy/ocs-operator/manifests/storageprofile.crd.yaml
Labels: lgtm, approved, ok-to-test

#2246 Remove Noobaa manifests & crds integration from OCS operator
  deploy/csv-templates/crds/noobaa/noobaa-crd.yaml
  deploy/csv-templates/noobaa-csv.yaml
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/source-manifests.sh
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2252 Syncing latest changes from main for ocs-operator
  deploy/csv-templates/crds/noobaa/noobaa-crd.yaml
  deploy/csv-templates/noobaa-csv.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/source-manifests.sh
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2248 Refactor isActiveStorageCluster to handle internal and external clusters
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/storagecluster_controller_test.go
Labels: lgtm, approved

#2251 Bug 2247743: Validate client supplied data only when set
  services/provider/server/server.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#2259 Update ocs operator version to v4.15.0
  README.md
  catalog/index.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  version/version.go
Labels: lgtm, approved

#2225 Ran pending make command and fix obc alerts issue
  config/rbac/exporter-role.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/deploy/rbac.yaml
  metrics/internal/collectors/object-bucket.go
Labels: lgtm, approved

#2261 Bug 2248625: Simplify version comparison for StorageClient Alerts
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/storage-client.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#2263 Revert "Delete a template job after the job gets completed"
  controllers/storagecluster/job_templates.go
Labels: lgtm, approved

#2181 Bug 2235571:[release-4.13] Fix upgrade issue when storagecluster is not present
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/ocs_operator_config.go
  controllers/util/k8sutil.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#2264 StorageCluster spec change and updating Noobaa reconcile
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/cosi_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/namespacestore_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/container-object-storage-interface-api/apis/bucket_info.go
Labels: lgtm, approved

#2247 allow migration of osds to bluestore-rdr
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved

#2274 Bug fix of failed data pool retreival
  controllers/storageclassrequest/storageclassrequest_controller.go
Labels: lgtm, approved

#2275 Skip creation of Virtualization SC in Provider Mode
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#2276 Bug 2248449: Fusion HCI integration changes for OCS operator [4.14 Backport]
  api/v1/storagecluster_types.go
  api/v1/storageprofile_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  config/crd/bases/ocs.openshift.io_storageprofiles.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storageprofiles.yaml
  config/crd/patches/webhook_in_storageprofiles.yaml
  config/rbac/storageprofile_editor_role.yaml
  config/rbac/storageprofile_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/ocs_v1_storageprofile.yaml
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageprofiles.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  deploy/ocs-operator/manifests/storageprofile.crd.yaml
  go.mod
  go.sum
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/internal/collectors/storageconsumer.go
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/alerts/storage-client.libsonnet
  metrics/mixin/config.libsonnet
  services/provider/client/client.go
  services/provider/clientstatus/status.go
  services/provider/pb/provider.pb.go
  services/provider/pb/storageclient_status.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/provider/server/server_test.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_securitycontextconstraints.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2271 cephfs: add creation of csi default svg
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
Labels: lgtm, approved

#2257 Add & Change options to provide custom MgrCount, MonCount & no. of CephFSActiveMDS, ObjectStoreGateways
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/defaults/defaults.go
  controllers/defaults/placements.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/cephobjectstores_test.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/placement_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved

#2242 Add resource profiles to control the resourceRequirements for ceph pods
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/defaults/resources.go
  controllers/defaults/utils.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved

#2256 Watch for specific set of namespaces using the client
  main.go
Labels: lgtm, approved

#2284 monitoring: Update alert annotation runbook_url
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#2267 external: create rados namspace for external cluster
  config/rbac/role.yaml
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2289 ensure interal cluster is only allowed in the OperatorNamespace
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/storagecluster_controller_test.go
  main.go
Labels: lgtm, approved

#2285 Fix the condition for noobaa reconcile
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved

#2290 Consider all storage clusters status for operator upgradability
  controllers/storagecluster/reconcile.go
  controllers/util/clusters.go
Labels: lgtm, approved
