Repository red-hat-storage/ocs-operator, pull requests merged in 2023-10, with the labels that each got.

#2196 Bug 2234664:[release-4.13] When NFS is enabled on the storagecluster pass ROOK_CSI_ENABLE_NFS: true
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/ocs_operator_config.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2200 Correcting the job names in prometheus metrics
  controllers/storagecluster/prometheus/localcephrules.yaml
  metrics/mixin/rules/rules.libsonnet
Labels: lgtm, approved

#2178 Bug 2237370:[release-4.12] external: update objectstore with hostname if rgw-endpoint is hostname
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/external_resources_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2202 Bug 2241113: [release-4.12]must-gather: collect events in a sorted order
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2203 Bug 2234735:[release-4.14] Revert "support osd migration in RDR customers
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2205 Fix typo in metrics code comment
  metrics/internal/collectors/registry.go
Labels: lgtm, approved

#2212 Syncing latest changes from main for ocs-operator
  metrics/internal/collectors/registry.go
Labels: lgtm, approved

#2213 Add default virtualization storage class annotation
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved, ok-to-test

#2204 Transforms StorageProfile array into a set of CRs
  api/v1/storagecluster_types.go
  api/v1/storageprofile_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  config/crd/bases/ocs.openshift.io_storageprofiles.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storageprofiles.yaml
  config/crd/patches/webhook_in_storageprofiles.yaml
  config/rbac/storageprofile_editor_role.yaml
  config/rbac/storageprofile_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/ocs_v1_storageprofile.yaml
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/storagecluster_controller.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageprofiles.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/manifests/storageprofile.crd.yaml
Labels: lgtm, approved, ok-to-test

#2215 Add new field 'monCount' in storagecluster CR
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved

#2223 Fix Provisioner Namespace Configuration
  controllers/storagecluster/generate.go
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#2222 Provide a flag to mark rbd storageclass as the default for the cluster
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/storageclasses.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved

#2232 Use context passed via handler instead of reconciler's context
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved

#2237 [release-4.12] Fix typo in metrics code comment
  metrics/internal/collectors/registry.go
Labels: lgtm, approved, bugzilla/valid-bug

#2241 Add commitlint in the github workflows to check the commit messages
  .github/workflows/conf/commitlintrc.json
  .github/workflows/ocs-operator-ci.yaml
Labels: lgtm, approved

#2195 store client information on storageconsumer status
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  services/provider/client/client.go
  services/provider/clientstatus/status.go
  services/provider/pb/provider.pb.go
  services/provider/pb/storageclient_status.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2228 Bug 2244426: check for existing CephBlockPool for given consumer/profile in StorageClassRequest
  api/v1/storageprofile_types.go
  config/samples/ocs_v1_storageprofile.yaml
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, bugzilla/severity-unspecified
