Repository red-hat-storage/ocs-operator, pull requests merged in 2023-03, with the labels that each got.

#1952 remove OCSInitialization controller ref from ocs-operator-config cm
  controllers/storagecluster/ocs_operator_config.go
Labels: lgtm, approved

#1960 Image Changes, Codespell Fix, Use of ICS name, Functest Removal
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  functests/must-gather/must_gather_test.go
  hack/common.sh
  hack/generate-unified-csv.sh
  hack/install-noobaa-operator.sh
  hack/source-manifests.sh
  pkg/deploy-manager/subscription.go
Labels: lgtm, approved

#1959 Reconcile the job templates so it is in sync with the latest changes
  controllers/storagecluster/job_templates.go
Labels: lgtm, approved

#1966 Bug 2174335:[release-4.12] remove namespace deps from the bundle
  config/rbac/exporter-role.yaml
  config/rbac/exporter-role_binding.yaml
  config/rbac/kustomization.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/exporter-role.yaml
  deploy/ocs-operator/manifests/exporter-role_binding.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/rook-monitor-mgr-role_binding.yaml
  deploy/ocs-operator/manifests/rook-monitor-role_binding.yaml
  hack/source-manifests.sh
  must-gather/README.md
  pkg/deploy-manager/subscription.go
  rbac/rook-monitor-mgr-role_binding.yaml
  rbac/rook-monitor-role_binding.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1956 Bug 2176357: [release-4.9] Moving the defaults for rookceph operator from configmap to csv
  controllers/ocsinitialization/ocsinitialization_controller.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1957 Bug 2176356: [release-4.10] Moving the defaults for rookceph operator from configmap to csv
  controllers/ocsinitialization/ocsinitialization_controller.go
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1976 ms: add subvolumegroupname to GetStorageClassClaimConfig RPC
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved
