Repository red-hat-storage/ocs-operator, pull requests merged in 2023-12, with the labels that each got.

#2295 Add new `.spec.CSI` field in storagecluster
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/ocs_operator_config.go
  controllers/storagecluster/ocs_operator_config_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
  deploy/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/ocs-operator/manifests/cephfilesystemsubvolumegroup.crd.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/go-jose/go-jose/v3/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v3/symmetric.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/github.com/rook/rook/pkg/client/clientset/versioned/typed/ceph.rook.io/v1/ceph.rook.io_client.go
  vendor/github.com/rook/rook/pkg/client/clientset/versioned/typed/ceph.rook.io/v1/cephcosidriver.go
  vendor/github.com/rook/rook/pkg/client/clientset/versioned/typed/ceph.rook.io/v1/generated_expansion.go
  vendor/github.com/rook/rook/pkg/client/listers/ceph.rook.io/v1/cephcosidriver.go
  vendor/github.com/rook/rook/pkg/client/listers/ceph.rook.io/v1/expansion_generated.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved

#2297 Add StorageCluster count and namespace to ClusterClaim
  controllers/storagecluster/clusterclaims.go
Labels: lgtm, approved

#2240 Separate ceph toolbox from ocsinitialization
  api/v1/ocsinitialization_types.go
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/cephtoolbox.go
  controllers/storagecluster/cephtoolbox_test.go
  controllers/storagecluster/storagecluster_controller.go
  functests/ocs/ceph_tools_test.go
Labels: lgtm, approved

#2283 Ensure resource profile changes are applied correctly without any issues
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/resourceprofile.go
  controllers/util/k8sutil.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved

#2260 monitoring: Add new alert CephMonLowNumber
  controllers/storagecluster/prometheus/localcephrules.yaml
  metrics/internal/collectors/ceph-cluster.go
  metrics/internal/collectors/ceph-cluster_test.go
Labels: lgtm, approved

#2229 monitoring: runbooks documentation files
  metrics/mixin/README.md
Labels: lgtm, approved

#2303 fix: do not return after updating conditions if there is no error
  controllers/storagecluster/reconcile.go
Labels: lgtm, approved

#2299 Skip ensureRbdMirrorDebugLogging job in case of external storage cluster
  controllers/storagecluster/reconcile.go
Labels: lgtm, approved

#2305 Onboard clients only if they are on same version as provider
  services/provider/client/client.go
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
Labels: lgtm, approved

#2309 add alert for mds cache over use
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/alerts/perf.libsonnet
  metrics/mixin/config.libsonnet
Labels: lgtm, approved

#2298 Ignore storage clusters that meet specific criteria
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/util/clusters.go
Labels: lgtm, approved

#2306 Add alerts for high osd cpu usage
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/perf.libsonnet
  metrics/mixin/config.libsonnet
Labels: lgtm, approved

#2307 Alert user if ceph metadata server is consuming cpu at threshold point.
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/perf.libsonnet
  metrics/mixin/config.libsonnet
Labels: lgtm, approved

#2313 CSV changes to remove ocs metrics exporter deployment
  config/rbac/exporter-role.yaml
  config/rbac/exporter-role_binding.yaml
  config/rbac/kustomization.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/install-ocs.sh
  hack/source-manifests.sh
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2302 Add runbook_url annotation in alerts
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/README.md
  metrics/mixin/alerts/blocklist.libsonnet
  metrics/mixin/alerts/encryption.libsonnet
  metrics/mixin/alerts/mirroring.libsonnet
Labels: lgtm, approved

#2300 Add ClusterClaim for RDR optimizations and refactor getOsdCount()
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/clusterclaims.go
  controllers/storagecluster/resourceprofile.go
Labels: lgtm, approved

#2316 add runbooks_url to alerts
  controllers/storagecluster/prometheus/localcephrules.yaml
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/mirroring.libsonnet
  metrics/mixin/alerts/obc.libsonnet
Labels: lgtm, approved

#2293 Enable MetricsExporter and PrometheusRules on each StorageCluster namespaces
  config/rbac/role.yaml
  controllers/storagecluster/exporter.go
  controllers/storagecluster/prometheus.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/internal/collectors/ceph-block-pool.go
  metrics/internal/collectors/ceph-cluster.go
  metrics/internal/collectors/ceph-object-store.go
  metrics/internal/collectors/cluster-advance-feature-use.go
  metrics/internal/collectors/registry.go
  metrics/internal/collectors/storage-cluster.go
  metrics/internal/collectors/storageconsumer.go
  metrics/mixin/alerts/blocklist.libsonnet
  metrics/mixin/alerts/encryption-external.libsonnet
  metrics/mixin/alerts/encryption.libsonnet
  metrics/mixin/alerts/mirroring.libsonnet
  metrics/mixin/alerts/obc.libsonnet
  metrics/mixin/alerts/services-external.libsonnet
  metrics/mixin/alerts/services.libsonnet
  metrics/mixin/alerts/storage-client.libsonnet
Labels: lgtm, approved

#2319 upgraded golangci-lint to 1.54.2
  .github/workflows/ocs-operator-ci.yaml
  controllers/storagecluster/backingstorageclasses.go
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/cephconfig.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/cephnfs_test.go
  controllers/storagecluster/cephobjectstores_test.go
  controllers/storagecluster/cephobjectstoreusers_test.go
  controllers/storagecluster/cephrbdmirrors_test.go
  controllers/storagecluster/exporter.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/job_templates.go
  controllers/storagecluster/operator_conditions_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/routes_test.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/topology.go
  controllers/storagecluster/uninstall_reconciler.go
  controllers/storagecluster/uninstall_reconciler_test.go
  controllers/storagecluster/volumesnapshotterclasses.go
  controllers/storagecluster/volumesnapshotterclasses_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  hack/common.sh
  metrics/internal/cache/ceph-blocklist.go
  metrics/internal/cache/pv.go
  metrics/internal/cache/rbd-mirror.go
  metrics/internal/collectors/cluster-advance-feature-use.go
  metrics/internal/collectors/rbd-mirror.go
  metrics/internal/collectors/registry.go
  metrics/internal/collectors/storageconsumer.go
  pkg/deploy-manager/storagecluster.go
  services/provider/server/server.go
  services/provider/server/server_test.go
  services/provider/server/storageclassrequest.go
Labels: lgtm, approved

#2322 Added permissions to resources for metrics exporter
  controllers/storagecluster/exporter.go
  metrics/internal/cache/pv.go
  metrics/internal/collectors/ceph-block-pool.go
Labels: lgtm, approved

#2325 Changed alerts queries to support multicluster mode
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/blocklist.libsonnet
  metrics/mixin/alerts/mirroring.libsonnet
  metrics/mixin/alerts/obc.libsonnet
Labels: lgtm, approved

#2334 revert go workspace support
  .gitignore
  go.work
  go.work.sum
Labels: lgtm, approved

#2337 [release-4.13] Use exact ceph image version v17.2.6 instead of v17
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: lgtm, approved, bugzilla/valid-bug

#2338 [release-4.12] Use exact ceph image version v17.2.6 instead of v17
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: lgtm, approved, bugzilla/valid-bug

#2335 [release-4.12] update the catalog image to point to 4.12 catalog
  hack/install-noobaa-operator.sh
Labels: lgtm, approved, bugzilla/valid-bug

#2301 Token generation for prov/consumer mode
  Dockerfile
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  controllers/storagecluster/storagecluster_controller.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-binding.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-role.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-sa.yaml
  onboarding/main.go
  rbac/onboarding-secret-generator-binding.yaml
  rbac/onboarding-secret-generator-role.yaml
  rbac/onboarding-secret-generator-sa.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2314 Revert "Merge pull request #2305 from leelavg/5072-onboard"
  services/provider/client/client.go
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
Labels: lgtm, approved

#2311 Stop provider upgrade if clients version is lagging
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved

#2323 Added network configuration setting for CephObjectStore
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephobjectstores.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved, ok-to-test

#2341 skip checking osd store type for external clusters
  controllers/storagecluster/clusterclaims.go
Labels: lgtm, approved

#2347 [fusion-hci-4.14] added creation of job template
  Dockerfile
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  controllers/storagecluster/storagecluster_controller.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-binding.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-role.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-sa.yaml
  onboarding/main.go
  rbac/onboarding-secret-generator-binding.yaml
  rbac/onboarding-secret-generator-role.yaml
  rbac/onboarding-secret-generator-sa.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2348 [fusion-hci-4.14] Stop provider upgrade if client gets behind
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved

#2253 Bug 2247963: [Release 4.14] fix obc label alerts issue
  config/rbac/exporter-role.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/deploy/rbac.yaml
  metrics/internal/collectors/object-bucket.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2349 [fusion-hci-4.14] Added network configuration setting for CephObjectStore
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephobjectstores.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved

#2350 [fusion-hci-4.14] Onboard clients only if they are on same version as provider - 2
  services/provider/client/client.go
  services/provider/clientstatus/status.go
  services/provider/interfaces/interfaces.go
  services/provider/pb/provider.pb.go
  services/provider/pb/storageclient.go
  services/provider/pb/storageclient_status.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
Labels: lgtm, approved
