Repository red-hat-storage/ocs-operator, pull requests merged in 2023-04, with the labels that each got.

#1987 [release-4.11] Fix ginko errors in the openshift-ci
  hack/build-functest.sh
Labels: lgtm

#1988 Reconcile the clusterClaim spec values to keep the values in sync
  controllers/storagecluster/clusterclaims.go
Labels: lgtm, approved

#1993 Don't require msgr2 port for provider/consumer clusters
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/ocs_operator_config.go
Labels: lgtm, approved

#1996 For provider/consumer cluster don't require msgr2 & don't allow encryption or compression
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#1998 Bug 2184666: [release-4.13] Rook api & image version change to v1.11.3
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephnfses.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectstores.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/ics-operator/manifests/cephcluster.crd.yaml
  deploy/ics-operator/manifests/cephnfs.crd.yaml
  deploy/ics-operator/manifests/cephobjectstore.crd.yaml
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/ocs-operator/manifests/cephnfs.crd.yaml
  deploy/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/go-openapi/errors/.golangci.yml
  vendor/github.com/go-openapi/errors/README.md
  vendor/github.com/go-openapi/errors/api.go
  vendor/github.com/go-openapi/errors/headers.go
  vendor/github.com/go-openapi/errors/middleware.go
  vendor/github.com/go-openapi/errors/parsing.go
  vendor/github.com/go-openapi/errors/schema.go
  vendor/github.com/hashicorp/vault/LICENSE
  vendor/github.com/hashicorp/vault/command/agent/auth/auth.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/annotations.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/keys.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/labels.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/nfs.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/object.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1999 Correct storage cluster request queuing in OCSInitialization
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved

#1972 do not watch noobaa CRs if SKIP_NOOBAA_CRD_WATCH is set to true
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved

#1968 Allow ignoring RBDMirror CR
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephrbdmirrors.go
  deploy/csv-templates/crds/ics/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ics-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved

#2005 upgrade rook api to pre-release 1.11.4
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ics/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/ics-operator/manifests/cephcluster.crd.yaml
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ics-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2006 Bug 2186225: [release-4.13] upgrade rook api to pre-release 1.11.4
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ics/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/ics-operator/manifests/cephcluster.crd.yaml
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ics-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2010 Refactor GetNetworkSpec to handle different network connection & Pass appropriate options for all the cases of Network Spec
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/ocs_operator_config.go
Labels: lgtm, approved

#2012 update rook to 1.11.4
  deploy/csv-templates/rook-csv.yaml.in
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/modules.txt
Labels: lgtm, approved

#2014 make the description for Cluster Object Store more specific
  metrics/mixin/alerts/services.libsonnet
Labels: lgtm, approved

#2008 Change any embedded namespace to current one
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved

#2004 Added 'namespace' tag to queries
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#2018 Bug 2185190:[release-4.12] Correct storage cluster request queuing in OCSInitialization
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#2022 Bug 2185725:[release-4.12] do not watch noobaa CRs if SKIP_NOOBAA_CRD_WATCH is set to true
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2024 Use ms_mode=legacy instead of blank value, add network spec to external mode ceph cluster, add unit tests
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/ocs_operator_config.go
Labels: lgtm, approved

#2025 ms: fix label on storageclassrequest cr
  services/provider/server/storageclassrequest.go
Labels: lgtm, approved

#2032 Exporter fixes for StorageCluster and StorageClass metrics
  metrics/internal/collectors/cluster-advance-feature-use.go
  metrics/internal/collectors/ocs-client.go
  metrics/internal/collectors/storage-cluster.go
  metrics/internal/collectors/storageconsumer.go
Labels: lgtm, approved

#2031 Make metric code namespace agnostic
  metrics/internal/cache/ceph-blocklist.go
  metrics/internal/cache/pv.go
  metrics/internal/cache/rbd-mirror.go
Labels: lgtm, approved

#2034 Bug 2188228: [release-4.12] Exporter fixes for StorageCluster and StorageClass metrics
  metrics/internal/collectors/cluster-advance-feature-use.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2037 fix clusterclaim reconcile failure
  controllers/storagecluster/clusterclaims.go
  vendor/modules.txt
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/clientset.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/doc.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/scheme/doc.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/scheme/register.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1/cluster_client.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1/doc.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1/generated_expansion.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1/managedcluster.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/addonplacementscore.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/clusterclaim.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/doc.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/generated_expansion.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta1/cluster_client.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta1/doc.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta1/generated_expansion.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta1/managedclusterset.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta1/managedclustersetbinding.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta1/placement.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta1/placementdecision.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta2/cluster_client.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta2/doc.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta2/generated_expansion.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta2/managedclusterset.go
  vendor/open-cluster-management.io/api/client/cluster/clientset/versioned/typed/cluster/v1beta2/managedclustersetbinding.go
  vendor/open-cluster-management.io/api/cluster/v1/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1/doc.go
  vendor/open-cluster-management.io/api/cluster/v1/register.go
  vendor/open-cluster-management.io/api/cluster/v1/types.go
  vendor/open-cluster-management.io/api/cluster/v1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1/zz_generated.swagger_doc_generated.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/0000_00_clusters.open-cluster-management.io_managedclustersets.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1beta1/0000_01_clusters.open-cluster-management.io_managedclustersetbindings.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1beta1/0000_02_clusters.open-cluster-management.io_placements.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1beta1/0000_03_clusters.open-cluster-management.io_placementdecisions.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1beta1/doc.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/helpers.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/register.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/types_managedclusterset.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/types_managedclustersetbinding.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/types_placement.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/types_placementdecision.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/open-cluster-management.io/api/cluster/v1beta2/0000_00_clusters.open-cluster-management.io_managedclustersets.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1beta2/0000_01_clusters.open-cluster-management.io_managedclustersetbindings.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1beta2/doc.go
  vendor/open-cluster-management.io/api/cluster/v1beta2/helpers.go
  vendor/open-cluster-management.io/api/cluster/v1beta2/register.go
  vendor/open-cluster-management.io/api/cluster/v1beta2/types_managedclusterset.go
  vendor/open-cluster-management.io/api/cluster/v1beta2/types_managedclustersetbinding.go
  vendor/open-cluster-management.io/api/cluster/v1beta2/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1beta2/zz_generated.swagger_doc_generated.go
Labels: lgtm, approved

#2039 fix logging for the storageclassclaim in server
  services/provider/server/server.go
Labels: lgtm, approved
