Repository red-hat-storage/ocs-operator, pull requests merged in 2023-08, with the labels that each got.

#2118 Move autoscale into DesiredState method for upgrade
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved

#2121 Fix CVE-2023-3978 by upgrading golang.org/x/net to v0.14.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_loong64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/text/language/match.go
  vendor/modules.txt
Labels: lgtm, approved

#2056 Use `IfNotPresent` pull policy for images pulled by digest
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, ok-to-test

#2073 add topology mode annotation rgw service
  controllers/storagecluster/cephobjectstores.go
Labels: lgtm, approved

#2122 Delete completed template job so no need to delete it when rerunning the job
  controllers/storagecluster/job_templates.go
Labels: lgtm, approved

#2128 Add multus related annotations to ceph toolbox
  controllers/storagecluster/cephtoolbox.go
Labels: lgtm, approved

#2138 fix provAPIServer when NodePort svc is stuck waiting for lb endpoint
  controllers/storagecluster/provider_server.go
Labels: lgtm, approved

#2108 Fix KMSServerConnectionAlert stays even when KMS connection is re-established
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#2143 Incorporate the CSI_TOPOLOGY_DOMAIN_LABELS key into the configmap
  controllers/storagecluster/ocs_operator_config.go
Labels: lgtm, approved

#2147 Bug 2232502:[release-4.14] Update Rook version to v1.12.1
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2148 set priority class for csi pods
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2130 design doc to use optimized OSD store
  docs/design/disaster-recovery-optimization.md
Labels: lgtm, approved

#2132 Use optimized osd store for new clusters
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved

#2162 support using bluestore-rdr for RDR customers
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#2157 When NFS is enabled on the storagecluster pass ROOK_CSI_ENABLE_NFS: true
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/ocs_operator_config.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2166 Bug 2234658:[release-4.13] update k8s.io/client-go to v0.26.4 for ocp 4.14
  .github/workflows/ocs-operator-ci.yaml
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1alpha1/generated.proto
  vendor/k8s.io/api/resource/v1alpha1/types.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2123 Avoid wrong detection of disk type, such as HDD instead of SSD on vSAN
  controllers/storagecluster/cephconfig.go
Labels: lgtm, approved
