Repository red-hat-storage/ocs-operator, pull requests merged in 2023-07, with the labels that each got.

#2069 Bug 2211592: [release-4.12] Always update the template parameters & objects to keep it up-to-date
  controllers/storagecluster/job_templates.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2071 Bug 2211595: [release-4.10] Always update the template parameters & objects to keep it up-to-date
  controllers/storagecluster/job_templates.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2070 Bug 2211594: [release-4.11] Always update the template parameters & objects to keep it up-to-date
  controllers/storagecluster/job_templates.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2029 enable single node cluster deployment
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/topology.go
  controllers/util/k8sutil.go
  deploy/single-node-storagecluster.yaml
Labels: lgtm, approved

#2088 Remove left over fusion related files
  deploy/csv-templates/crds/ics/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/ics-operator.csv.yaml.in
  deploy/ics-operator/manifests/cephcluster.crd.yaml
  deploy/ics-operator/manifests/cephnfs.crd.yaml
  deploy/ics-operator/manifests/cephobjectstoreuser.crd.yaml
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ics-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved

#2090 Update operator-sdk version to v1.25.4 from v1.20.0
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  deploy/Dockerfile
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/metadata/annotations.yaml
  hack/operator-sdk-common.sh
Labels: lgtm, approved

#2092 Fixes in make target for controller-gen, kustomize, install-ocs & install-noobaa
  Makefile
  hack/install-noobaa.sh
  hack/install-ocs.sh
Labels: lgtm, approved

#2091 noobaa autoscaler changes, new properties added
  controllers/storagecluster/noobaa_system_reconciler.go
  go.mod
  go.sum
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2086 update the metric for rgw_health_status
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/internal/collectors/ceph-object-store.go
  metrics/internal/collectors/ceph-object-store_test.go
  metrics/mixin/alerts/services-external.libsonnet
  metrics/mixin/alerts/services.libsonnet
Labels: lgtm, approved

#2094 feat: support ocs encrypted volume with cross-ns smart cloning in CNV
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
Labels: lgtm, approved

#2063 Bug 2210475: [release-4.12] cleanup to resolve jq: command not found error
  must-gather/collection-scripts/gather_ceph_resources
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2096 Update ocs-operator & metrics-exporter dockerfiles & build process
  Dockerfile
  Makefile
  build/Dockerfile
  hack/build-container.sh
  hack/build-metrics-exporter.sh
  hack/build-operator.sh
  metrics/Dockerfile
Labels: lgtm, approved

#2097 Improvements to file based catalog generation process
  .gitignore
  Dockerfile.catalog
  catalog/index.yaml
  catalog/noobaa-bundle.yaml
  catalog/ocs-bundle.yaml
  hack/build-operator-catalog.sh
  hack/ensure-opm.sh
Labels: lgtm, approved

#2098 Improve the bundle build process for the operator
  Dockerfile.bundle
  Makefile
  hack/build-operator-bundle.sh
  hack/source-manifests.sh
Labels: lgtm, approved

#2064 Bug 2209254: [release-4.11] Fix encryption enablement in Noobaa
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2107 Add back gen-release-csv make target as it is being used for ds build
  Makefile
Labels: lgtm, approved

#2105 Use new module path for ocs in ldflags
  Dockerfile
  hack/build-functest.sh
  hack/build-metrics-exporter.sh
  hack/build-operator.sh
  hack/common.sh
  hack/generate-unified-csv.sh
  hack/unit-test.sh
  metrics/Dockerfile
Labels: lgtm, approved

#2110 Update go version to 1.20 in go.mod & in github workflows
  .github/workflows/ocs-operator-ci.yaml
  go.mod
Labels: lgtm, approved

#2109 Update ocs operator version to v4.14.0
  README.md
  catalog/index.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  version/version.go
Labels: lgtm, approved

#2083 Remove quota while creating cephblockpool and remove capacity field from StorageConsumer CR as it is no longer used
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/internal/collectors/storageconsumer.go
  services/provider/client/client.go
  services/provider/common/mock.go
  services/provider/pb/provider.pb.go
  services/provider/pb/provider_grpc.pb.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/provider/server/server_mock.go
Labels: lgtm, approved

#2114 Removing capacity feature from the storageconsumer CR
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/internal/collectors/storageconsumer.go
  services/provider/client/client.go
  services/provider/common/mock.go
  services/provider/pb/provider.pb.go
  services/provider/pb/provider_grpc.pb.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/provider/server/server_mock.go
Labels: approved

#2115 update rook image
  deploy/csv-templates/rook-csv.yaml.in
  deploy/ocs-operator/manifests/cephcosidriver.crd.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: lgtm, approved

#2116 Add support for configuring OSD store type
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/storage.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2117 Toggle between OCS Provider Server Service Type
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: approved
