Repository red-hat-storage/ocs-operator, pull requests merged in 2023-02, with the labels that each got.

#1927 Update fusion bundle
  config/manifests/fcs-operator/bases/fcs-operator.clusterserviceversion.yaml
  config/manifests/ics-operator/bases/ocs-operator.clusterserviceversion.yaml
  config/manifests/ics-operator/kustomization.yaml
  deploy/csv-templates/crds/ics/ocs.openshift.io_ocsinitializations.yaml
  deploy/csv-templates/crds/ics/ocs.openshift.io_storageclassclaims.yaml
  deploy/csv-templates/crds/ics/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ics/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/fcs-operator.csv.yaml.in
  deploy/csv-templates/ics-operator.csv.yaml.in
  deploy/ics-operator/manifests/ceph-conf.yaml
  deploy/ics-operator/manifests/cephblockpool.crd.yaml
  deploy/ics-operator/manifests/cephblockpoolradosnamespace.crd.yaml
  deploy/ics-operator/manifests/cephbucketnotification.crd.yaml
  deploy/ics-operator/manifests/cephbuckettopic.crd.yaml
  deploy/ics-operator/manifests/cephclient.crd.yaml
  deploy/ics-operator/manifests/cephcluster.crd.yaml
  deploy/ics-operator/manifests/cephfilesystem.crd.yaml
  deploy/ics-operator/manifests/cephfilesystemmirror.crd.yaml
  deploy/ics-operator/manifests/cephfilesystemsubvolumegroup.crd.yaml
  deploy/ics-operator/manifests/cephnfs.crd.yaml
  deploy/ics-operator/manifests/cephobjectrealm.crd.yaml
  deploy/ics-operator/manifests/cephobjectstore.crd.yaml
  deploy/ics-operator/manifests/cephobjectstoreuser.crd.yaml
  deploy/ics-operator/manifests/cephobjectzone.crd.yaml
  deploy/ics-operator/manifests/cephobjectzonegroup.crd.yaml
  deploy/ics-operator/manifests/cephrbdmirror.crd.yaml
  deploy/ics-operator/manifests/consumer-role.yaml
  deploy/ics-operator/manifests/consumer-role_binding.yaml
  deploy/ics-operator/manifests/consumer-sa.yaml
  deploy/ics-operator/manifests/exporter-service-role.yaml
  deploy/ics-operator/manifests/exporter-service-role_binding.yaml
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ics-operator/manifests/ocsinitialization.crd.yaml
  deploy/ics-operator/manifests/provider-role.yaml
  deploy/ics-operator/manifests/provider-role_binding.yaml
  deploy/ics-operator/manifests/provider-sa.yaml
  deploy/ics-operator/manifests/rook-metrics-role.yaml
  deploy/ics-operator/manifests/rook-metrics-role_binding.yaml
  deploy/ics-operator/manifests/rook-monitor-mgr-role.yaml
  deploy/ics-operator/manifests/rook-monitor-mgr-role_binding.yaml
  deploy/ics-operator/manifests/rook-monitor-role.yaml
  deploy/ics-operator/manifests/rook-monitor-role_binding.yaml
  deploy/ics-operator/manifests/storageclassclaim.crd.yaml
  deploy/ics-operator/manifests/storagecluster.crd.yaml
  deploy/ics-operator/manifests/storageconsumer.crd.yaml
  deploy/ics-operator/metadata/annotations.yaml
  deploy/ics.Dockerfile
  hack/build-operator-bundle.sh
  hack/common.sh
  hack/generate-unified-csv.sh
  hack/source-manifests.sh
  hack/verify-latest-csv.sh
  hack/verify-operator-bundle.sh
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1931 Bug 2165960:[release-4.12] add annotation to the CSV for disconnected env
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1932 Replace various clients in e2e test with a single client with required schemes
  functests/ocs/ceph_tools_test.go
  functests/ocs/data_validation_test.go
  functests/ocs/pvc_creation_test.go
  functests/ocs/storagecluster_creation_test.go
  pkg/deploy-manager/arbiter.go
  pkg/deploy-manager/common.go
  pkg/deploy-manager/config.go
  pkg/deploy-manager/storagecluster.go
  pkg/deploy-manager/subscription.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/groupversion_info.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/clientset.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/scheme/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/scheme/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/generated_expansion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/olmconfig.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/operatorcondition.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/operators_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/catalogsource.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/generated_expansion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/installplan.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/operators_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/subscription.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha2/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha2/generated_expansion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha2/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha2/operators_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v2/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v2/generated_expansion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v2/operatorcondition.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v2/operators_client.go
  vendor/modules.txt
Labels: lgtm, approved

#1929 must-gather: remove mustgather scripts
  Makefile
  hack/build-must-gather.sh
  hack/common.sh
  hack/dump-debug-info.sh
  hack/generate-latest-csv.sh
  must-gather/Dockerfile
  must-gather/OWNERS
  must-gather/README.md
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_common_ceph_resources
  must-gather/collection-scripts/gather_namespaced_resources
  must-gather/collection-scripts/gather_noobaa_resources
  must-gather/collection-scripts/post-uninstall.sh
  must-gather/collection-scripts/pre-install.sh
  must-gather/docs/Directory-Structure-Top-Level.png
  must-gather/functests/functests.sh
  must-gather/functests/integration/command_output_test.sh
  must-gather/templates/noobaa.template
  must-gather/templates/pod.template
Labels: lgtm, approved, 4.13-feature

#1934 e2e: Use new file based catalog, Create Noobaa sub, Fix broken Must gather path
  deploy/deploy-with-olm.yaml
  functests/common.go
  hack/build-functest.sh
  hack/functest.sh
  hack/gen-deployment-yaml.sh
  pkg/deploy-manager/subscription.go
Labels: lgtm, approved

#1935 do not use hardcoded ns for ocs-prometheus-rules
  controllers/storagecluster/prometheus.go
Labels: lgtm, approved, 4.13-feature

#1924 feat: enabled kubernetes auth for SC and SS
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#1897 Bug 2154164:[release-4.11] disable rook webhook
  deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, jira/valid-bug

#1938 Update CSV & Package versions to 4.13
  catalog/index.yaml
  deploy/Dockerfile
  deploy/csv-templates/ics-operator.csv.yaml.in
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ics.Dockerfile
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-master-appregistry.sh
  hack/generate-master-bundle.sh
  openshift-ci/Dockerfile.bundle
  openshift-ci/Dockerfile.bundle.master
  version/version.go
Labels: lgtm, approved

#1936 Pass which namespace the e2e functest uses to deploy the ocs operator in
  deploy/deploy-with-olm.yaml
  functests/config.go
  functests/ocs/ceph_tools_test.go
  functests/setup_teardown.go
  hack/cluster-deploy.sh
  hack/common.sh
  hack/functest.sh
  hack/gen-deployment-yaml.sh
  pkg/deploy-manager/config.go
  pkg/deploy-manager/storagecluster.go
  pkg/deploy-manager/subscription.go
  tools/cluster-deploy/cluster-deploy.go
Labels: lgtm, approved

#1939 cephcluster: add support for read affinity for RBD volumes
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/ocsinitialization/ocsoperator_config.go
  controllers/storagecluster/cephcluster.go
  controllers/util/k8sutil.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1944 Update to golang 1.19
  .ci-operator.yaml
  .github/workflows/ocs-operator-ci.yaml
  Dockerfile
  build/Dockerfile.build
  go.mod
  hack/golangci_lint.sh
  metrics/Dockerfile
Labels: lgtm, approved

#1915 rook is migrating to lastest operator-sdk
  deploy/csv-templates/crds/rook/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephblockpools.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephbucketnotifications.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephbuckettopics.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclients.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephfilesystemmirrors.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephfilesystems.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephnfses.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectrealms.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectstores.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectstoreusers.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectzonegroups.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectzones.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephrbdmirrors.yaml
  deploy/csv-templates/crds/rook/replication.storage.openshift.io_volumereplicationclasses.yaml
  deploy/csv-templates/crds/rook/replication.storage.openshift.io_volumereplications.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/ics-operator/manifests/cephbucketnotification.crd.yaml
  deploy/ics-operator/manifests/cephcluster.crd.yaml
  deploy/ics-operator/manifests/cephfilesystem.crd.yaml
  deploy/ics-operator/manifests/cephfilesystemmirror.crd.yaml
  deploy/ics-operator/manifests/cephnfs.crd.yaml
  deploy/ics-operator/manifests/cephobjectrealm.crd.yaml
  deploy/ics-operator/manifests/cephobjectstore.crd.yaml
  deploy/ics-operator/manifests/cephobjectzone.crd.yaml
  deploy/ics-operator/manifests/cephobjectzonegroup.crd.yaml
  deploy/ics-operator/manifests/cephrbdmirror.crd.yaml
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/cephbucketnotification.crd.yaml
  deploy/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/ocs-operator/manifests/cephfilesystem.crd.yaml
  deploy/ocs-operator/manifests/cephfilesystemmirror.crd.yaml
  deploy/ocs-operator/manifests/cephnfs.crd.yaml
  deploy/ocs-operator/manifests/cephobjectrealm.crd.yaml
  deploy/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/ocs-operator/manifests/cephobjectzone.crd.yaml
  deploy/ocs-operator/manifests/cephobjectzonegroup.crd.yaml
  deploy/ocs-operator/manifests/cephrbdmirror.crd.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/source-manifests.sh
Labels: lgtm, approved, 4.13-feature

#1942 Alwasy enable ceph msgrv2 port & pass kernel mount options to rook-ceph operator
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/ocs_operator_config.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#1922 expose seperate route for secure port in RGW
  controllers/storagecluster/routes.go
  controllers/storagecluster/routes_test.go
Labels: lgtm, approved

#1937 Add new metric for monitoring blocklisted RBD clients
  config/rbac/exporter-role.yaml
  deploy/csv-templates/ics-operator.csv.yaml.in
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/deploy/rbac.yaml
  metrics/internal/cache/ceph-blocklist.go
  metrics/internal/cache/pv.go
  metrics/internal/cache/rbd-mirror.go
  metrics/internal/collectors/ceph-blocklist.go
  metrics/internal/collectors/rbd-mirror.go
  metrics/internal/collectors/registry.go
  metrics/main.go
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/alerts/blocklist.libsonnet
  metrics/mixin/config.libsonnet
  metrics/mixin/rules/rules.libsonnet
Labels: lgtm, approved

#1951 chore: Update formatting in shell script
  hack/operator-sdk-common.sh
Labels: lgtm, approved

#1947 change the conditions when cephcluster is in connected state
  controllers/storagecluster/reconcile.go
  controllers/util/status.go
Labels: lgtm, approved

#1923 Add KMS alert
  config/rbac/exporter-role.yaml
  controllers/storagecluster/cephcluster.go
  deploy/csv-templates/ics-operator.csv.yaml.in
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/deploy/rbac.yaml
  metrics/internal/collectors/ocs-client.go
  metrics/internal/collectors/registry.go
  metrics/internal/collectors/storage-cluster.go
  metrics/mixin/alerts/alerts-external.libsonnet
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/alerts/encryption-external.libsonnet
  metrics/mixin/alerts/encryption.libsonnet
  metrics/mixin/alerts/obc.libsonnet
  metrics/mixin/config.libsonnet
Labels: lgtm, approved, ok-to-test, 4.13-feature
