Repository red-hat-storage/ocs-operator, pull requests merged in 2024-10, with the labels that each got.

#2831 Syncing latest changes from main for ocs-operator
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2745 Available CRDs check feature
  Dockerfile
  config/manager/manager.yaml
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/util/k8sutil.go
  controllers/util/predicates.go
  controllers/util/util.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/entrypoint.sh
  main.go
Labels: lgtm, approved

#2826 fix panic in provider server while onboarding
  services/provider/server/server.go
Labels: lgtm, approved

#2832 use a default backing store for noobaa acount
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#2835 Bug 2313515: Revert "Merge pull request #2679 from umangachapagain/metrics-secure"
  controllers/defaults/resources.go
  controllers/storagecluster/exporter.go
  controllers/storagecluster/storagecluster_controller.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  metrics/deploy/deployment.yaml
  metrics/deploy/kube-rbac-proxy-secret.yaml
  metrics/deploy/rbac.yaml
  metrics/deploy/scc.yaml
  metrics/deploy/service.yaml
  metrics/deploy/servicemonitor.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2839 Syncing latest changes from main for ocs-operator
  Dockerfile
  config/manager/manager.yaml
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/k8sutil.go
  controllers/util/predicates.go
  controllers/util/util.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/entrypoint.sh
  main.go
  services/provider/server/server.go
Labels: lgtm, approved

#2811 Bug 2313492: [release-4.14] Remove check of object type & return in enqueueStorageClusterRequest
  controllers/storagecluster/storagecluster_controller.go
  hack/build-functest.sh
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2697 Adding StorageQuotaUtilizationRatio field for storage consumer api
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  services/provider/api/interfaces/interfaces.go
  services/provider/api/provider.pb.go
  services/provider/api/storageclient.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/storageclient.go
Labels: lgtm, approved

#2845 Syncing latest changes from main for ocs-operator
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  services/provider/api/interfaces/interfaces.go
  services/provider/api/provider.pb.go
  services/provider/api/storageclient.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/storageclient.go
Labels: lgtm, approved

#2848 Reducing the core group privileges
  config/rbac/role.yaml
  controllers/storagecluster/reconcile.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2849 Syncing latest changes from main for ocs-operator
  config/rbac/role.yaml
  controllers/storagecluster/reconcile.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2851 Clear the affinity on Noobaa if it was set previously to handle upgrades
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved

#2853 change float32 to float64 in storageconsumer api
  api/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  services/provider/api/interfaces/interfaces.go
  services/provider/api/provider.pb.go
  services/provider/api/storageclient.go
  services/provider/proto/provider.proto
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/storageclient.go
Labels: lgtm, approved

#2847 controller: update the odf-info to include client identification info
  api/v1alpha1/odfinfoconfig.go
  controllers/storagecluster/odfinfoconfig.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
Labels: lgtm, approved

#2860 Add missing vendor changes
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/csi_options.go
Labels: lgtm, approved

#2837 Include Encryption In-Transit state as part of the desired state hash sent to clients
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2862 hack: run continuous patch for ocs-client-operator-config
  hack/install-ocs-operator.sh
Labels: lgtm, approved

#2841 Adjust Node Label Conditions Based on Full Label Name
  controllers/storagecluster/topology.go
Labels: lgtm, approved

#2864 Syncing latest changes from main for ocs-operator
  controllers/storagecluster/topology.go
  hack/install-ocs-operator.sh
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2867 Syncing latest changes from main for ocs-operator
  services/provider/api/client/client.go
  services/provider/api/provider.pb.go
  services/provider/api/provider_grpc.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/client/client.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider_grpc.pb.go
Labels: lgtm, approved

#2865 remove dependency of ocs-client-operator CRDs during manager setup
  catalog/index.yaml
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses_test.go
  controllers/storagecluster/storageclient.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/util/predicates.go
  deploy/deploy-with-olm.yaml
  hack/build-operator-catalog.sh
  hack/common.sh
  hack/install-ocs-operator.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/predicates.go
  pkg/deploy-manager/subscription.go
Labels: lgtm, approved

#2868 Syncing latest changes from main for ocs-operator
  catalog/index.yaml
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses_test.go
  controllers/storagecluster/storageclient.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/util/predicates.go
  deploy/deploy-with-olm.yaml
  hack/build-operator-catalog.sh
  hack/common.sh
  hack/install-ocs-operator.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/predicates.go
  pkg/deploy-manager/subscription.go
Labels: lgtm, approved
