Repository red-hat-storage/ocs-operator, pull requests merged in 2024-06, with the labels that each got.

#2651 install all operators within one script
  Makefile
  catalog/index.yaml
  hack/common.sh
  hack/install-ocs-operator.sh
Labels: lgtm, approved

#2650 Syncing latest changes from main for ocs-operator
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/exporter.go
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/annotations.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/keys.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/labels.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/scc.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/security.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2652 remove duplicate install scripts
  Makefile
  hack/common.sh
  hack/install-noobaa.sh
  hack/install-ocs-client.sh
  hack/install-ocs.sh
  hack/install-rook.sh
Labels: lgtm, approved

#2655 [MCG] Add support for deploying NooBaa operator SCC along with Rook SCCs
  controllers/ocsinitialization/sccs.go
  controllers/storagecluster/noobaa_system_reconciler.go
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/bundle/deploy.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test

#2656 Revert "use "upmap-read" as default balancer mode"
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/annotations.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/keys.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/labels.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/scc.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/security.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2615 Set deviceClasses to avoid replicated pool spreading PGs across all OSDs
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/generate.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#2662 Bug 2274175: [release-4.16] Set deviceClasses to avoid replicated pool spreading PGs across all OSDs
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/generate.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2658 Bug 2273923:[release-4.15] [MCG] add support for deploying NooBaa operator SCC along with Rook SCCs
  controllers/ocsinitialization/sccs.go
  go.mod
  go.sum
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/bundle/deploy.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug

#2629 Increase PV usage alert percentages
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#2666 Revert rgw vhost dnsnames feature
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephobjectstores.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2668 Adding storage quota field to spec of storage consumer
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
Labels: lgtm, approved

#2665 BUG 2292114: api: changed storageConsumer status fields to optional
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, bugzilla/severity-high

#2674 Bug 2273924:[release-4.14] [MCG] add support for deploying NooBaa operator SCC along with Rook SCCs
  controllers/ocsinitialization/sccs.go
  go.mod
  go.sum
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/cosi_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/namespacestore_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/bundle/deploy.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/doc.go
  vendor/modules.txt
  vendor/sigs.k8s.io/container-object-storage-interface-api/apis/bucket_info.go
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug
