Repository red-hat-storage/ocs-operator, pull requests merged in 2024-12, with the labels that each got.

#2915 controllers: watch for consumer annotation in mirroring controller
  controllers/mirroring/mirroring_controller.go
Labels: lgtm, approved

#2914 provider: send mirrorEnabled info for each client
  services/provider/api/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
Labels: lgtm, approved

#2902 DFBUGS-872: [release-4.17] server: saving quota in GiB instead GB
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2918 provider: fix ramen labels
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2911 controllers: fix dynamic crd predicate
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/util/predicates.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/predicates.go
Labels: lgtm, approved

#2923 controllers: read the storageclusterpeer name from annotation
  controllers/mirroring/mirroring_controller.go
Labels: lgtm, approved

#2919 DFBUGS-976: monitoring: mark mirroring enabled if spec.Mirroring is !nil
  metrics/internal/collectors/ceph-block-pool.go
  metrics/internal/collectors/ceph-block-pool_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#2913 Add default TSCs if not present to ensure even distribution of OSDs
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#2924 filesystem: correct the pool name in the ux backend handler
  services/ux-backend/handlers/expandstorage/handler.go
Labels: lgtm, approved

#2921 Fixed an indentation issue in 'prometheus-ocs-rules.yaml' file
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved

#2930 provider: provide namespace for storage-client-mapping config
  services/provider/server/server.go
Labels: lgtm, approved

#2812 DFBUGS-789: Fix 'ceph_disk_occupation' query expressions
  controllers/storagecluster/prometheus/localcephrules.yaml
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important
