Repository red-hat-storage/ocs-operator, pull requests merged in 2024-03, with the labels that each got.

#2479 skip csi-addons pod restart for new namespaces
  controllers/namespace/namespace_controller.go
Labels: lgtm, approved

#2486 Update CephMonLowNumber alert description
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved

#2452 onboarding key generator package rename as it does not implies what it does
  Dockerfile
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-sa.yaml
  deploy/ocs-operator/manifests/onboarding-validation-keys-generator-binding.yaml
  deploy/ocs-operator/manifests/onboarding-validation-keys-generator-role.yaml
  deploy/ocs-operator/manifests/onboarding-validation-keys-generator-sa.yaml
  onboarding-validation-keys-generator/main.go
  rbac/onboarding-secret-generator-sa.yaml
  rbac/onboarding-validation-keys-generator-binding.yaml
  rbac/onboarding-validation-keys-generator-role.yaml
  rbac/onboarding-validation-keys-generator-sa.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2490 Bug 2266583: [release-4.15] Update CephMonLowNumber alert description
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2460 changing native client to runtime client
  onboarding-validation-keys-generator/main.go
Labels: lgtm, approved

#2489 Syncing latest changes from main for ocs-operator
  Dockerfile
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/defaults/placements.go
  controllers/defaults/resources.go
  controllers/namespace/namespace_controller.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephconfig.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  controllers/util/util.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-sa.yaml
  deploy/ocs-operator/manifests/onboarding-validation-keys-generator-binding.yaml
  deploy/ocs-operator/manifests/onboarding-validation-keys-generator-role.yaml
  deploy/ocs-operator/manifests/onboarding-validation-keys-generator-sa.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  onboarding-validation-keys-generator/main.go
  rbac/onboarding-secret-generator-sa.yaml
  rbac/onboarding-validation-keys-generator-binding.yaml
  rbac/onboarding-validation-keys-generator-role.yaml
  rbac/onboarding-validation-keys-generator-sa.yaml
  tools/csv-merger/csv-merger.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2469 UX: implement rotating keys api in ux-backend server
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/ux_backend_role.yaml
  rbac/ux_backend_role.yaml
  services/ux-backend/handlers/common.go
  services/ux-backend/handlers/onboardingtokens/handler.go
  services/ux-backend/handlers/rotatekeys/handler.go
  services/ux-backend/main.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2484 proto: send ocs-operator subscription channel name in heartbeat response
  controllers/util/util.go
  deploy/ocs-operator/manifests/provider-role.yaml
  rbac/provider-role.yaml
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
Labels: lgtm, approved

#2491 add support for Azure key vault
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/kms_resources.go
Labels: lgtm, approved

#2233 Bug 2246525:[release-4.12] Use context.TODO() instead of reconciler's context
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#2505 add runbook_url for OSDCPUHighLoad alert
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved

#2500 Various small fixes found during development
  controllers/util/k8sutil.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2506 Adding a monitoring interval for cephcluster
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#2502 Apply custom taints via the storagecluster CR
  api/v1/ocsinitialization_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_ocsinitializations.yaml
  controllers/defaults/placements.go
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/exporter.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_ocsinitializations.yaml
  deploy/ocs-operator/manifests/ocsinitialization.crd.yaml
  go.mod
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/ocsinitialization_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2501 Create replica-1 sc for external mode if topology details are provided
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#2513 Add CSI_REMOVE_HOLDER_PODS key and its value in the ocs configmap
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/util/k8sutil.go
Labels: lgtm, approved

#2514 Add a specific tag for proxy image
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: lgtm, approved

#2492 Added the new rook bundle and removed rook csv from ocs-operator
  .gitignore
  Makefile
  catalog/index.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephblockpools.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephbucketnotifications.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephbuckettopics.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclients.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephclusters.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephcosidrivers.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephfilesystemmirrors.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephfilesystems.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephnfses.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectrealms.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectstores.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectstoreusers.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectzonegroups.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephobjectzones.yaml
  deploy/csv-templates/crds/rook/ceph.rook.io_cephrbdmirrors.yaml
  deploy/csv-templates/crds/rook/objectstorage-provisioner-role-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  deploy/csv-templates/crds/rook/objectstorage-provisioner-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  deploy/csv-templates/crds/rook/objectstorage-provisioner_v1_serviceaccount.yaml
  deploy/csv-templates/rook-csv.yaml.in
  deploy/deploy-with-olm.yaml
  deploy/ocs-operator/manifests/cephblockpool.crd.yaml
  deploy/ocs-operator/manifests/cephblockpoolradosnamespace.crd.yaml
  deploy/ocs-operator/manifests/cephbucketnotification.crd.yaml
  deploy/ocs-operator/manifests/cephbuckettopic.crd.yaml
  deploy/ocs-operator/manifests/cephclient.crd.yaml
  deploy/ocs-operator/manifests/cephcluster.crd.yaml
  deploy/ocs-operator/manifests/cephcosidriver.crd.yaml
  deploy/ocs-operator/manifests/cephfilesystem.crd.yaml
  deploy/ocs-operator/manifests/cephfilesystemmirror.crd.yaml
  deploy/ocs-operator/manifests/cephfilesystemsubvolumegroup.crd.yaml
  deploy/ocs-operator/manifests/cephnfs.crd.yaml
  deploy/ocs-operator/manifests/cephobjectrealm.crd.yaml
  deploy/ocs-operator/manifests/cephobjectstore.crd.yaml
  deploy/ocs-operator/manifests/cephobjectstoreuser.crd.yaml
  deploy/ocs-operator/manifests/cephobjectzone.crd.yaml
  deploy/ocs-operator/manifests/cephobjectzonegroup.crd.yaml
  deploy/ocs-operator/manifests/cephrbdmirror.crd.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/build-operator-catalog.sh
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/install-ocs.sh
  hack/install-rook.sh
  hack/source-manifests.sh
  pkg/deploy-manager/subscription.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2517 controllers: remove storageprofiles from storageclassrequest
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storageclassrequest/storageclassrequest_controller_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/testing.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/unconventionallisttypecrd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/util.go
Labels: lgtm, approved

#2516 Set values in ocs-operator-config CM for replica-1 in external mode
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/storageclasses.go
  controllers/util/k8sutil.go
Labels: lgtm, approved

#2494 Add options for specifying dataPool and additionalDataPools for cephfs
  Makefile
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2504 RDR: exporting client info
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  services/provider/interfaces/interfaces.go
  services/provider/pb/provider.pb.go
  services/provider/pb/storageclient.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
Labels: lgtm, approved

#2512 add suffix for external ceph client secret name during gRPC response
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2519 controllers: do not skip cephfs creation in provider mode
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
Labels: approved

#2515 rgw: add vhost style support for rgw in ocs-op
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephobjectstores.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2510 add ROOK_OBC_PROVISIONER_NAME_PREFIX to Rook Config
  controllers/storagecluster/generate.go
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#2518 provider: check for RADOS namespace CephResource
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2522 Add rook,ceph image and remove rook related env variables from relatedImages field in csv
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  docs/catalog-generation.md
  hack/generate-unified-csv.sh
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2520 Add ocs-client bundle to ocs-operator catalog
  .gitignore
  Makefile
  catalog/index.yaml
  deploy/deploy-with-olm.yaml
  hack/build-operator-catalog.sh
  hack/common.sh
  hack/install-ocs-client.sh
  pkg/deploy-manager/subscription.go
Labels: lgtm, approved

#2525 Add new rook env variables to rook install script
  hack/install-rook.sh
Labels: lgtm, approved

#2475 configure a native storageclient when running in provider mode
  Dockerfile
  config/manager/manager.yaml
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclient.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/uninstall_reconciler.go
  controllers/util/k8sutil.go
  controllers/util/provider.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  main.go
  services/ux-backend/handlers/onboardingtokens/handler.go
  vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/groupversion_info.go
  vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/storageclassclaim_types.go
  vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/storageclient_types.go
  vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2523 label ceph svg correctly if datapool name is empty
  config/rbac/role.yaml
  controllers/storageclassrequest/storageclassrequest_controller.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/provider-role.yaml
  rbac/provider-role.yaml
Labels: lgtm, approved

#2465 Added support for Prometheus
  config/rbac/role.yaml
  controllers/defaults/resources.go
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/ocsinitialization/ocsinitialization_controller_test.go
  controllers/platform/platform_detection.go
  controllers/util/util.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/k8s-metrics-servicemonitor-role-binding.yaml
  deploy/ocs-operator/manifests/k8s-metrics-servicemonitor-role.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/odf-prometheus-role-binding.yaml
  deploy/ocs-operator/manifests/odf-prometheus-role.yaml
  rbac/k8s-metrics-servicemonitor-role-binding.yaml
  rbac/k8s-metrics-servicemonitor-role.yaml
  rbac/odf-prometheus-role-binding.yaml
  rbac/odf-prometheus-role.yaml
  templates/alertmanager.go
  templates/k8smetricsservicemonitor.go
  templates/prometheus.go
  templates/prometheuskuberbacproxyconfig.go
Labels: lgtm, approved

#2527 Update rook bundle image tag
  hack/common.sh
Labels: lgtm, approved

#2524 Bug 2271371:[release-4.15] Use operator namespace as a driver name
  controllers/storagecluster/generate.go
  controllers/storagecluster/volumesnapshotterclasses.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2530 use ROOK_CSI_DISABLE_DRIVER for disabling CSI in provider mode
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/util/k8sutil.go
  hack/common.sh
  hack/install-rook.sh
Labels: lgtm, approved

#2472 Prevent ObcQuotaObjectsAlert overlapping with ObcQuotaObjectsExhausedAlert
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved

#2531 rbd: update rbd sc for topology provisioning
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#2535 Update rook package version to 4.16.0
  catalog/index.yaml
  hack/common.sh
Labels: lgtm, approved

#2536 storageclassrequest: set controller ownerref
  controllers/storageclassrequest/storageclassrequest_controller.go
Labels: lgtm, approved

#2538 make provider mode deployment w/ CI and manual testing
  catalog/index.yaml
  deploy/deploy-with-olm.yaml
  deploy/single-node-storagecluster-provider.yaml
  hack/common.sh
  hack/install-ocs-client.sh
  pkg/deploy-manager/subscription.go
Labels: lgtm, approved
