Repository red-hat-storage/ocs-operator, pull requests merged in 2024-02, with the labels that each got.

#2385 fixed re-trigger job issue when public key deleted
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/storagecluster_controller.go
  deploy/ocs-operator/manifests/onboarding-secret-generator-role.yaml
  hack/ticketgen/ticketcheck.go
  onboarding/main.go
  rbac/onboarding-secret-generator-role.yaml
  services/provider/server/server.go
Labels: lgtm, approved

#2442 stop CephMonLowNumber alert when MON count is 5
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/storage-cluster.libsonnet
Labels: lgtm, approved

#2444 Remove monitoring mixin
  Makefile
  hack/gen-promethues-rules.sh
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/Makefile
  metrics/mixin/README.md
  metrics/mixin/alerts/alerts-external.libsonnet
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/alerts/blocklist.libsonnet
  metrics/mixin/alerts/encryption-external.libsonnet
  metrics/mixin/alerts/encryption.libsonnet
  metrics/mixin/alerts/mirroring.libsonnet
  metrics/mixin/alerts/obc.libsonnet
  metrics/mixin/alerts/perf.libsonnet
  metrics/mixin/alerts/services-external.libsonnet
  metrics/mixin/alerts/services.libsonnet
  metrics/mixin/alerts/storage-client.libsonnet
  metrics/mixin/alerts/storage-cluster.libsonnet
  metrics/mixin/build/external.jsonnet
  metrics/mixin/build/internal.jsonnet
  metrics/mixin/build/jsonnet/kube-prometheus-external.libsonnet
  metrics/mixin/build/jsonnet/kube-prometheus.libsonnet
  metrics/mixin/build/jsonnet/prometheus.libsonnet
  metrics/mixin/build/jsonnetfile.json
  metrics/mixin/build/jsonnetfile.lock.json
  metrics/mixin/config.libsonnet
  metrics/mixin/lib/alerts-external.jsonnet
  metrics/mixin/lib/alerts.jsonnet
  metrics/mixin/lib/rules.jsonnet
  metrics/mixin/mixin-external.libsonnet
  metrics/mixin/mixin.libsonnet
  metrics/mixin/rules/rules.libsonnet
Labels: lgtm, approved

#2428 controllers: use k8s pointer util
  controllers/storagecluster/exporter.go
  controllers/util/predicates_test.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2445 Enable externalPgSSLRequired only when tlssecret exists
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved

#2441 alerts: add runbook url for ODF Provider
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved

#2449 storageClassRequest: move away from status as source of truth
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storageclassrequest/storageclassrequest_controller_test.go
  controllers/util/slices.go
Labels: lgtm, approved

#2450 Bug 2258937: [release-4.15] storageClassRequest: move away from status as source of truth
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/util/slices.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2453 Bug 2263311: Backport fusion hci phase 2 related changes to 4.14 branch
  Dockerfile
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  config/rbac/kustomization.yaml
  config/rbac/oauth_proxy_role.yaml
  config/rbac/oauth_proxy_role_binding.yaml
  config/rbac/ux_backend_sa.yaml
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/util/slices.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-binding.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-role.yaml
  deploy/ocs-operator/manifests/onboarding-secret-generator-sa.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/manifests/ux_backend_role.yaml
  deploy/ocs-operator/manifests/ux_backend_role_binding.yaml
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  hack/source-manifests.sh
  hack/ticketgen/ticketcheck.go
  onboarding/main.go
  rbac/onboarding-secret-generator-binding.yaml
  rbac/onboarding-secret-generator-role.yaml
  rbac/onboarding-secret-generator-sa.yaml
  rbac/ux_backend_role.yaml
  rbac/ux_backend_role_binding.yaml
  services/provider/client/client.go
  services/provider/clientstatus/status.go
  services/provider/interfaces/interfaces.go
  services/provider/pb/provider.pb.go
  services/provider/pb/storageclient.go
  services/provider/pb/storageclient_status.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/types.go
  services/ux-backend/handlers/onboardingtokens/handler.go
  services/ux-backend/main.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2454 Fix cephCluster invalid spec error in replica-1 due to misspelled field
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#2458 Adds spec changes to enable TLS on external Postgresql server
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#2462 fix csv generation.
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2463 Syncing latest changes from main for ocs-operator
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2456 storageclassrequest: replace the filter logic with fieldIndexer
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storageclassrequest/storageclassrequest_controller_test.go
  controllers/util/slices.go
Labels: lgtm, approved

#2461 Added a fix for noobaa-standalone placement configuration
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved

#2448 Use separate TSCs with labels for osd & osd prepare pods
  controllers/defaults/placements.go
Labels: lgtm, approved

#2468 Increase mgr resources to avoid mgr OOMKilled
  controllers/defaults/resources.go
Labels: lgtm, approved

#2477 allow disabling key rotation
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/util/util.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2234 Bug 2246526:[release-4.13] Use context.TODO() instead of reconciler's context
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#2482 Remove active mds solution from alert
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved
