Repository red-hat-storage/ocs-operator, pull requests merged in 2024-05, with the labels that each got.

#2595 Bug 2278641: [release-4.15] remove namespace controller
  PROJECT
  config/rbac/role.yaml
  controllers/namespace/namespace_controller.go
  controllers/namespace/namespace_controller_test.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  main.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2603 Fix rbd daemon count validation
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#2596 Make all alerts/rules compatible with multicluster mode
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#2585 external: seaprate rgw endpoint validation from cephfs and rbd sc
  controllers/storagecluster/external_resources.go
Labels: lgtm, approved

#2610 Revert "bundle: add rook as a dependency to allow upgrades from 4.15 to 4.16"
  config/dependencies/dependencies.yaml
  deploy/ocs-operator/metadata/dependencies.yaml
  hack/source-manifests.sh
Labels: lgtm, approved

#2611 Update github workflows actions versions
  .github/workflows/ocs-operator-ci.yaml
Labels: lgtm, approved

#2614 Update ocs operator CSV version to 4.17.0
  catalog/index.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/version/version.go
  version/version.go
Labels: lgtm, approved

#2608 Bug 2262943: [release-4.16] Make all alerts/rules compatible with multicluster mode
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2581 Bug 2276824: [release-4.15] Add waitTimeoutForHealthyOSDInMinutes field in the storagecluster CR
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2616 action: add action to build and push images on demand
  .github/workflows/docker-push.yaml
Labels: lgtm, approved

#2619 Fix storagecluster version in odfinfoconfig unit test
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/odfinfoconfig_test.go
  controllers/storagecluster/storagecluster_controller_test.go
Labels: lgtm, approved

#2582 Bug 2276825: [release-4.14] Add waitTimeoutForHealthyOSDInMinutes field in the storagecluster CR
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2591 Bug 2277928: [release-4.12]Add waitTimeoutForHealthyOSDInMinutes field in the storagecluster CR
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2621 controllers: limit reconciliations to relevant events
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/storagecluster_controller.go
  go.mod
Labels: lgtm, approved

#2590 Bug 2277926: [release-4.13] Add waitTimeoutForHealthyOSDInMinutes field in the storagecluster CR
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/metadata/annotations.yaml
  hack/operator-sdk-common.sh
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2622 Bug 2282086:[release-4.16] controllers: limit reconciliations to relevant events
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/storagecluster_controller.go
  go.mod
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2618 do not check for storageconsumer when storagerequest is being deleted
  controllers/storagerequest/storagerequest_controller.go
Labels: lgtm, approved

#2628 Fix spell check CI
  .github/workflows/ocs-operator-ci.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  docs/catalog-generation.md
Labels: lgtm, approved

#2612 exporter: add metric and alert if a system has OSD based on LVM
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/go.mod
  metrics/go.sum
  metrics/internal/collectors/ceph-cluster.go
  metrics/internal/collectors/ceph-cluster_test.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/annotations.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/keys.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/labels.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/scc.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/security.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
Labels: lgtm, approved

#2632 noobaa: provide denyHTTP option to NooBaa CR
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#2636 Bug 2279928:[release-4.16] exporter: add metric and alert if a system has OSD based on LVM
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/go.mod
  metrics/go.sum
  metrics/internal/collectors/ceph-cluster.go
  metrics/internal/collectors/ceph-cluster_test.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/scc.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/security.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  metrics/vendor/golang.org/x/net/http2/frame.go
  metrics/vendor/golang.org/x/net/http2/pipe.go
  metrics/vendor/golang.org/x/net/http2/server.go
  metrics/vendor/golang.org/x/net/http2/testsync.go
  metrics/vendor/golang.org/x/net/http2/transport.go
  metrics/vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2627 Syncing latest changes from main for ocs-operator
  .github/workflows/ocs-operator-ci.yaml
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagerequest/storagerequest_controller.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  docs/catalog-generation.md
  go.mod
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/go.mod
  metrics/go.sum
  metrics/internal/collectors/ceph-cluster.go
  metrics/internal/collectors/ceph-cluster_test.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/annotations.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/keys.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/labels.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/scc.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/security.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#2646 [release-4.13] Fix spell check CI
  .github/workflows/ocs-operator-ci.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  docs/catalog-generation.md
  hack/gen-promethues-rules.sh
Labels: lgtm, approved, bugzilla/valid-bug

#2644 [release-4.15] Fix spell check CI
  .github/workflows/ocs-operator-ci.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  docs/catalog-generation.md
  hack/gen-promethues-rules.sh
Labels: lgtm, approved, bugzilla/valid-bug

#2645 [release-4.14] Fix spell check CI
  .github/workflows/ocs-operator-ci.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  docs/catalog-generation.md
  hack/gen-promethues-rules.sh
Labels: lgtm, approved, bugzilla/valid-bug

#2635 use "upmap-read" as default balancer mode
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/annotations.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/keys.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/labels.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/resources.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/scc.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/security.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2647 [release-4.12] Fix spell check CI
  .github/workflows/ocs-operator-ci.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  docs/catalog-generation.md
  hack/gen-promethues-rules.sh
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved, bugzilla/valid-bug

#2638 do not reset ocs-metrics-exporter ServiceAccount specs
  controllers/storagecluster/exporter.go
Labels: lgtm, approved

#2640 Bug 2276824: [release-4.15] Remove default value of waitTimeoutForHealthyOSDInMinutes
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2639 Bug 2276694: [release-4.16] Remove default value of waitTimeoutForHealthyOSDInMinutes
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2642 Bug 2277926: [release-4.13] Remove default value of waitTimeoutForHealthyOSDInMinutes
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2641 Bug 2276825: [release-4.14] Remove default value of waitTimeoutForHealthyOSDInMinutes
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2643 Bug 2277928: [release-4.12] Remove default value of waitTimeoutForHealthyOSDInMinutes
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
