Repository red-hat-storage/ocs-operator, pull requests merged in 2024-09, with the labels that each got.

#2733 Added support for ocs provider server to fetch noobaa client resources
  config/rbac/role.yaml
  controllers/storageconsumer/consumer_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/provider-role.yaml
  rbac/provider-role.yaml
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2766 use qualified name upto ".svc" for endpoint svc in native storageclient
  controllers/storagecluster/storageclient.go
Labels: lgtm, approved

#2768 Reducing the template.openshift.io group privileges
  config/rbac/role.yaml
  controllers/storagecluster/reconcile.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2782 Add watch verb to snapshot.storage.k8s.io group
  config/rbac/role.yaml
  controllers/storagecluster/reconcile.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2776 disabling rook mgr module in CephCluster
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved

#2773 update deps bundle images
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/install-ocs-operator.sh
Labels: lgtm, approved

#2788 Bug 2270889: [release-4.14] Revert "add topology mode annotation rgw service"
  controllers/storagecluster/cephobjectstores.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2620 Adds metadata to external ceph resources
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
Labels: lgtm, approved

#2794 Syncing latest changes from main for ocs-operator
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
Labels: lgtm, approved

#2797 restore default affinity for noobaa standalone
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved, ok-to-test

#2800 Bug 2309488:[release-4.17] Added support for ocs provider server to fetch noobaa client resources
  config/rbac/role.yaml
  controllers/storageconsumer/consumer_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/provider-role.yaml
  rbac/provider-role.yaml
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2806 proto: remove depricated label
  services/provider/api/provider.pb.go
  services/provider/proto/provider.proto
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
Labels: lgtm, approved

#2808 Syncing latest changes from main for ocs-operator
  services/provider/api/provider.pb.go
  services/provider/proto/provider.proto
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
Labels: lgtm, approved

#2805 Bug 2304799: [release-4.17] Sending desired state of provider config
  controllers/util/util.go
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2809 csv: update ocs-operator csv version to 4.18
  catalog/index.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/version/version.go
  version/version.go
Labels: lgtm, approved

#2810 Syncing latest changes from main for ocs-operator
  catalog/index.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/version/version.go
  version/version.go
Labels: lgtm, approved

#2813 remove resource limits on ocs-metrics-exporter
  controllers/defaults/resources.go
  metrics/deploy/deployment.yaml
Labels: lgtm, approved

#2792 Bug 2311468: [release-4.17] Re-adds DR Optimized check feature
  api/v1alpha1/odfinfoconfig.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/odfinfoconfig.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2815 Set default CephDeviceClass in the status only if it's not set yet
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved

#2816 Update the Prometheus rule alerts acc to specified value & correct the default values in API desc
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2669 changes to onboarding token api to include role in body
  controllers/storagecluster/storageclient.go
  controllers/util/provider.go
  services/provider/server/server.go
  services/types.go
  services/ux-backend/handlers/onboarding/clienttokens/handler.go
  services/ux-backend/handlers/onboarding/peertokens/handler.go
  services/ux-backend/main.go
Labels: lgtm, approved

#2821 Syncing latest changes from main for ocs-operator
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved

#2718 Update provider-api-server to be deployed in internal and provider mode
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephrbdmirrors_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  controllers/storagecluster/storageclient.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/util/k8sutil.go
  deploy/ocs-operator/manifests/onboarding-validation-keys-generator-binding.yaml
  deploy/ocs-operator/manifests/onboarding-validation-keys-generator-role.yaml
  deploy/ocs-operator/manifests/provider-role-binding.yaml
  deploy/ocs-operator/manifests/provider-role.yaml
  onboarding-validation-keys-generator/main.go
  rbac/onboarding-validation-keys-generator-binding.yaml
  rbac/onboarding-validation-keys-generator-role.yaml
  rbac/provider-role-binding.yaml
  rbac/provider-role.yaml
  services/provider/main.go
Labels: lgtm, approved

#2819 Prevent noobaaccount creation in provider cluster
  controllers/storageconsumer/consumer_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2828 Ignore sending healthchecker & rook-ceph-mon secrets via storageconfig
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved
