Repository red-hat-storage/ocs-operator, pull requests merged in 2024-04, with the labels that each got.

#2534 Exports the cluster's name
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  services/provider/interfaces/interfaces.go
  services/provider/pb/provider.pb.go
  services/provider/pb/storageclient.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
Labels: lgtm, approved

#2545 bundle: add readOnlyRootFilesystem for ocs-operator
  config/manager/manager.yaml
  controllers/storagecluster/exporter.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2552 Bug 2274100:[release-4.15] bundle: add readOnlyRootFilesystem for ocs-operator
  config/manager/manager.yaml
  controllers/storagecluster/exporter.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2544 initalise objectstore.spec.hosting for virtualHostnames
  controllers/storagecluster/cephobjectstores.go
Labels: lgtm, approved

#2551 rename CSI_REMOVE_HOLDER_PODS to CSI_DISABLE_HOLDER_PODS
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/util/k8sutil.go
  hack/common.sh
  hack/install-rook.sh
Labels: lgtm, approved

#2547 update storageclient to reflect as a clusterscoped resource
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  controllers/storagecluster/storageclient.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  services/provider/interfaces/interfaces.go
  services/provider/pb/provider.pb.go
  services/provider/pb/storageclient.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
Labels: lgtm, approved

#2548 rename storageclassclaim to storageclaim in gRPC methods
  services/provider/client/client.go
  services/provider/pb/provider.pb.go
  services/provider/pb/provider_grpc.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2564 update ocs-client-operator bundle image
  hack/common.sh
Labels: lgtm, approved

#2562 Specify pg & pgm num to distribute data across OSDs for replica-1 pools
  controllers/storagecluster/cephblockpools.go
Labels: lgtm, approved

#2565 bundle: add rook as a dependency to allow upgrades from 4.15 to 4.16
  config/dependencies/dependencies.yaml
  deploy/ocs-operator/metadata/dependencies.yaml
  hack/source-manifests.sh
Labels: lgtm, approved

#2563 allow cleanup of ceph resources when storageclassrequest is deleted
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storageclassrequest/storageclassrequest_controller_test.go
Labels: lgtm, approved

#2550 Rename StorageClassRequest api to StorageRequest
  PROJECT
  api/v1/storagecluster_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/storageclassrequest_types.go
  api/v1alpha1/storagerequest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  config/crd/bases/ocs.openshift.io_storagerequests.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storagerequests.yaml
  config/crd/patches/webhook_in_storagerequests.yaml
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/storagerequest_editor_role.yaml
  config/rbac/storagerequest_viewer_role.yaml
  config/samples/ocs_v1alpha1_storagerequest.yaml
  controllers/storagecluster/storageclasses.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/storagerequest/storagerequest_controller.go
  controllers/storagerequest/storagerequest_controller_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storagerequests.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/provider-role.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/manifests/storagerequest.crd.yaml
  main.go
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/LICENSE
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/groupversion_info.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageclassrequest_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storagerequest_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
  rbac/provider-role.yaml
  services/provider/server/server.go
  services/provider/server/server_test.go
  services/provider/server/storageclassrequest.go
  services/provider/server/storageclassrequest_test.go
  services/provider/server/storagerequest.go
  services/provider/server/storagerequest_test.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/groupversion_info.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageclassrequest_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storagerequest_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, ok-to-test

#2568 remove storagecluster as owner of clusterscope storageclient
  controllers/storagecluster/storageclient.go
  controllers/storagecluster/storagecluster_controller.go
  hack/common.sh
Labels: lgtm, approved

#2573 change forcedeletion annotation key for cleanup of ceph resources
  controllers/storagerequest/storagerequest_controller.go
Labels: lgtm, approved

#2570 change storagerequest spec.type to be either block or sharedfile
  api/v1alpha1/storagerequest_types.go
  config/crd/bases/ocs.openshift.io_storagerequests.yaml
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  controllers/storagerequest/storagerequest_controller.go
  controllers/storagerequest/storagerequest_controller_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storagerequests.yaml
  deploy/ocs-operator/manifests/storagerequest.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storagerequest_types.go
  services/provider/client/client.go
  services/provider/server/server.go
  services/provider/server/server_test.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storagerequest_types.go
Labels: lgtm, approved

#2569 remove rotation of keys endpoint from ux-backend
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/ux_backend_role.yaml
  rbac/ux_backend_role.yaml
  services/ux-backend/handlers/common.go
  services/ux-backend/handlers/rotatekeys/handler.go
  services/ux-backend/main.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2571 provider: avoid CSI secret name collisions
  services/provider/server/server.go
  services/provider/server/server_test.go
  services/provider/server/storagerequest.go
  services/provider/server/storagerequest_test.go
Labels: lgtm, approved

#2579 Add waitTimeoutForHealthyOSDInMinutes field in the storagecluster CR
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/defaults/defaults.go
  controllers/storagecluster/cephcluster.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#2583 Remove support TSC check & always use TSCs for osd placements
  controllers/defaults/placements.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/clusterclaims.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/resourceprofile.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/storagequota_test.go
Labels: lgtm, approved

#2588 Adding empty label selector for prom service monitor selector
  templates/prometheus.go
Labels: lgtm, approved

#2586 Support specifying Node Affinity for CephToolbox pod
  api/v1/storagecluster_types.go
  controllers/storagecluster/cephtoolbox.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved
