Repository red-hat-storage/ocs-operator, pull requests merged in 2024-01, with the labels that each got.

#2254 Bug 2243003: [Release 4.13] fix obc label alerts issue
  config/rbac/exporter-role.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/deploy/rbac.yaml
  metrics/internal/collectors/object-bucket.go
  metrics/mixin/alerts/mirroring.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2353 Enhanced logger for ocs-metrics-exporter
  go.mod
  metrics/internal/handler/handler.go
  metrics/internal/options/options.go
  metrics/main.go
Labels: lgtm, approved

#2357 Bug 2256458: [release-4.14] Enhanced logger for ocs-metrics-exporter
  go.mod
  metrics/internal/handler/handler.go
  metrics/internal/options/options.go
  metrics/main.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2358 Bug 2256459: [release-4.13] Enhanced logger for ocs-metrics-exporter
  go.mod
  metrics/internal/handler/handler.go
  metrics/internal/options/options.go
  metrics/main.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2255 Bug 2239766: [Release 4.12] fix obc label alerts issue
  config/rbac/exporter-role.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/deploy/rbac.yaml
  metrics/internal/collectors/object-bucket.go
  metrics/mixin/alerts/mirroring.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2359 Update go modules to Golang v1.21
  .github/workflows/ocs-operator-ci.yaml
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  metrics/Dockerfile
  vendor/modules.txt
Labels: lgtm, approved

#2360 make changes to the contribution guide
  CONTRIBUTING.md
Labels: lgtm, approved

#2361 use correct units for MDSCacheUsageHigh alerts
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/perf.libsonnet
Labels: lgtm, approved

#2345 Some minor changes/fixes to ux backend
  services/provider/server/server.go
  services/types.go
  services/ux-backend/handlers/onboardingtokens/handler.go
  services/ux-backend/main.go
Labels: lgtm, approved

#2370 [fusion-hci-4.14] added changes to oauth proxy config
  config/rbac/kustomization.yaml
  config/rbac/oauth_proxy_role.yaml
  config/rbac/oauth_proxy_role_binding.yaml
  config/rbac/ux_backend_sa.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/ux_backend_sa.yaml
  hack/source-manifests.sh
  services/ux-backend/main.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2369 UX Backend - Unified handling of env var based configuration
  services/ux-backend/main.go
Labels: lgtm, approved

#2329 Send provider operator version in client heartbeat
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
Labels: lgtm, approved

#2382 Revert "Send provider operator version in client heartbeat"
  services/provider/pb/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
Labels: lgtm, approved

#2384 Fixed wrong runbook link for PersistentVolumeUsageNearFull alert
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#2381 update noobaa version that is compatible with rook 1.13.1
  api/go.mod
  api/go.sum
  api/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  api/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  api/vendor/modules.txt
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2321 Add 'runbook_url' link to alerts' annotation
  controllers/storagecluster/prometheus/localcephrules.yaml
  metrics/deploy/prometheus-ocs-rules-external.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/obc.libsonnet
  metrics/mixin/alerts/services-external.libsonnet
  metrics/mixin/alerts/services.libsonnet
Labels: lgtm, approved

#2386 add runbooks links for ceph rules
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#2249 storageclassrequest: refactor and unit testing
  controllers/storageclassrequest/storageclassrequest_controller.go
  controllers/storageclassrequest/storageclassrequest_controller_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/testing.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/unconventionallisttypecrd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/util.go
Labels: lgtm, approved

#2390 Fixed wrong runbook link for CephMonLowNumber alert
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#2362 Set current mon count value in StorageCluster CR
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#2395 Added group and made resource to smallcase to support api call from pod
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2403 update Project file
  PROJECT
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2404 add runbook url for MDSCpuUsageHigh alert.
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/perf.libsonnet
Labels: lgtm, approved

#2398 Revert "add topology mode annotation rgw service"
  controllers/storagecluster/cephobjectstores.go
Labels: lgtm, approved

#2401 add runbook url for MDSCacheUsageHigh alert
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/perf.libsonnet
Labels: lgtm, approved

#2383 Provide options for count, resources, volumeclaimtemplate for replica-1
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2394 refactor metrics exporter deployment
  controllers/storagecluster/exporter.go
Labels: lgtm, approved

#2380 remove rbd-mirror metrics already exported by ceph
  metrics/internal/cache/rbd-mirror.go
  metrics/internal/collectors/rbd-mirror.go
Labels: lgtm, approved

#2410 fix false positive error log in metrics-exporter
  metrics/internal/collectors/ceph-block-pool.go
Labels: lgtm, approved

#2406 increase the threshold for OSDCPULoadHigh
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/mixin/alerts/perf.libsonnet
  metrics/mixin/config.libsonnet
Labels: lgtm, approved

#2399 RBD mirror daemon count validation
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#2408 Fix PV cache lock mechanism
  metrics/internal/cache/pv.go
Labels: lgtm, approved

#2424 Refactor the ensureCreated func for rook-config-override configmap
  controllers/storagecluster/cephconfig.go
  controllers/storagecluster/cephconfig_test.go
Labels: lgtm, approved

#2392 Adding 'ClusterRole' and 'ClusterRoleBinding' to rook-ceph-mgr
  controllers/storagecluster/exporter.go
  deploy/ocs-operator/manifests/rook-monitor-mgr-role.yaml
  deploy/ocs-operator/manifests/rook-monitor-mgr-role_binding.yaml
  rbac/rook-monitor-mgr-role.yaml
  rbac/rook-monitor-mgr-role_binding.yaml
Labels: lgtm, approved

#2288 `StorageProfile` unit tests
  controllers/storageclassrequest/storageclassrequest_controller_test.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/storagecluster_controller_test.go
Labels: lgtm, approved

#2235 Bug 2246527:[release-4.14] Use context passed via handler instead of reconciler's context
  controllers/namespace/namespace_controller_test.go
  controllers/storagecluster/storagecluster_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#2413 fix PV cache error conditions
  metrics/internal/cache/pv.go
Labels: lgtm, approved

#2407 Enable ceph client and collectors for multicluster case
  controllers/storagecluster/exporter.go
  metrics/internal/cache/ceph-blocklist.go
  metrics/internal/cache/pv.go
  metrics/internal/cache/pv_test.go
  metrics/internal/cache/rbd-mirror.go
  metrics/internal/cache/rbd_mirror_test.go
  metrics/internal/options/options.go
Labels: lgtm, approved

#2430 Fix CephMonLowNumber alert
  controllers/storagecluster/prometheus/localcephrules.yaml
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/internal/collectors/ceph-cluster.go
  metrics/internal/collectors/ceph-cluster_test.go
  metrics/internal/collectors/storage-cluster.go
  metrics/mixin/alerts/alerts.libsonnet
  metrics/mixin/alerts/storage-cluster.libsonnet
Labels: lgtm, approved

#2427 Add keyRotation spec to the StorageCluster
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/util/util.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2434 split rook monitoring rbac into multiple files
  deploy/ocs-operator/manifests/rook-ceph-metrics-role.yaml
  deploy/ocs-operator/manifests/rook-ceph-monitor-role.yaml
  deploy/ocs-operator/manifests/rook-monitor-mgr-role.yaml
  rbac/rook-ceph-metrics-role.yaml
  rbac/rook-ceph-monitor-role.yaml
  rbac/rook-monitor-mgr-role.yaml
Labels: lgtm, approved

#2433 Add 'managedBy' label to rook-ceph-exporter metrics
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#2429 add CSI_DRIVER_NAME_PREFIX to Rook config
  controllers/storagecluster/generate.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/volumesnapshotterclasses.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved
