Repository red-hat-storage/ocs-operator, pull requests merged in 2024-07, with the labels that each got.

#2679 Update ocs-metrics-exporter to follow best practices
  controllers/defaults/resources.go
  controllers/storagecluster/exporter.go
  controllers/storagecluster/storagecluster_controller.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-latest-csv.sh
  hack/generate-unified-csv.sh
  metrics/deploy/deployment.yaml
  metrics/deploy/kube-rbac-proxy-secret.yaml
  metrics/deploy/rbac.yaml
  metrics/deploy/scc.yaml
  metrics/deploy/service.yaml
  metrics/deploy/servicemonitor.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#2681 Add missing RBACs required for ocs-metrics-exporter
  config/rbac/role.yaml
  controllers/storagecluster/reconcile.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2684 Update github workflows go version to 1.22
  .github/workflows/ocs-operator-ci.yaml
  Makefile
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_ocsinitializations.yaml
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  config/crd/bases/ocs.openshift.io_storageprofiles.yaml
  config/crd/bases/ocs.openshift.io_storagerequests.yaml
  config/rbac/role.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_ocsinitializations.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageprofiles.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storagerequests.yaml
  deploy/ocs-operator/manifests/ocsinitialization.crd.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  deploy/ocs-operator/manifests/storageprofile.crd.yaml
  deploy/ocs-operator/manifests/storagerequest.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  tools/csv-merger/csv-merger.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2687 fix metrics-exporter resource requests and limits
  controllers/defaults/resources.go
Labels: lgtm, approved

#2689 Metrics exporter configuration and args fixes
  controllers/storagecluster/exporter.go
Labels: lgtm, approved

#2692 Reducing the noobaas resources privilege according to the required verbs
  config/rbac/role.yaml
  controllers/storagecluster/reconcile.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2600 Changes to the onboarding token api to include quota in the body
  controllers/storagecluster/storageclient.go
  controllers/util/provider.go
  services/types.go
  services/ux-backend/handlers/onboardingtokens/handler.go
Labels: lgtm, approved

#2688 annotate RBD storageclasses for reclaimspace
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#2694 Fix pg_autoscaler won't scale due to overlapping roots
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
Labels: lgtm, approved

#2661 Sends `VolumeGroupSnapshotClass` to client
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2699 Fix fetching CSV from right namespace
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/odfinfoconfig.go
Labels: lgtm, approved

#2698 Migrate odf-info structs to API folder
  api/v1alpha1/odfinfoconfig.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/storagecluster/odfinfoconfig.go
  controllers/storagecluster/odfinfoconfig_test.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2672 Adding changes to decode/Unmarshal quota from token
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/ux-backend/handlers/onboardingtokens/handler.go
Labels: lgtm, approved

#2704 [release-4.13] remove status-reporter binary copy step
  build/Dockerfile
Labels: lgtm, approved, bugzilla/valid-bug

#2703 Annotate RBD storageclasses for keyrotation
  controllers/storagecluster/storageclasses.go
Labels: lgtm, approved

#2705 [release-4.12] remove status-reporter binary copy step
  build/Dockerfile
Labels: lgtm, approved, bugzilla/valid-bug

#2702 external: enable log rotation and log collection for external mode
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/storagecluster_controller_test.go
Labels: lgtm, approved

#2685 Sending encoded bytes for storage quota
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2708 use "upmap-read" as default balancer mode
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved

#2606 Migrate osds to bluestore
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  docs/design/disaster-recovery-optimization.md
Labels: lgtm, approved

#2709 Add a check for provider mode and pass to noobaa
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved

#2677 add new cr and controller for peering
  PROJECT
  api/v1/groupversion_info.go
  api/v1/storageclusterpeer_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusterpeers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storageclusterpeers.yaml
  config/crd/patches/webhook_in_storageclusterpeers.yaml
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/storageclusterpeer_editor_role.yaml
  config/rbac/storageclusterpeer_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/ocs_v1_storageclusterpeer.yaml
  controllers/storageclusterpeer/storageclusterpeer_controller.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusterpeers.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storageclusterpeer.crd.yaml
  main.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/groupversion_info.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageclusterpeer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/groupversion_info.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageclusterpeer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2623 Bug 2282087:[release-4.15] controllers: limit reconciliations to relevant events
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/storagecluster_controller.go
  go.mod
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2624 Bug 2282089:[release-4.14] controllers: limit reconciliations to relevant events
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/storagecluster_controller.go
  go.mod
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2717 provider: add annotation to StorageCluster about deployment mode
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
Labels: lgtm, approved
