Repository red-hat-storage/ocs-operator, pull requests merged in 2025-05, with the labels that each got.

#3170 Set mon_target_pg_per_osd to 400 only during cluster creation
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3175 DFBUGS-2305:[release-4.16] check csvs in the operator ns instead of storagecluster ns
  controllers/storagecluster/clusterclaims.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-critical

#3201 Set mon_max_pg_per_osd to 1000 to avoid too many PGs warning
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephconfig.go
Labels: lgtm, approved

#3194 Always apply rbd-mirror debug logging ceph configs
  controllers/storagecluster/cephconfig.go
  controllers/storagecluster/cephrbdmirrors.go
  controllers/storagecluster/reconcile.go
Labels: lgtm, approved

#3203 Add target size ratio value to custom cephBlockPool during creation
  services/ux-backend/handlers/expandstorage/handler.go
Labels: lgtm, approved

#3202 Fix NFS snapshot class name used in internal consumer distribution
  controllers/storagecluster/storageconsumer.go
Labels: lgtm, approved

#3179 storageautoscaler: refactor the resizing verification logic
  controllers/storageautoscaler/storageautoscaler_controller.go
  controllers/storageautoscaler/storageautoscaler_controller_test.go
  controllers/storageautoscaler/verify.go
  controllers/storageautoscaler/verify_test.go
Labels: lgtm, approved

#3084 Add node toleration to prometheus operator pod
  controllers/ocsinitialization/ocsinitialization_controller.go
Labels: lgtm, approved, ok-to-test

#3217 Make mon_target_pg_per_osd = 400 always both for new & upgraded clusters
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved

#3185 Prevent quota reduction via CEL validation in StorageConsumer CRD
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
Labels: lgtm, approved

#3219 allow virtualization storageclass to be marked as default for kubevirt
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/util/storageclasses.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#3216 controller: fix permissions for consumer controller
  config/rbac/role.yaml
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#3228 storageautoscaler: fix the invalid state phase
  controllers/storageautoscaler/storageautoscaler_controller.go
Labels: lgtm, approved

#3218 delete rns cr only if there are no rbd images
  controllers/storageconsumer/storageconsumer_controller.go
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/namespace.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  metrics/vendor/golang.org/x/net/html/atom/table.go
  metrics/vendor/golang.org/x/net/html/parse.go
  metrics/vendor/golang.org/x/net/html/token.go
  metrics/vendor/golang.org/x/net/http2/frame.go
  metrics/vendor/golang.org/x/net/http2/server.go
  metrics/vendor/golang.org/x/net/websocket/websocket.go
  metrics/vendor/modules.txt
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/namespace.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: lgtm, approved

#3200 storageautoscaler: scale only when more than threshold minus 10% percent of cluster is used
  controllers/storageautoscaler/scraper.go
  controllers/storageautoscaler/scraper_test.go
  controllers/storageautoscaler/storageautoscaler_controller.go
  controllers/storageautoscaler/storageautoscaler_controller_test.go
Labels: lgtm, approved

#3193 server: add monips as a part of desired state hash
  services/provider/server/server.go
Labels: lgtm, approved

#3232 controllers: prevent deletion of storageclusterpeer
  controllers/mirroring/mirroring_controller.go
  controllers/storageclusterpeer/storageclusterpeer_controller.go
Labels: lgtm, approved

#3237 Follow the replicate size of the default CephBlockPool for the .mgr pool
  controllers/storagecluster/cephblockpools.go
Labels: lgtm, approved

#3238 add nil check for client in metrics exporter
  metrics/internal/collectors/storageconsumer.go
Labels: lgtm, approved

#3227 Send OCS sub channel only if the current CSV of the sub has succeeded
  deploy/ocs-operator/manifests/provider-role.yaml
  rbac/provider-role.yaml
  services/provider/server/server.go
Labels: lgtm, approved

#3242 Set mon_target_pg_per_osd based on the resource profile
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved

#3221 controllers: add finalizers for internal client/consumer
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclient.go
  controllers/storagecluster/storageconsumer.go
Labels: lgtm, approved

#3136 Adding an alert to detect StorageAutoScaler CRs in invalid state
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/internal/collectors/storage-auto-scaler.go
Labels: lgtm, approved

#3252 delete pre4.19 rns cr as part of provider upgrade
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
Labels: lgtm, approved

#3222 external: add external mode label to storageclasses
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/storageconsumer.go
  controllers/storagecluster/volumegroupsnapshotterclasses.go
  controllers/storagecluster/volumesnapshotterclasses.go
  controllers/util/k8sutil.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
  services/provider/server/server.go
Labels: lgtm, approved

#3251 delete pre4.19 svg cr as part of internal upgrade
  controllers/storagecluster/storageconsumer.go
Labels: lgtm, approved

#3223 server: FullFillStorageClaim returns empty response and no error
  services/provider/server/server.go
Labels: lgtm, approved

#3262 Fix extensibility issue with GetDesiredClientState
  services/provider/api/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
Labels: lgtm, approved

#3264 Expend KubeObject message to return expected client reconcile behavior
  services/provider/api/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
Labels: lgtm, approved

#3255 Add disable key rotation annotation only for the internal client
  controllers/storagecluster/storageconsumer.go
  controllers/util/storageclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
  services/provider/server/server.go
Labels: lgtm, approved

#3260 server: add rbd storageid and clientProfile name to the GetStorageClientInfo rpc
  services/provider/api/provider.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
Labels: lgtm, approved
