Repository red-hat-storage/ocs-operator, pull requests merged in 2025-04, with the labels that each got.

#3115 consumer: update calculation of the default clientprofile name
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/storageconsumer.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
Labels: lgtm, approved

#3114 consumer: reconcile rbd/cephfs/nfs if service required
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/external_resources_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/storageclasses.go
  controllers/util/storageconsumer.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
  services/provider/server/server.go
Labels: lgtm, approved

#3121 remove namespaced owner reference from cluster-scoped StorageClass
  controllers/storagecluster/obcstorageclasses.go
Labels: lgtm, approved

#3120 Update golang.org/golang.org/x/net to v0.37.0 for CVE CVE-2025-22870
  services/provider/api/go.mod
  services/provider/api/go.sum
  services/provider/api/vendor/golang.org/x/net/http2/config.go
  services/provider/api/vendor/golang.org/x/net/http2/config_go124.go
  services/provider/api/vendor/golang.org/x/net/http2/http2.go
  services/provider/api/vendor/golang.org/x/net/http2/server.go
  services/provider/api/vendor/golang.org/x/net/http2/transport.go
  services/provider/api/vendor/golang.org/x/net/http2/write.go
  services/provider/api/vendor/golang.org/x/net/internal/httpcommon/ascii.go
  services/provider/api/vendor/golang.org/x/net/internal/httpcommon/headermap.go
  services/provider/api/vendor/golang.org/x/net/internal/httpcommon/request.go
  services/provider/api/vendor/golang.org/x/sys/unix/auxv.go
  services/provider/api/vendor/golang.org/x/sys/unix/auxv_unsupported.go
  services/provider/api/vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  services/provider/api/vendor/golang.org/x/sys/unix/syscall_solaris.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  services/provider/api/vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  services/provider/api/vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  services/provider/api/vendor/golang.org/x/sys/unix/ztypes_linux.go
  services/provider/api/vendor/golang.org/x/sys/windows/dll_windows.go
  services/provider/api/vendor/modules.txt
Labels: lgtm, approved

#3123 Set metadata pool spec on the cephFS metadata pool
  controllers/storagecluster/cephfilesystem.go
Labels: lgtm, approved

#3119 align internal storageconsumer for fresh and upgraded deployments
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/odfinfoconfig_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/storageconsumer.go
  controllers/storagecluster/uninstall_reconciler_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/storageconsumer.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
  services/provider/server/server.go
Labels: lgtm, approved

#3125 controllers: fix obc storageclass creation
  controllers/storagecluster/obcstorageclasses.go
  controllers/util/k8sutil.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
Labels: lgtm, approved

#3127 api: make allowRemoteStorageConsumers immutable
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#3133 provider: implement a new rpc GetStorageInfo for the new hub & spoke to be used from 4.19 onwards
  services/provider/api/client/client.go
  services/provider/api/provider.pb.go
  services/provider/api/provider_grpc.pb.go
  services/provider/proto/provider.proto
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/client/client.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider_grpc.pb.go
Labels: lgtm, approved

#3129 do not reconcile older storageconsumer
  controllers/storageconsumer/consumer_test.go
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#3116 rdr: update the controller/server for rdr after convergence
  controllers/mirroring/mirroring_controller.go
  controllers/storagecluster/odfinfoconfig.go
  services/provider/server/server.go
Labels: lgtm, approved

#3131 controllers: add a new controller to handle provider upgrades
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
  controllers/storagecluster/obcstorageclasses.go
  controllers/storagecluster/storageconsumer.go
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
  controllers/util/storageclasses.go
  controllers/util/storageconsumer.go
  main.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
  services/provider/server/server.go
Labels: lgtm, approved

#3128 send older subscription channel for older clients
  services/provider/server/server.go
Labels: lgtm, approved

#3135 server: implement the GetDesiredClientState rpc
  controllers/util/k8sutil.go
  controllers/util/snapshotclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/snapshotclasses.go
  services/provider/server/server.go
Labels: lgtm, approved

#3063 DFBUGS-1711: [release-4.16] : Remove duplicate placements for rook-ceph dameons due to specifying with all & specific key
  controllers/defaults/placements.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/placement_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#3144 server: fix the new rpc call
  services/provider/server/server.go
Labels: lgtm, approved

#3148 bundle: update the client op bundle
  hack/common.sh
Labels: lgtm, approved

#3064 DFBUGS-1701: [release-4.17] Delete the succeeded pods with duplicate tolerations to avoid alert
  controllers/storagecluster/cephcluster.go
  controllers/util/k8sutil.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-critical

#3146 external: fix external mode snapshot class
  controllers/storagecluster/volumegroupsnapshotterclasses.go
  controllers/storagecluster/volumesnapshotterclasses.go
Labels: lgtm, approved

#3143 add support for distributing day2 storageclasses
  config/rbac/kustomization.yaml
  config/rbac/provider_sa.yaml
  config/rbac/storageclass_cr.yaml
  config/rbac/storageclass_crb.yaml
  controllers/util/groupsnapshotclasses.go
  controllers/util/snapshotclasses.go
  controllers/util/storageclasses.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/provider-sa.yaml
  hack/source-manifests.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/groupsnapshotclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/snapshotclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
  services/provider/server/server.go
Labels: lgtm, approved

#3150 Syncing latest changes from main for ocs-operator
  config/rbac/kustomization.yaml
  config/rbac/provider_sa.yaml
  config/rbac/storageclass_cr.yaml
  config/rbac/storageclass_crb.yaml
  controllers/storagecluster/volumegroupsnapshotterclasses.go
  controllers/storagecluster/volumesnapshotterclasses.go
  controllers/util/groupsnapshotclasses.go
  controllers/util/snapshotclasses.go
  controllers/util/storageclasses.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/provider-sa.yaml
  hack/common.sh
  hack/source-manifests.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/groupsnapshotclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/snapshotclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
  services/provider/server/server.go
Labels: lgtm, approved

#3147 server: write shim for GetStorageConfig
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#3105 autoscaler: update storageautoscaler design doc
  docs/design/storage-auto-scale.md
Labels: lgtm, approved

#3122 Update rook operator and bundle images
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: lgtm, approved

#3155 Syncing latest changes from main for ocs-operator
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#3154 fix Error logs
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/storagequota.go
Labels: lgtm, approved

#3156 DFBUGS-2062: [release-4.16] add osdMaintenanceTimeout field in storagecluster CR
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3151 add priorityClassName under deployments
  config/manager/manager.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/exporter.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#3142 controllers: implement upgrade controller for provider mode
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
Labels: lgtm, approved

#3160 Revert changes from "Set bulk flag to true on intended pools for performance gain"
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/cephobjectstores_test.go
Labels: lgtm, approved

#3153 add support for distributing day2 volume[group]snapshotclasses
  config/rbac/kustomization.yaml
  config/rbac/provider_server_cr.yaml
  config/rbac/provider_server_crb.yaml
  config/rbac/storageclass_cr.yaml
  controllers/util/groupsnapshotclasses.go
  controllers/util/snapshotclasses.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/groupsnapshotclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/snapshotclasses.go
  services/provider/server/server.go
Labels: lgtm, approved

#3152 add day2 *classes to storageconsumer distribution list
  controllers/storagecluster/storageconsumer.go
  services/provider/server/server.go
Labels: lgtm, approved

#3165 controllers: fix rbac and typo for update controller
  config/rbac/role.yaml
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm

#3060 DFBUGS-1688: [release-4.17] Update github.com/go-jose/go-jose/v4 to v4.0.5 to resolve CVE-2025-27144
  api/go.mod
  api/go.sum
  api/vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  api/vendor/github.com/go-jose/go-jose/v4/README.md
  api/vendor/github.com/go-jose/go-jose/v4/jwe.go
  api/vendor/github.com/go-jose/go-jose/v4/jwk.go
  api/vendor/github.com/go-jose/go-jose/v4/jws.go
  api/vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  api/vendor/golang.org/x/sys/windows/dll_windows.go
  api/vendor/modules.txt
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  metrics/vendor/github.com/go-jose/go-jose/v4/README.md
  metrics/vendor/github.com/go-jose/go-jose/v4/jwe.go
  metrics/vendor/github.com/go-jose/go-jose/v4/jwk.go
  metrics/vendor/github.com/go-jose/go-jose/v4/jws.go
  metrics/vendor/github.com/stretchr/testify/assert/assertion_compare.go
  metrics/vendor/github.com/stretchr/testify/assert/assertion_format.go
  metrics/vendor/github.com/stretchr/testify/assert/assertion_forward.go
  metrics/vendor/github.com/stretchr/testify/assert/assertion_order.go
  metrics/vendor/github.com/stretchr/testify/assert/assertions.go
  metrics/vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  metrics/vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  metrics/vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  metrics/vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  metrics/vendor/golang.org/x/sys/windows/dll_windows.go
  metrics/vendor/modules.txt
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3065 DFBUGS-1702: [release-4.16] Delete the succeeded pods with duplicate tolerations to avoid alert
  controllers/storagecluster/cephcluster.go
  controllers/util/k8sutil.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-critical

#3080 Set mon_target_pg_per_osd to 400 for better performance from higher PG count
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#3137 DFBUGS-1033: [release 4.17] remove MDSCacheUsageHigh prometheus alert
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3139 DFBUGS-1034: [release 4.15] remove MDSCacheUsageHigh prometheus alert
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3149 osd: add a new ceph config to prevent slow ops
  controllers/storagecluster/cephconfig.go
Labels: lgtm, approved

#3173 Adding DisableRoutes to MultiCloudGateway
  api/go.mod
  api/go.sum
  api/v1/storagecluster_types.go
  api/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  api/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  api/vendor/modules.txt
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/noobaa_system_reconciler.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/modules.txt
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/bundle/deploy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/modules.txt
Labels: lgtm, approved

#3167 controllers: disable csi ctrlPlugin hostNetwork for internal client
  controllers/storagecluster/storageclient.go
Labels: lgtm, approved

#3174 cluster: update exporter and crashcollector resources
  controllers/defaults/resources.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/defaults/resources.go
Labels: lgtm, approved

#3130 storageautoscaler: add a invalid phase in cr
  api/v1/storageautoscaler_types.go
  controllers/storageautoscaler/storageautoscaler_controller.go
  controllers/storageautoscaler/verify.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageautoscaler_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageautoscaler_types.go
Labels: lgtm, approved

#3163 controllers: update the keys in the consumer configmap
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
  controllers/util/groupsnapshotclasses.go
  controllers/util/snapshotclasses.go
  controllers/util/storageclasses.go
  controllers/util/storageconsumer.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/groupsnapshotclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/snapshotclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
  services/provider/server/server.go
Labels: lgtm, approved

#3177 controllers: make client information under consumer status a pointer
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  controllers/mirroring/mirroring_controller.go
  controllers/storagecluster/odfinfoconfig.go
  controllers/storagecluster/odfinfoconfig_test.go
  controllers/storagecluster/reconcile.go
  controllers/storageconsumer/consumer_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  services/provider/server/consumer.go
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3196 skip reconciling rns if blockpool is marked for deletion
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#3070 remove StorageRequest API and controller
  PROJECT
  api/v1/storagecluster_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/storagerequest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  config/crd/bases/ocs.openshift.io_storagerequests.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storagerequests.yaml
  config/crd/patches/webhook_in_storagerequests.yaml
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/storagerequest_editor_role.yaml
  config/rbac/storagerequest_viewer_role.yaml
  config/samples/ocs_v1alpha1_storagerequest.yaml
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/storagerequest/storagerequest_controller.go
  controllers/storagerequest/storagerequest_controller_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storagerequests.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/provider-role.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/ocs-operator/manifests/storagerequest.crd.yaml
  main.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/groupversion_info.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storagerequest_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  rbac/provider-role.yaml
  services/provider/server/server.go
  services/provider/server/server_test.go
  services/provider/server/storagerequest.go
  services/provider/server/storagerequest_test.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/groupversion_info.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storagerequest_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved
