Repository red-hat-storage/ocs-operator, pull requests merged in 2025-07, with the labels that each got.

#3338 Update operator SDK version to v1.30.0
  Dockerfile.bundle
  config/default/manager_auth_proxy_patch.yaml
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/metadata/annotations.yaml
  hack/common.sh
  hack/verify-latest-csv.sh
Labels: lgtm, approved

#3335 remove storagerequest as the owner for pre419 provider mode cephclients
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
  controllers/util/k8sutil.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
Labels: lgtm, approved

#3332 controllers: update the consumer configmap default values
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageconsumer.go
  controllers/util/storageconsumer.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
Labels: lgtm, approved

#3343 Add cache folder to gitignore & remove the folder
  .gitignore
  cache/metadata.db
Labels: lgtm, approved

#3350 fix cephClients ownership and panic in consumer watches
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
Labels: lgtm, approved

#3346 DFBUGS-2840:[release-4.19] retain ceph clients keryrings created in pre4.19 deployments
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageconsumer.go
  controllers/storageconsumer/consumer_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
  controllers/util/k8sutil.go
  controllers/util/storageconsumer.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  hack/verify-latest-csv.sh
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/version/version.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  metrics/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
  services/provider/server/server.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
  version/version.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-critical

#3345 Update ocs-client-operator bundle image & it's dependencies
  hack/common.sh
  hack/install-ocs-operator.sh
Labels: lgtm, approved

#3355 ux-backend: remove hardcoded config from storageclass
  services/ux-backend/handlers/expandstorage/handler.go
Labels: lgtm, approved

#3353 Update Noobaa bundle & noobaa core images
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: lgtm, approved

#3362 Organize & cleanup the common.sh file
  Makefile
  hack/common.sh
Labels: lgtm, approved

#3330 Update to Go 1.24
  .github/workflows/ocs-operator-ci.yaml
  Dockerfile
  api/go.mod
  go.mod
  metrics/Dockerfile
  metrics/go.mod
  metrics/vendor/modules.txt
  services/provider/api/go.mod
  vendor/modules.txt
Labels: lgtm, approved

#3365 Syncing latest changes from main for ocs-operator
  .github/workflows/ocs-operator-ci.yaml
  Dockerfile
  Makefile
  api/go.mod
  controllers/storagecluster/exporter.go
  controllers/storagecluster/uninstall_reconciler.go
  controllers/util/util.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  hack/common.sh
  metrics/Dockerfile
  metrics/go.mod
  metrics/internal/cache/rbd-mirror.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/util.go
  metrics/vendor/modules.txt
  services/provider/api/go.mod
  services/ux-backend/handlers/expandstorage/handler.go
  vendor/modules.txt
Labels: lgtm, approved

#3371 Syncing latest changes from main for ocs-operator
  .github/workflows/docker-push.yaml
  .github/workflows/ocs-operator-ci.yaml
  .gitignore
  Dockerfile.catalog
  Makefile
  README.md
  api/go.mod
  api/go.sum
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  api/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/namespace.go
  api/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/pool.go
  api/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/types.go
  api/vendor/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  api/vendor/golang.org/x/net/html/atom/table.go
  api/vendor/golang.org/x/net/html/parse.go
  api/vendor/golang.org/x/net/html/token.go
  api/vendor/golang.org/x/net/http2/frame.go
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/golang.org/x/net/websocket/websocket.go
  api/vendor/modules.txt
  catalog/index.yaml
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/deploy-with-olm.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  deploy/storagecluster.yaml
  docs/catalog-generation.md
  hack/build-operator-catalog.sh
  hack/cluster-clean.sh
  hack/cluster-deploy.sh
  hack/common.sh
  hack/ensure-opm.sh
  hack/gen-deployment-yaml.sh
  hack/verify-latest-deploy-yaml.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  tools/cluster-deploy/cluster-deploy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3373 DFBUGS-2925:[release-4.19] set aliases for volumesnapshotclasses under storageconsumer spec
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  controllers/storagecluster/storageconsumer.go
  controllers/storageconsumer/storageconsumer_upgrade_controller.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  services/provider/server/server.go
  services/provider/server/server_test.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3375 Setting topologyKey in noobaa cr reconciliation
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/noobaa_system_reconciler_test.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/common.sh
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/modules.txt
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/bundle/deploy.go
  vendor/modules.txt
Labels: lgtm, approved

#3275 send vgrc from provider to client
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  controllers/util/groupreplicationclasses.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/LICENSE
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/groupversion_info.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumegroupreplication_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumegroupreplicationclass_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumegroupreplicationcontent_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumereplication_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumereplicationclass_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/github.com/openshift/api/pkg/serialization/serialization.go
  metrics/vendor/github.com/openshift/api/template/v1/codec.go
  metrics/vendor/github.com/openshift/api/template/v1/consts.go
  metrics/vendor/github.com/openshift/api/template/v1/doc.go
  metrics/vendor/github.com/openshift/api/template/v1/generated.pb.go
  metrics/vendor/github.com/openshift/api/template/v1/generated.proto
  metrics/vendor/github.com/openshift/api/template/v1/legacy.go
  metrics/vendor/github.com/openshift/api/template/v1/register.go
  metrics/vendor/github.com/openshift/api/template/v1/types.go
  metrics/vendor/github.com/openshift/api/template/v1/zz_generated.deepcopy.go
  metrics/vendor/github.com/openshift/api/template/v1/zz_generated.swagger_doc_generated.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/groupreplicationclasses.go
  metrics/vendor/modules.txt
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3376 set ceph daemons key rotation policy
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/util/env.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-unified-csv.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/env.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#3305 odf-info: add blockpools to the odf-info configmap
  api/v1alpha1/odfinfoconfig.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/mirroring/mirroring_controller.go
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/odfinfoconfig.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/k8sutil.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3381 Syncing latest changes from main for ocs-operator
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  controllers/util/groupreplicationclasses.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/LICENSE
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/groupversion_info.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumegroupreplication_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumegroupreplicationclass_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumegroupreplicationcontent_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumereplication_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumereplicationclass_types.go
  metrics/vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/github.com/openshift/api/pkg/serialization/serialization.go
  metrics/vendor/github.com/openshift/api/template/v1/codec.go
  metrics/vendor/github.com/openshift/api/template/v1/consts.go
  metrics/vendor/github.com/openshift/api/template/v1/doc.go
  metrics/vendor/github.com/openshift/api/template/v1/generated.pb.go
  metrics/vendor/github.com/openshift/api/template/v1/generated.proto
  metrics/vendor/github.com/openshift/api/template/v1/legacy.go
  metrics/vendor/github.com/openshift/api/template/v1/register.go
  metrics/vendor/github.com/openshift/api/template/v1/types.go
  metrics/vendor/github.com/openshift/api/template/v1/zz_generated.deepcopy.go
  metrics/vendor/github.com/openshift/api/template/v1/zz_generated.swagger_doc_generated.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/groupreplicationclasses.go
  metrics/vendor/modules.txt
  services/provider/server/server.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3339 Add default requests and limits for ocs-operator pods
  api/v1/storagecluster_types.go
  controllers/defaults/resources.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/defaults/resources.go
  tools/csv-merger/csv-merger.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#3385 Syncing latest changes from main for ocs-operator
  api/v1alpha1/odfinfoconfig.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/mirroring/mirroring_controller.go
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/odfinfoconfig.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/env.go
  controllers/util/k8sutil.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-unified-csv.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/env.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
  tools/csv-merger/csv-merger.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3389 Halve the CPU requests of daemons for IBM Z platform
  controllers/defaults/utils.go
  controllers/defaults/utils_test.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/defaults/utils.go
Labels: lgtm, approved

#3361 Add alerts for CephPoolNearFull and CephPoolFull
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#3302 storageclasses: automate key rotation for encrypted RBD storageclasses
  controllers/util/storageclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
  services/ux-backend/handlers/expandstorage/handler.go
Labels: lgtm, approved

#3393 Fix typo in alert query CephPoolNearFull
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#3340 metrics-exporter: add new metrics to count rbd children
  metrics/internal/cache/pv.go
  metrics/internal/cache/pv_test.go
  metrics/internal/collectors/rbd-children-count.go
  metrics/internal/collectors/registry.go
  metrics/main.go
Labels: lgtm, approved

#3394 csi: add controllerPublishSecret to ClientProfile
  services/provider/server/server.go
Labels: lgtm, approved
