Repository red-hat-storage/ocs-operator, pull requests merged in 2025-02, with the labels that each got.

#2998 Syncing latest changes from main for ocs-operator
  controllers/storagecluster/volumegroupsnapshotterclasses.go
  controllers/storagecluster/volumesnapshotterclasses.go
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2999 Rename hostname key to host in supportedLabels to resolve mismatch
  api/v1/topologymap.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/topologymap.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/topologymap.go
Labels: lgtm, approved

#3001 Fix issue with the ceph block pool rados namespace storage class
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/reconcile.go
Labels: lgtm, approved

#3003 Syncing latest changes from main for ocs-operator
  api/v1/topologymap.go
  controllers/storagecluster/external_resources.go
  controllers/storagecluster/reconcile.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/topologymap.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/topologymap.go
Labels: lgtm, approved

#3006 Fix CephFS volumes failing to mount after upgrade to 4.18 in Provider Mode
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#3012 remove the storageprofile apis
  PROJECT
  api/v1/groupversion_info.go
  api/v1/storagecluster_types.go
  api/v1/storageprofile_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storageprofiles.yaml
  config/crd/patches/webhook_in_storageprofiles.yaml
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  config/rbac/storageprofile_editor_role.yaml
  config/rbac/storageprofile_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/ocs_v1_storageprofile.yaml
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storageprofile.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/groupversion_info.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageprofile_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/groupversion_info.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageprofile_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3023 Syncing latest changes from main for ocs-operator
  PROJECT
  api/v1/groupversion_info.go
  api/v1/storagecluster_types.go
  api/v1/storageprofile_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storageprofiles.yaml
  config/crd/patches/webhook_in_storageprofiles.yaml
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  config/rbac/storageprofile_editor_role.yaml
  config/rbac/storageprofile_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/ocs_v1_storageprofile.yaml
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storageprofile.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/groupversion_info.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageprofile_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  services/provider/server/server.go
  services/provider/server/server_test.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/groupversion_info.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageprofile_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3021 added missing alert from upstream
  controllers/storagecluster/prometheus/localcephrules.yaml
Labels: lgtm, approved

#3032 DFBUGS-1323: [release-4.18] provider: update the storageID for ramen
  controllers/util/k8sutil.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#3026 provider: update the replicationID for ramen
  controllers/mirroring/mirroring_controller.go
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#3009 DFBUGS-193: [release-4.16] Upgrade hashicorp/go-retryablehttp to v0.7.7 to fix CVE-2024-6104
  api/go.mod
  api/go.sum
  api/vendor/github.com/hashicorp/go-retryablehttp/.go-version
  api/vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  api/vendor/github.com/hashicorp/go-retryablehttp/CODEOWNERS
  api/vendor/github.com/hashicorp/go-retryablehttp/Makefile
  api/vendor/github.com/hashicorp/go-retryablehttp/README.md
  api/vendor/github.com/hashicorp/go-retryablehttp/cert_error_go119.go
  api/vendor/github.com/hashicorp/go-retryablehttp/cert_error_go120.go
  api/vendor/github.com/hashicorp/go-retryablehttp/client.go
  api/vendor/modules.txt
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/hashicorp/go-retryablehttp/.go-version
  metrics/vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  metrics/vendor/github.com/hashicorp/go-retryablehttp/CODEOWNERS
  metrics/vendor/github.com/hashicorp/go-retryablehttp/Makefile
  metrics/vendor/github.com/hashicorp/go-retryablehttp/README.md
  metrics/vendor/github.com/hashicorp/go-retryablehttp/cert_error_go119.go
  metrics/vendor/github.com/hashicorp/go-retryablehttp/cert_error_go120.go
  metrics/vendor/github.com/hashicorp/go-retryablehttp/client.go
  metrics/vendor/modules.txt
  vendor/github.com/hashicorp/go-retryablehttp/.go-version
  vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  vendor/github.com/hashicorp/go-retryablehttp/CODEOWNERS
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/cert_error_go119.go
  vendor/github.com/hashicorp/go-retryablehttp/cert_error_go120.go
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3035 Use Required Pod anti affinity if Active MDS is not more than 1
  controllers/defaults/placements.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/placement_test.go
Labels: lgtm, approved

#3011 DFBUGS-1529: [release-4.15] Upgrade hashicorp/go-retryablehttp to v0.7.7 to fix CVE-2024-6104
  api/go.mod
  api/go.sum
  api/vendor/github.com/hashicorp/go-retryablehttp/.go-version
  api/vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  api/vendor/github.com/hashicorp/go-retryablehttp/CODEOWNERS
  api/vendor/github.com/hashicorp/go-retryablehttp/Makefile
  api/vendor/github.com/hashicorp/go-retryablehttp/README.md
  api/vendor/github.com/hashicorp/go-retryablehttp/cert_error_go119.go
  api/vendor/github.com/hashicorp/go-retryablehttp/cert_error_go120.go
  api/vendor/github.com/hashicorp/go-retryablehttp/client.go
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-retryablehttp/.go-version
  vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  vendor/github.com/hashicorp/go-retryablehttp/CODEOWNERS
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/cert_error_go119.go
  vendor/github.com/hashicorp/go-retryablehttp/cert_error_go120.go
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3039 Syncing latest changes from main for ocs-operator
  api/v1alpha1/odfinfoconfig.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/defaults/placements.go
  controllers/mirroring/mirroring_controller.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/noobaa_system_reconciler.go
  controllers/storagecluster/odfinfoconfig.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/placement_test.go
  controllers/storagecluster/prometheus/localcephrules.yaml
  controllers/util/k8sutil.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
  services/provider/server/server.go
  services/provider/server/server_test.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2979 Allow specifying poolSpec for default block, file, object pools from storageCluster
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/generate.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3040 Syncing latest changes from main for ocs-operator
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/generate.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3038 osd: delete completed prepare pod jobs
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#3042 provider: add missing permissions
  deploy/ocs-operator/manifests/provider-role.yaml
  rbac/provider-role.yaml
Labels: lgtm, approved

#3046 Fix broken dev build process on Mac OS & cleanup
  Dockerfile
  hack/build-metrics-exporter.sh
  hack/build-operator-bundle.sh
  hack/build-operator-catalog.sh
  hack/build-operator.sh
  hack/common.sh
  hack/ensure-operator-sdk.sh
  hack/ensure-opm.sh
  hack/gen-protobuf.sh
  hack/shellcheck-test.sh
  metrics/Dockerfile
Labels: lgtm, approved

#3050 DFBUGS-1656: [release-4.18] core: add back the CSI_DISABLE_HOLDER_PODS key on the cm
  controllers/ocsinitialization/ocsinitialization_controller.go
  controllers/util/k8sutil.go
  hack/install-ocs-operator.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-critical

#2823 Fix metrics params for k8s service monitor
  templates/k8smetricsservicemonitor.go
  templates/prometheus.go
Labels: lgtm, approved

#3052 DFBUGS-1603: [release-4.17] Use Required Pod anti affinity if Active MDS is not more than 1
  controllers/defaults/placements.go
  controllers/storagecluster/placement.go
  controllers/storagecluster/placement_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#3051 DFBUGS-1659: [release-4.15] Restore default affinity for noobaa standalone & clear if set previously
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#3048 DFBUGS-1646: [release-4.16] restore default affinity for noobaa standalone & clear if set previously
  controllers/storagecluster/noobaa_system_reconciler.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#3057 mirroring: requeue if mirroring token is not generated
  controllers/mirroring/mirroring_controller.go
  services/provider/server/server.go
Labels: lgtm, approved

#2978 Add make install Procedure to README for Installation
  README.md
Labels: lgtm, approved

#3054 DFBUGS-1667: [release-4.17] Fix conflict between SSD and HDD device classes causing CRUSH rule issue
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#3053 DFBUGS-1668: [release-4.16] Fix conflict between SSD and HDD device classes causing CRUSH rule issue
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#3056 DFBUGS-1654: [release-4.18] Delete the succeeded pods with duplicate tolerations to avoid alert
  controllers/storagecluster/cephcluster.go
  controllers/util/k8sutil.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3016 Improve TestFailureDomain for Failure Domain Key and Values
  controllers/storagecluster/topology_test.go
Labels: lgtm, approved

#3067 Allow specifying poolSpec parameters for non-resilient cephBlockPools
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3066 Allow specifying poolSpec for metadata pools of cephFS and cephObjectStore
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephobjectstores.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved
