Repository red-hat-storage/ocs-operator, pull requests merged in 2025-03, with the labels that each got.

#2968 DFBUGS-1326: [release-4.17] odf-info: stop owning the odf-info configMap
  controllers/storagecluster/odfinfoconfig.go
  controllers/storagecluster/storagecluster_controller.go
  controllers/util/predicates.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-critical

#3045 autoscale: add a design doc for auto storage scaling
  docs/design/storage-auto-scale.md
Labels: lgtm, approved

#3044 autoscaling: add new crd for automatic storage scaling
  PROJECT
  api/v1/groupversion_info.go
  api/v1/storageautoscaler_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageautoscalers.yaml
  config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageautoscalers.yaml
  docs/design/storage-auto-scale.md
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/groupversion_info.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageautoscaler_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/groupversion_info.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageautoscaler_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3077 DFBUGS-931:[release-4.18] disable provider when allowremotestorageconsumers is not set
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3079 provider: update storageid for rbd and cephfs
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#2980 Set bulk flag to true on intended pools for performance gain
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/cephobjectstores_test.go
Labels: lgtm, approved

#3086 mds: disable the mds livenessProbe
  controllers/storagecluster/cephfilesystem.go
Labels: lgtm, approved

#3082 cephblockpool: stop reconciling mirroring field
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephblockpools_test.go
Labels: lgtm, approved

#3085 Update ManageCephNonResilientPools & ManageCephRBDMirror API fields so they are not in the CR output if not specified
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephrbdmirrors.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3073 Update bundles & other images on ocs-operator
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/install-ocs-operator.sh
Labels: lgtm, approved

#3083 Specify the poolSpec API field as a pointer to avoid unneceesary empty fields in storageCluster yaml output
  api/v1/storagecluster_types.go
  api/v1/zz_generated.deepcopy.go
  controllers/storagecluster/cephblockpools.go
  controllers/storagecluster/cephblockpools_test.go
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/cephobjectstores_test.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3090 add isStorageSystem label to the storagecluster
  config/crd/kustomization.yaml
  config/crd/patches/label_in_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#3062 update storageconsumer api for centralising distribution and making it user facing
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3089 update cephcsi-op dependency
  go.mod
  go.sum
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/clientprofile_types.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/driver_types.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#3091 api: add vrc to the consumer spec
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3037 Deprecate DisableStorageClass & DisableSnapshotClass fields
  api/v1/storagecluster_types.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/volumegroupsnapshotterclasses.go
  controllers/storagecluster/volumesnapshotterclasses.go
  deploy/single-node-storagecluster-provider.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#3092 remove the storagesystem from the odfinfo configmap
  api/v1alpha1/odfinfoconfig.go
  controllers/storagecluster/external_resources_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/odfinfoconfig.go
  controllers/storagecluster/odfinfoconfig_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
  pkg/deploy-manager/config.go
  pkg/deploy-manager/storagecluster.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
Labels: lgtm, approved

#3093 mgr: disable mgr liveness and startup probe
  controllers/storagecluster/cephcluster.go
Labels: lgtm, approved

#3078 provider: add storageID to the clientInfo rpc
  services/provider/api/provider.pb.go
  services/provider/proto/provider.proto
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
Labels: lgtm, approved

#3081 provider: get the radosnamespace name from consumer configmap
  services/provider/server/server.go
Labels: lgtm, approved

#3096 unless explicitly mentioned infer providerApiServerService type from hostNetwork
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#3076 Adding metrics and alerts related to StorageAutoScaler CR
  controllers/storagecluster/exporter.go
  metrics/deploy/prometheus-ocs-rules.yaml
  metrics/deploy/rbac.yaml
  metrics/internal/collectors/ocs-client.go
  metrics/internal/collectors/registry.go
  metrics/internal/collectors/storage-auto-scaler.go
Labels: lgtm, approved

#3098 proto & api: get the client operator namespace from heartbeat
  api/v1alpha1/storageconsumer_types.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  services/provider/api/interfaces/interfaces.go
  services/provider/api/provider.pb.go
  services/provider/api/storageclient.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/storageclient.go
Labels: lgtm, approved

#3101 autoscale: avoid querying prometheus if autosclaer cr is not present
  controllers/storageautoscaler/scraper.go
Labels: lgtm, approved

#3095 storagecluster: remove unused code
  controllers/storagecluster/cephfilesystem.go
  controllers/storagecluster/cephfilesystem_test.go
  controllers/storagecluster/generate.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclasses.go
  controllers/storagecluster/storageclasses_test.go
  controllers/storagecluster/uninstall_reconciler.go
  controllers/storagecluster/volumegroupsnapshotterclasses_test.go
  controllers/storagecluster/volumesnapshotterclasses.go
  controllers/storagecluster/volumesnapshotterclasses_test.go
Labels: lgtm, approved

#3104 controllers: reconcile consumer configmap
  cache/metadata.db
  controllers/storageclusterpeer/storageclusterpeer_controller.go
  controllers/storageconsumer/consumer_test.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/k8sutil.go
  controllers/util/storageconsumer.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
  services/provider/server/server.go
Labels: lgtm, approved

#3106 ci: disable ocp catsrc
  hack/install-ocs-operator.sh
Labels: lgtm, approved

#3109 Fix issues with crds
  config/crd/bases/ocs.openshift.io_storageprofiles.yaml
  config/crd/kustomization.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageprofiles.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storageautoscaler.crd.yaml
Labels: lgtm, approved

#3108 controllers: add ceph clients for cephfs and rbd
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#3068 create storageconsumer for fresh installs
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/storagecluster/storageconsumer.go
  controllers/storagecluster/uninstall_reconciler.go
Labels: lgtm, approved

#3075 onboard a client onto already created storageconsumer based on token
  api/v1alpha1/storageconsumer_types.go
  controllers/defaults/defaults.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/storageclient.go
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/provider.go
  controllers/util/util.go
  main.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/provider.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/util.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/services/types.go
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/types.go
  services/ux-backend/handlers/onboarding/clienttokens/handler.go
  services/ux-backend/main.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
Labels: lgtm, approved

#3059 DFBUGS-1689: [release-4.18] Update github.com/go-jose/go-jose/v4 to v4.0.5 to resolve CVE-2025-27144
  api/go.mod
  api/go.sum
  api/vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  api/vendor/github.com/go-jose/go-jose/v4/README.md
  api/vendor/github.com/go-jose/go-jose/v4/jwe.go
  api/vendor/github.com/go-jose/go-jose/v4/jwk.go
  api/vendor/github.com/go-jose/go-jose/v4/jws.go
  api/vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  api/vendor/golang.org/x/sys/windows/dll_windows.go
  api/vendor/modules.txt
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  metrics/vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  metrics/vendor/github.com/go-jose/go-jose/v4/README.md
  metrics/vendor/github.com/go-jose/go-jose/v4/jwe.go
  metrics/vendor/github.com/go-jose/go-jose/v4/jwk.go
  metrics/vendor/github.com/go-jose/go-jose/v4/jws.go
  metrics/vendor/github.com/stretchr/testify/assert/assertion_compare.go
  metrics/vendor/github.com/stretchr/testify/assert/assertion_format.go
  metrics/vendor/github.com/stretchr/testify/assert/assertion_forward.go
  metrics/vendor/github.com/stretchr/testify/assert/assertion_order.go
  metrics/vendor/github.com/stretchr/testify/assert/assertions.go
  metrics/vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  metrics/vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  metrics/vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  metrics/vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  metrics/vendor/golang.org/x/sys/windows/dll_windows.go
  metrics/vendor/modules.txt
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: jira/valid-bug, jira/valid-reference

#3111 convergence: add small fixes
  controllers/storageconsumer/storageconsumer_controller.go
  controllers/util/storageclasses.go
  hack/common.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
Labels: lgtm, approved

#3117 check consumer status for clusterid before reconciling noobaaaccount
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved
