Repository red-hat-storage/ocs-operator, pull requests merged in 2025-09, with the labels that each got.

#3471 DFBUGS-3791:[release-4.20] store client info during onboard process
  services/provider/api/interfaces/interfaces.go
  services/provider/api/provider.pb.go
  services/provider/api/storageclient.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/provider/server/storageclusterpeer_test.go
  services/provider/server/test_helpers.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/storageclient.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3475 Fix no fallback_scrape_protocol specified for target with nfs metrics
  controllers/storagecluster/cephnfs.go
Labels: lgtm, approved

#3423 enable host network for rook operator
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/reconcile.go
  controllers/storagecluster/rookoperatorhostnetwork.go
  controllers/storagecluster/storagecluster_controller_test.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#3462 Correcting the alert firing timing for HighRBDCloneSnapshotCount
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved

#3448 ocs-metrics-exporter and toolbox needs to run on host network for data replication separation
  config/rbac/role.yaml
  controllers/storagecluster/cephtoolbox.go
  controllers/storagecluster/exporter.go
  controllers/storagecluster/reconcile.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-metrics-exporter-hostnetwork-role-binding.yaml
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  rbac/ocs-metrics-exporter-hostnetwork-role-binding.yaml
Labels: lgtm, approved

#3473 server: improve logging for server
  services/provider/main.go
  services/provider/server/consumer.go
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved

#3487 DFBUGS-2316: [release-4.20] server: improve logging for server
  controllers/util/replicationclasses.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/replicationclasses.go
  services/provider/main.go
  services/provider/server/consumer.go
  services/provider/server/server.go
  services/provider/server/server_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3397 Change the runbook url link to match the alert name
  metrics/deploy/prometheus-ocs-rules.yaml
Labels: lgtm, approved

#3498 Revert "set ceph daemons key rotation policy"
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/initialization_reconciler_test.go
  controllers/storagecluster/storagecluster_controller_test.go
  controllers/util/env.go
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  hack/common.sh
  hack/generate-unified-csv.sh
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/env.go
  tools/csv-merger/csv-merger.go
Labels: lgtm, approved

#3495 mds: enable the mds livenessProbe
  controllers/storagecluster/cephfilesystem.go
Labels: lgtm, approved

#3510 inform client-op not to autoapprove installplans when run in hub
  controllers/storagecluster/storageclient.go
Labels: lgtm, approved

#3507 Fix blockPool spec fields like failure domain not getting updated
  controllers/storagecluster/cephblockpools.go
Labels: lgtm, approved

#3472 DFBUGS-3796:[release-4.19] store client info during onboard process
  services/provider/api/interfaces/interfaces.go
  services/provider/api/provider.pb.go
  services/provider/api/storageclient.go
  services/provider/proto/provider.proto
  services/provider/server/consumer.go
  services/provider/server/consumer_test.go
  services/provider/server/server.go
  services/provider/server/storageclusterpeer_test.go
  services/provider/server/test_helpers.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/storageclient.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3526 consumer: create cephclients for each consumer
  controllers/storageconsumer/storageconsumer_controller.go
Labels: lgtm, approved

#3517 DFBUGS-4124: [release-4.19] Add configurable resource limits for kube-rbac-proxy containers
  controllers/defaults/resources.go
  controllers/storagecluster/exporter.go
  metrics/deploy/deployment.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/defaults/resources.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#3499 api: add nfc to storageconsumer spec
  api/v1alpha1/storageconsumer_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storageconsumer.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#3533 add default resource requests/limits for ocs-provider-server and other sidecars
  api/v1/storagecluster_types.go
  controllers/defaults/resources.go
  controllers/storagecluster/cephcluster_test.go
  controllers/storagecluster/cephtoolbox.go
  controllers/storagecluster/provider_server.go
  controllers/storagecluster/provider_server_test.go
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/defaults/resources.go
  tools/csv-merger/csv-merger.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved

#3502 enable hostNetwork and change ports for rgw for non default hostNetwork while using data replication seperation
  api/v1/storagecluster_types.go
  config/crd/bases/ocs.openshift.io_storageclusters.yaml
  controllers/storagecluster/cephcluster.go
  controllers/storagecluster/cephobjectstores.go
  controllers/storagecluster/rookoperatorhostnetwork.go
  deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
  deploy/csv-templates/ocs-operator.csv.yaml.in
  deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
  deploy/ocs-operator/manifests/storagecluster.crd.yaml
  metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Labels: lgtm, approved
